### ISSUE TITLE
Interview of ID Lock fails

### ISSUE THREAD

**Issue by slangstrom** [zwave-js/zwave-js#1037]
So I tried to include my Remotec ZRC-90, "Scene master", (yes, I do have a lot of Z-Wave devices ;)) but the inclusion fails pretty quickly. Based on the log file attached I don't even think it's being interviewed. I attached my cache-files too, there's nothing in them though.

[remoteczrc90_log.txt](https://github.com/AlCalzone/node-zwave-js/files/5362993/remoteczrc90.txt)
[eabbf325.txt](https://github.com/AlCalzone/node-zwave-js/files/5362996/eabbf325.txt)
[eabbf325.metadata.txt](https://github.com/AlCalzone/node-zwave-js/files/5362997/eabbf325.metadata.txt)
[eabbf325.values.txt](https://github.com/AlCalzone/node-zwave-js/files/5362998/eabbf325.values.txt)

**Comment by slangstrom** [comment]
I also tried to include Everspring ST812, the inclusion seems to work but got "the node is unknown or not initialized yet, discarding..." there too. Do you want me to open a separate issue for that one?

**Comment by AlCalzone** [comment]
Since both issues seem to affect the node inclusion, you can leave it here.

**Comment by AlCalzone** [comment]
> but the inclusion fails pretty quickly. Based on the log file attached I don't even think it's being interviewed.

It seems that the inclusion went through but the interview was not started afterwards although it should be. You can probably work around it by restarting your application until I've found the source of the problem.

**Comment by slangstrom** [comment]
Here's the files for Everspring ST812. When I restart and then manually wake up Remotec, the interview process gets completed. 

[e81a9a19.metadata.txt](https://github.com/AlCalzone/node-zwave-js/files/5369019/e81a9a19.metadata.txt)
[e81a9a19.txt](https://github.com/AlCalzone/node-zwave-js/files/5369020/e81a9a19.txt)
[e81a9a19.values.txt](https://github.com/AlCalzone/node-zwave-js/files/5369021/e81a9a19.values.txt)
[everspring_st812_inclusion.txt](https://github.com/AlCalzone/node-zwave-js/files/5369022/everspring_st812_inclusion.txt)

**Comment by slangstrom** [comment]
Issue with inclusion of ID Lock too, don't know if it's related to the above though. Attached log files.

[idlock_inclusion.txt](https://github.com/AlCalzone/node-zwave-js/files/5383834/idlock_inclusion.txt)

**Comment by AlCalzone** [comment]
That seems to be something else. The device is included and the interview starts immediately, but then it fails to respond to some messages. First it doesn't respond to `SecurityCCCommandsSupportedGet` which causes the driver to think it is not secure (which is wrong because it responsed to nonce requests). Then it doesn't respond to Version requests (because the `VersionCC` is probably only supported securely).

However I'm not seeing the security bootstrapping process in the log. Could it be that the device was previously included securely but you did an insecure inclusion? In that case you might have to factory-reset the device.

**Comment by slangstrom** [comment]
Alright! This was actually the first inclusion attempt after I opened the box, but let me try to reset it and try again.

**Comment by slangstrom** [comment]
So I did a hard reset of my PC Z-Wave module and then did a hard reset of the Z-Wave module on the ID Lock. Still the same, attaching the inclusion log and all the cache-files.

[c3ed057b.metadata.txt](https://github.com/AlCalzone/node-zwave-js/files/5384651/c3ed057b.metadata.txt)
[c3ed057b.txt](https://github.com/AlCalzone/node-zwave-js/files/5384652/c3ed057b.txt)
[c3ed057b.values.txt](https://github.com/AlCalzone/node-zwave-js/files/5384653/c3ed057b.values.txt)
[idlock_inclusion.txt](https://github.com/AlCalzone/node-zwave-js/files/5384654/idlock_inclusion.txt)

**Comment by AlCalzone** [comment]
This time I'm seeing the bootstrapping process succeed. But the device does something weird as soon as the driver tries to communicate securely. The normal flow is
```
--> Get Nonce
<-- Nonce Report
--> Encrypted Request
<-- Nonce Request
--> Nonce Report
<-- Encrypted Response
```

What I'm seeing is:
```
--> Get Nonce
<-- Nonce Report
--> Encrypted Request
... nothing for one second ...
<-- Encrypted Response (unknown nonce)
```

I'm not sure whats going on and where the nonce is coming from that the device uses to encrypt the response. The encrypted response is discarded because the driver did not create any nonce for that exchange.

**Comment by slangstrom** [comment]
Is there anything I can do to debug more? I tried to include it in a friends Fibaro Home Center and it worked fine.

**Comment by AlCalzone** [comment]
There's no way to see the communication logs in Home Center, is it?

**Comment by slangstrom** [comment]
Nope, they have a basic "Inclusion started", "Interviewing device", etc but nothing more... I guess it would be possible to try open-zwave, could that help somehow?

**Comment by AlCalzone** [comment]
The OZW log would probably help, yeah!

**Comment by slangstrom** [comment]
Here's the log file from OpenZWave, hope it helps!

[idlock_openzwave.txt](https://github.com/zwave-js/node-zwave-js/files/5395760/idlock_openzwave.txt)

**Comment by AlCalzone** [comment]
In this log, the node asks the controller for a nonce. Very weird. Wonder why it didn't in the other log.
Maybe try re-interviewing the node in zwave-js (or delete the cache)?

**Comment by slangstrom** [comment]
So I ran zwave-js and here's the output from the interview process. I used the same security network key in both zwave-js and OpenZWave.

[idlock_interview.txt](https://github.com/zwave-js/node-zwave-js/files/5397361/idlock_interview.txt)

**Comment by AlCalzone** [comment]
Hm that looks better - maybe a temporary hiccup?
The interview mostly goes through, except for the User Code CC which does something it shouldn't.
```
12:35:12.501 CNTRLR   [Node 002] UserCodeCC: doing a complete interview...
12:35:12.502 CNTRLR » [Node 002] querying capabilities...
12:35:12.504 CNTRLR   [Node 002] Error during node interview: Node #2 does not support the command C
                      apabilitiesGet!
```

**Comment by slangstrom** [comment]
Well, yes, the only difference is that I didn't _include_ it in zwave-js, I did that in openzwave.

**Comment by AlCalzone** [comment]
Could you try doing the same again in zwave-js now? Wonder if it has to do with the inclusion process.

**Comment by slangstrom** [comment]
You mean include it with zwave-js? Reset the lock, reset the z-wave stick and try the inclusion?

**Comment by AlCalzone** [comment]
yup

**Comment by slangstrom** [comment]
Still the same problem, tried a few times

[idlock_inclusion_new.txt](https://github.com/zwave-js/node-zwave-js/files/5401097/idlock_inclusion_new.txt)

**Comment by AlCalzone** [comment]
Did you do a complete reset? The device does not respond to the NetworkKeySet command, after which the driver must treat it as a non-secure device. The weird thing is that it asks for a nonce to send a reply, but that reply never arrives.

I'll take a look at what OZW does differently.

**Comment by slangstrom** [comment]
Yes, did a reset of both the lock and the stick. The only difference I can tell without looking at the code is that in openzwave, you pass true as an argument when doing the inclusion to enable the security inclusion process while in zwave-js it's managed automatically.

**Comment by AlCalzone** [comment]
I'll do a 1:1 comparison of the data exchange later to see if there is any difference.

**Comment by AlCalzone** [comment]
So, I've analyzed the first few messages in both inclusion logs (OZW and the last zwave-js):

**zwave-js**

1. Inclusion:
    1. NodeFound
    1. AddingSlave
    1. ProtocolDone
    1. Done
2. Security Bootstrap
```
 --> SchemeGet (0)
<--  SchemeReport (0)
 --> NonceGet (for NetworkKeySet)
<--  NonceReport
 --> CommandEncapsulation > NetworkKeySet
<--  NonceGet (for the response to NetworkKeySet!)
 --> NonceReport
... nothing ...
```

**OZW**

1. Inclusion:
    1. NodeFound
    1. AddingSlave
    1. ProtocolDone
    1. Done
2. Security Bootstrap
```
 --> SchemeGet (0)
<--  SchemeReport (0)
 --> NonceGet (for NetworkKeySet)
<--  NonceReport
 --> CommandEncapsulation > NetworkKeySet
<--  NonceGet (for the response to NetworkKeySet!)
 --> NonceReport
<--  A message that OZW does not understand.
     zwave-js parses it as NetworkKeyVerify with the configured key (the expected response to NetworkKeySet)
```

---

The communication flow is identical. The only difference I see in the logs is that OZW requires an acknowledgement for the NonceReport and does not use the "Explorer Frame" option. I'm not entirely sure why that would make a difference, but we can try that with a test build I can prepare later tonight.

**Comment by AlCalzone** [comment]
Version `5.3.2-alpha.0` will be available in a couple of minutes. Please try the inclusion with that version again and create a log. The nonce reports are now transmitted using the same options that OZW uses, so there should be no more difference in communication.

**Comment by slangstrom** [comment]
I just tried and still the same issue... I think. Did a full reset of the stick and lock and also had the lock 20-30 cm from the z-wave stick when doing the inclusion just to be sure that there were no problems with range. Attached the log.

[idlock_inclusion_alpha0.txt](https://github.com/zwave-js/node-zwave-js/files/5404077/idlock_inclusion_alpha0.txt)

**Comment by AlCalzone** [comment]
The security bootstrap process succeeds now:
```
20:48:47.236 DRIVER « [Node 002] [REQ] [ApplicationCommand]
                      └─[SecurityCCCommandEncapsulation]
                        │ sequenced: false
                        └─[SecurityCCNetworkKeyVerify]
```

But we're back to this problem https://github.com/zwave-js/node-zwave-js/issues/1037#issuecomment-709296495 now.
Looking at the OZW log it seems that it also receives an invalid response to that command, but chooses to ignore it.
I'm working on a PR to make the interview less strict in many cases, this should be one of them.
The root cause here is very non-standards-compliant behavior from your node :(

**Comment by AlCalzone** [comment]
This should be fixed in `v5.3.2`

**Comment by slangstrom** [comment]
Alright, tried all three devices in 5.3.2. Remotec, Everspring and ID-Lock. I was not able to include neither of them. Both Remotec and Everspring did same as last time. No interview for Remotec at all, and for Everspring the interview is being made but still says "unknown node" after it's done. I did a reset of everything before I began.

[everspring_st812_inclusion.txt](https://github.com/zwave-js/node-zwave-js/files/5421005/everspring_st812_inclusion.txt)
[idlock_inclusion.txt](https://github.com/zwave-js/node-zwave-js/files/5421006/idlock_inclusion.txt)
[remotec_inclusion.txt](https://github.com/zwave-js/node-zwave-js/files/5421007/remotec_inclusion.txt)

**Comment by AlCalzone** [comment]
Ohhh, I think I found whats going wrong with the remotec. It gets added as a controller, not as a slave (like all the devices I've seen so far). As a result, a variable does not get set. I'm tracking that part in https://github.com/zwave-js/node-zwave-js/issues/1069 now.

ID-Lock now gets past the inclusion process but does the same it did earlier during the inclusion. It responds without requesting a new nonce, so the driver does not know the nonce it used for encryption. I'll have to check if it is reusing previous nonces or something.

The everspring device has me confused. Directly after the inclusion, the node should be added to `controller.nodes` with the information you see in the log:
```
09:26:09.795 CNTRLR   finished adding node 3:
                        basic device class:    Static Controller
                        generic device class:  Alarm Sensor
                        specific device class: Routing Alarm Sensor
                        supported CCs: 
                        · Basic (0x20)
                        [...]
```
But the message "the node is unknown or not initialized yet" implies that the nodeid is not found in `controller.nodes`. The only location where one can be deleted is after **exclusion**.
Can you check if the `"node removed"` is emitted some time during the attempted inclusion?

**Comment by slangstrom** [comment]
1. Alright, worth noting about Remotec is that if I first include it, restart zwave-js and then waking it up, it gets interviewed and works like it should (Central Scene commands gets handled by zwave-js)
2. Ok, let me know if there's something I can do.

3. Everspring

   1. "node removed" is **not** emitted.
   2. The node is present in the cache-files
   3. For debug I put a console.log on driver.controller.nodes during the interview-process and the node is present there too, during and after the interview.
   4. I did notice it always fails on the same interview step:

 ```
20:46:10.190 CNTRLR » [Node 003] querying current value for Water Leak...
20:46:10.229 SERIAL » 0x010a001303039c0105250853                                          (12 bytes)
20:46:10.231 DRIVER » [Node 003] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      8
                      └─[AlarmSensorCCGet]
                          sensor type: Water Leak
20:46:10.236 SERIAL « [ACK]                                                                   (0x06)
20:46:10.241 SERIAL « 0x0104011301e8                                                       (6 bytes)
20:46:10.242 SERIAL » [ACK]                                                                   (0x06)
20:46:10.244 DRIVER « [RES] [SendData]
                        was sent: true
20:46:10.258 SERIAL « 0x0107001308000002e1                                                 (9 bytes)
20:46:10.259 SERIAL » [ACK]                                                                   (0x06)
20:46:10.262 DRIVER « [REQ] [SendData]
                        callback id:     8
                        transmit status: OK
20:46:11.874 CNTRLR   [Node 003] did not respond after 1/3 attempts. Scheduling next try in 500 ms.
20:46:12.389 SERIAL » 0x010a001303039c0105250853                                          (12 bytes)
20:46:12.392 DRIVER » [Node 003] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      8
                      └─[AlarmSensorCCGet]
                          sensor type: Water Leak
20:46:12.398 SERIAL « [ACK]                                                                   (0x06)
20:46:12.405 SERIAL « 0x0104011301e8                                                       (6 bytes)
20:46:12.407 SERIAL » [ACK]                                                                   (0x06)
20:46:12.410 DRIVER « [RES] [SendData]
                        was sent: true
20:46:12.420 SERIAL « 0x0107001308000002e1                                                 (9 bytes)
20:46:12.422 SERIAL » [ACK]                                                                   (0x06)
20:46:12.425 DRIVER « [REQ] [SendData]
                        callback id:     8
                        transmit status: OK
20:46:12.743 SERIAL « 0x010d00040003079c02000500000069                                    (15 bytes)
20:46:12.749 SERIAL » [ACK]                                                                   (0x06)
20:46:12.754 DRIVER « [REQ] [ApplicationCommand]
                      └─[AlarmSensorCCReport]
                          sensor type: Water Leak
                          alarm state: false
20:46:12.765 DRIVER     the node is unknown or not initialized yet, discarding...
 ```

**Comment by AlCalzone** [comment]
Remotec:
Then it has probably two modes of inclusion: Secondary controller or slave - could that be?

Regarding the everspring device:
Could you set a breakpoint [here](https://github.com/zwave-js/node-zwave-js/blob/master/packages/zwave-js/src/lib/driver/Driver.ts#L1607) and inspect `controller.nodes` as well as the detected node ID?
I'm also a bit stumped by the fact that this code is even hit during the interview. The `AlarmSensorCCReport` should be matched to the previous `AlarmSensorCCGet`.

**Comment by slangstrom** [comment]
Remotec: No, I don't think so. According to the manual this is the way to do it. I did try a few different ways but none worked. UPDATE: works in "include-controller" pull request

Everspring: attached two print screens from the debugger output

![print2](https://user-images.githubusercontent.com/20682252/96976155-c64a7200-151b-11eb-8bfd-5a238095e771.png)
![print1](https://user-images.githubusercontent.com/20682252/96976166-c8accc00-151b-11eb-8199-faf1330cfacd.png)

**Comment by AlCalzone** [comment]
Huh, `nodeId: 0`...
That seems like a bug in `AlarmSensorCCReport` (or the node sends corrupted Alarm Sensor commands).

**Comment by AlCalzone** [comment]
Yup, that's a bug in the CC implementation (or I misunderstood the specs)

**Comment by AlCalzone** [comment]
Tracking that bug in #1072, so the only thing left here is the ID Lock and its strange nonce usage.

**Comment by AlCalzone** [comment]
So, I've taken a closer look at the idlock log. The device **does** reuse nonces, which is clearly forbidden by the Z-Wave specs:

1. The driver sends a nonce (id 0x7f)
```
09:44:18.789 DRIVER » [Node 002] [REQ] [SendData]
                      │ transmit options: 0x05
                      │ callback id:      10
                      └─[SecurityCCNonceReport]
                          nonce: 0x7f216b115b3055b3
```

2. The device sends a message using that nonce
```
09:44:18.845 SERIAL « 0x01260004000220988126fbb14a2e48ea38e65073649a6585730fe5a7e7617f451 (40 bytes)
                                                                                    ^^
                      445eff88623eb25
09:44:18.845 SERIAL » [ACK]                                                                   (0x06)
09:44:18.846 DRIVER « [Node 002] [REQ] [ApplicationCommand]
                      └─[SecurityCCCommandEncapsulation]
                        │ sequenced: false
                        └─[SecurityCCCommandsSupportedReport]
                            reportsToFollow: 0
                            supportedCCs:
                            · Version
                            · Door Lock
                            · User Code
                            · Association
                            · Association Group Information
                            · Notification
                            · Firmware Update Meta Data
                            · Battery
                            controlledCCs:
```

3. a bunch of unencrypted communication

4. The driver does an encrypted request
```
09:44:18.954 DRIVER » [Node 002] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      13
                      └─[SecurityCCCommandEncapsulation]
                        │ nonce id: 47
                        └─[VersionCCGet]
```

5. The device responds, but reuses the same nonce it has used above
```
09:44:19.835 SERIAL « 0x0125000404021f9881a22080f5d642ed82adc5ac6ad6606740027d0f197f62985 (39 bytes)
                                                                                  ^^
                      ea9a71dbc5cac
09:44:19.836 DRIVER   Message with invalid data received. Dropping it
```

**Comment by AlCalzone** [comment]
Seems that the ID lock supports firmware updates - unfortunately, I can't see the current version in either OZW or here, since in both cases the VersionReport cannot be decoded. The [changelog](https://idlock.no/kundesenter/idl150updater-version/) is pretty vague regarding the Z-Wave fixes.
Could you ask the support if reusing S0 nonces is something that was fixed in an update?

**Comment by slangstrom** [comment]
Yeah, the lock supports firmware updates and the version on my lock is 1.5.6, which is the current version. I can try to contact them tomorrow. I did try to include the lock in a Homey and that worked like it should. I don't know if the log files can help but here's from the inclusion in my Homey.

[idlock_homey_inclusion.txt](https://github.com/zwave-js/node-zwave-js/files/5435897/idlock_homey_inclusion.txt)

**Comment by AlCalzone** [comment]
I'm not too familiar with the Homey log format, but I think that the same is happening there too - Homey just doesn't care like OZW.
If I'm correct, the device seems to reuse nonces after an unencrypted message exchange (lines 433ff):
```log
# Node requests a new nonce
[2020-10-25T20:17:44.752Z] Node[3]: Received application command for COMMAND_CLASS_SECURITY, data: 0x40
[2020-10-25T20:17:44.752Z] Node[3]: [COMMAND_CLASS_SECURITY] {}
[2020-10-25T20:17:44.754Z] Node[3]: [COMMAND_CLASS_SECURITY] [SECURITY_NONCE_REPORT] {"type":"Buffer","data":[17,220,166,43,149,123,179,127]}
[2020-10-25T20:17:44.755Z] Node[3]: sendData to COMMAND_CLASS_SECURITY, params 0x8011dca62b957bb37f
[2020-10-25T20:17:44.756Z] Command[56] start: sendData
[2020-10-25T20:17:44.757Z] ProcessSendData[55]: To node: 3 with data: 0x988011dca62b957bb37f and txOptions: AUTO_ROUTE,EXPLORE
[2020-10-25T20:17:44.783Z] Command[56] end: sendData

# Node responds with that nonce (ID 17)
[2020-10-25T20:17:44.814Z] Node[3]: Received application command for COMMAND_CLASS_SECURITY, data: 0x814adb0c27e5605f8ae809754ccf115d812be98a9bdd7d
[2020-10-25T20:17:44.814Z] Node[3]: [COMMAND_CLASS_SECURITY] {"Initialization Vector byte":{"type":"Buffer","data":[74,219,12,39,229,96,95,138]},"Properties1 (Raw)":{"type":"Buffer","data":[232]},"Properties1":{"Sequence Counter":8,"Sequenced":false,"Second Frame":true},"Command byte":{"type":"Buffer","data":[9,117,76,207]},"Receivers nonce Identifier (Raw)":{"type":"Buffer","data":[17]},"Receivers nonce Identifier":17,"Message Authentication Code byte":{"type":"Buffer","data":[93,129,43,233,138,155,221,125]}}
[2020-10-25T20:17:44.836Z] Node[3]: Decapsulated frame from COMMAND_CLASS_SECURITY to COMMAND_CLASS_VERSION, data 0x148001
[2020-10-25T20:17:44.836Z] Node[3]: [COMMAND_CLASS_VERSION] {"Requested Command Class (Raw)":{"type":"Buffer","data":[128]},"Requested Command Class":128,"Command Class Version (Raw)":{"type":"Buffer","data":[1]},"Command Class Version":1}
[2020-10-25T20:17:44.840Z] Command[4] status: addNode, status: INTERVIEW_CC_15_OF_15

# Controller sends an unencrypted CC
[2020-10-25T20:17:45.357Z] Command[4] status: addNode, status: INTERVIEW_MANUFACTURER_SPECIFIC
[2020-10-25T20:17:45.404Z] Node[3]: sendData to COMMAND_CLASS_MANUFACTURER_SPECIFIC, params 0x04
[2020-10-25T20:17:45.405Z] Command[57] start: sendData
[2020-10-25T20:17:45.406Z] ProcessSendData[56]: To node: 3 with data: 0x7204 and txOptions: AUTO_ROUTE,ACK,EXPLORE
[2020-10-25T20:17:45.460Z] Command[57] end: sendData

# Node replies unencrypted
[2020-10-25T20:17:45.478Z] Node[3]: Received application command for COMMAND_CLASS_MANUFACTURER_SPECIFIC, data: 0x05037300030001
[2020-10-25T20:17:45.498Z] Node[3]: [COMMAND_CLASS_MANUFACTURER_SPECIFIC] {"Manufacturer ID":{"value":883},"Product Type ID":{"value":3},"Product ID":{"value":1}}
[2020-10-25T20:17:45.503Z] Command[4] status: addNode, status: INTERVIEW_FIRMWARE_INFORMATION

# Controller requests a new nonce for the upcoming secure request
[2020-10-25T20:17:45.504Z] Node[3]: sendData to COMMAND_CLASS_VERSION, params 0x11
[2020-10-25T20:17:45.505Z] Node[3]: [COMMAND_CLASS_SECURITY] [SECURITY_NONCE_GET] {"type":"Buffer","data":[]}
[2020-10-25T20:17:45.506Z] Node[3]: sendData to COMMAND_CLASS_SECURITY, params 0x40
[2020-10-25T20:17:45.507Z] Command[58] start: sendData
[2020-10-25T20:17:45.509Z] ProcessSendData[57]: To node: 3 with data: 0x9840 and txOptions: AUTO_ROUTE,ACK,EXPLORE
[2020-10-25T20:17:45.544Z] Command[58] end: sendData
[2020-10-25T20:17:45.562Z] Node[3]: Received application command for COMMAND_CLASS_SECURITY, data: 0x80d7fbddf6da7d4dfd
[2020-10-25T20:17:45.562Z] Node[3]: [COMMAND_CLASS_SECURITY] {"Nonce byte":{"type":"Buffer","data":[215,251,221,246,218,125,77,253]}}

# Controller does an encrypted request
[2020-10-25T20:17:45.585Z] Node[3]: [COMMAND_CLASS_SECURITY] [SECURITY_MESSAGE_ENCAPSULATION] {"type":"Buffer","data":[45,89,69,38,210,34,22,220,195,191,202,215,144,172,220,243,21,218,144,71]}
[2020-10-25T20:17:45.586Z] Node[3]: sendData to COMMAND_CLASS_SECURITY, params 0x812d594526d22216dcc3bfcad790acdcf315da9047
[2020-10-25T20:17:45.586Z] Command[59] start: sendData
[2020-10-25T20:17:45.587Z] ProcessSendData[58]: To node: 3 with data: 0x98812d594526d22216dcc3bfcad790acdcf315da9047 and txOptions: AUTO_ROUTE,ACK,EXPLORE
[2020-10-25T20:17:45.628Z] Command[59] end: sendData

# Node responds encrypted (twice [!], with the already-used nonce 17)
[2020-10-25T20:17:46.471Z] Node[3]: Received application command for COMMAND_CLASS_SECURITY, data: 0x8180e207f5acd7d18eb445cc4453360a527268ec54113df90e5cc7dc5503
[2020-10-25T20:17:46.471Z] Node[3]: [COMMAND_CLASS_SECURITY] {"Initialization Vector byte":{"type":"Buffer","data":[128,226,7,245,172,215,209,142]},"Properties1 (Raw)":{"type":"Buffer","data":[180]},"Properties1":{"Sequence Counter":4,"Sequenced":true,"Second Frame":true},"Command byte":{"type":"Buffer","data":[69,204,68,83,54,10,82,114,104,236,84]},"Receivers nonce Identifier (Raw)":{"type":"Buffer","data":[17]},"Receivers nonce Identifier":17,"Message Authentication Code byte":{"type":"Buffer","data":[61,249,14,92,199,220,85,3]}}
[2020-10-25T20:17:46.714Z] Node[3]: Received application command for COMMAND_CLASS_SECURITY, data: 0x813b50bc404902fee7a071a64417b1ae82a68ba41d11d310d9bb7e119897
[2020-10-25T20:17:46.714Z] Node[3]: [COMMAND_CLASS_SECURITY] {"Initialization Vector byte":{"type":"Buffer","data":[59,80,188,64,73,2,254,231]},"Properties1 (Raw)":{"type":"Buffer","data":[160]},"Properties1":{"Sequence Counter":0,"Sequenced":false,"Second Frame":true},"Command byte":{"type":"Buffer","data":[113,166,68,23,177,174,130,166,139,164,29]},"Receivers nonce Identifier (Raw)":{"type":"Buffer","data":[17]},"Receivers nonce Identifier":17,"Message Authentication Code byte":{"type":"Buffer","data":[211,16,217,187,126,17,152,151]}}
```

I'm certain that this is a bug in the device. Other drivers just don't care, but reusing nonces is a security risk (putting aside that S0 is less secure than S2 anyways).
Please let me know if the manufacturer is going to do something about this. If not, I can implement a flag to disable nonce expiration for this device only, so that you can at least use it.

**Comment by slangstrom** [comment]
Okay, so I tried to contact ID Lock support 3 days ago (monday) and still no reply... could we do a workaround to disable the nonce expiration until they reply? I did read somewhere that even if the lock is updateable, the Z-Wave module is not, so it's possible that this is the only solution either way.

**Comment by AlCalzone** [comment]
@slangstrom The linked PR **should** fix your issue. Would you like an alpha release to test?

**Comment by roflmao** [comment]
@slangstrom The zwave module is possible to firmwareupgrade: https://idlock.no/wp-content/uploads/2019/11/OTA-guide-v1.4.pdf
I have upgraded both my idlock 150 to 1.6 firmware.

**Comment by AlCalzone** [comment]
> The zwave module is possible to firmwareupgrade:

**Note:** you don't need any extra software, you don't have to unpair the devices. Just upgrade from zwave-js

**Comment by roflmao** [comment]
@AlCalzone That is pure awesomeness! I will test it for sure on other devices.

**Comment by robertsLando** [comment]
@roflmao zwavejs2mqtt allows to do that using the UI :)

**Comment by roflmao** [comment]
@AlCalzone Trying to add my idlock 150 with the latest 1.6.0 firmware (Node 028)

[zwave-1.log](https://github.com/zwave-js/node-zwave-js/files/5691948/zwave-1.log)

**Comment by AlCalzone** [comment]
Uh that doesn't look like it works as I intended to...

Edit: The problem is that we need both the manufacturer/product ids and the firmware version to find the correct config file, but querying the firmware version already runs into this problem, so the config file is never loaded...

**Comment by AlCalzone** [comment]
@roflmao can you try the `fix-id-lock` branch?

**Comment by roflmao** [comment]
@AlCalzone Tried latest master: (Node 028)
[zwave-1.log](https://github.com/zwave-js/node-zwave-js/files/5726847/zwave-1.log)

**Comment by AlCalzone** [comment]
Hmm this issue is like whack-a-mole:
```
23:30:45.451 CNTRLR   [Node 028] trying to load device config
23:30:45.452 CNTRLR   [Node 028] no device config loaded
```

**Comment by roflmao** [comment]
EDIT: found it 0x0373/id-150_1.6.json. My bad.

@AlCalzone I dont seem to find any Idlock 150 config in the zwave-js repository either..

OZW: https://github.com/OpenZWave/open-zwave/blob/master/config/idlock/idlock150.xml

**Comment by AlCalzone** [comment]
There is one for specific firmware versions and #1212 adds a fallback one so the version CC interview can be completed:
https://github.com/zwave-js/node-zwave-js/pull/1212/files#diff-30921b89cc20aec16480118e42f425219ba2c86b65e1866bde169bd3965aba58

**Comment by roflmao** [comment]
Right.

How about a log from a complete OZW interview?

**Comment by AlCalzone** [comment]
Not necessary. Loading the device config file must succeed, so the rest of the interview can continue. I can't reproduce locally though - my test passes 🤔

**Comment by AlCalzone** [comment]
Can you please check if you have the file `config\devices\0x0373\id-150_compat.json` in the `@zwave-js/config` module? And if `id-150_compat.json` appears in the `config/devices/index.json`?

**Comment by roflmao** [comment]
Oh, i just broke my index.json because of testing https://github.com/zwave-js/node-zwave-js/pull/1236.

**Comment by AlCalzone** [comment]
If the files is there, running `yarn run config -i` should include it in the index - so all good.

**Comment by AlCalzone** [comment]
It exists on master at least:
https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/devices/index.json#L15053-L15059
https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/devices/0x0373/id-150_compat.json

**Comment by roflmao** [comment]
Still fails im afraid.
[zwave-1.log](https://github.com/zwave-js/node-zwave-js/files/5726936/zwave-1.log)

**Comment by AlCalzone** [comment]
I think we got further this time. However you're running into the same issue as https://github.com/zwave-js/node-zwave-js/issues/1219. The device does respond, but the driver is too impatient. 

You could try increasing the timeout by editing the zwavejs2mqtt sources locally:
https://github.com/zwave-js/zwavejs2mqtt/blob/306b3803d31e13e6dbdd8c0780740552135497b1/lib/ZwaveClient.js#L1295-L1298
--> add an option
```diff
      this.driver = new Driver(this.cfg.port, {
        cacheDir: storeDir,
+       timeouts: { report: 10000 }, // or even 15000
        networkKey: networkKey
      })
```

**Comment by roflmao** [comment]
Looks like the same response as before:
[zwave-1.log](https://github.com/zwave-js/node-zwave-js/files/5745132/zwave-1.log)

**Comment by robertsLando** [comment]
@roflmao With latest version now you don't need to edit the code but you can inject settings from `settings.json`, check readme, there is an hidden setting in zwave that allows to extend ZwaveOptions

**Comment by AlCalzone** [comment]
@roflmao The device simply does not respond to most requests... Aside from the security nonces, I see a total of 2 requests answered 🤷🏻‍♂️

Could you make me an OZW_Log after all?

**Comment by roflmao** [comment]
Upgraded to latest zwavejs2mqtt:dev tag on docker (1.0.0-alph2 with zwave-js 5.7.0 iirc) and suddenly it succeeds:

[zwave-1.log](https://github.com/zwave-js/node-zwave-js/files/5755054/zwave-1.log)

**Comment by AlCalzone** [comment]
I still see a shitton of `Message with invalid data received. Dropping it` (related to Nodes 28 and 29). Could you send me your network key, so I can try to investigate whats going on?

**Comment by AlCalzone** [comment]
Ok, seems like my original fix does not quite do it. These devices reuse the nonces until they request a new one and in some cases we expire the old one too early.

**Comment by AlCalzone** [comment]
@roflmao please give https://github.com/zwave-js/node-zwave-js/pull/1262 a test :)

**Comment by AlCalzone** [comment]
@roflmao I've gone ahead and merged the PR. Let me know if the issue persists.

**Comment by roflmao** [comment]
@AlCalzone Thanks, i will try to test it soon and get logs

**Comment by roflmao** [comment]
@AlCalzone  Interview completes! I havent been able to obtain the logs yet in bin nor store.

**Comment by AlCalzone** [comment]
:)
alpha.1 was bugged, alpha.2 should write the log again.

**Comment by hanskroner** [comment]
I realize I'm a bit late to this issue, hope this is still relevant. While the ID Lock in question does seem to misbehave, it doesn't seem like the problem is it reuses NONCEs. Reusing NONCEs would be a serious security issue that would call into question the reliability of the product. The product's security implementation seems sound. It does, however, seem run into issues that cause it to send the "weird" message that shows up in the logs here as "containing invalid data" and getting discarded by the driver.

As far as I can tell, the issue arises from sending a secured `VERSION_GET` command to the door lock, before its Lifeline association has been configured. The door lock makes an audible beep when this happens, similar to the sound it makes when the batteries are put it, which leads me to think it's running into some error internally. As a result of receiving the secured `VERSION_GET`, the door lock transmits a secured `VERSION_REPORT` (without asking for a new NONCE) using a NONCE it had received previously from the sender and already used to encrypt a previous reply. However, the transmission is sent out as a `BROADCAST`, not as a singlecast reply to the sender - again hinting at the device being in some error condition. While it's an issue, it seems this is a bug specific to the `VERSION_GET` command when the Lifeline association isn't configured, and not a problem with the device's Security S0 implementation,

So how do other Z-Wave Controllers get around this and work with this door lock? My guess is they're not "getting around" anything. It's probably a combination of two things:

- They're following the recommended steps that the Z-Wave Plus Role Type Specification lays out for interviewing devices after inclusion. After the protocol inclusion is completed, and security is negotiated, the first thing a controller should do with a Z-Wave Plus device is setup its Lifeline association. In this case, that is sufficient to not trigger the bug in the door lock (see traces below). I would guess neither the manufacturer nor the Certification tests caught this bug, since their interview process follows the guidelines. I also think this is reasonable, finding a bug like this would require testing far too many possibilities of interview processes.
- Even if they run into the same situation as here, they don't consider missing version information to be catastrophic and halt the interview process. The version information isn't received, they might retry once or twice, but then they move on and accept that the information is missing. While having the information is nice, not having it is fine. Sure, they won't be able to display it, and they won't be able to apply quirk fixes at higher layers that apply only to specific versions, but the device still gets included and operates.

Finally, here's two traces of inclusion for the same door lock. The only difference between them is setting up the Lifeline association. When that happens, early in the process, the device's bug doesn't get triggered and it replies fine to the `VERSION_GET` command. Note also that, in both situations, there's a lot of secured traffic before the call to `VERSION_GET` - the door lock follows the S0 specification, always requesting fresh NONCEs from the sender before replying - with the exception of the `VERSION_REPORT` broadcast described above.

[id_lock_150_fail.txt](https://github.com/zwave-js/node-zwave-js/files/5835239/id_lock_150_fail.txt)
[id_lock_150_pass.txt](https://github.com/zwave-js/node-zwave-js/files/5835246/id_lock_150_pass.txt)

The changes in the PRs related to this issue compromise the security the S0 layer provides. Extending the validity of the NONCE timer or otherwise keeping NONCEs around after they have been used, allowing messages that re-use NONCEs is against the S0 specification and a security issue - _zwave-js_ should **not** be doing this.
