### ISSUE TITLE
[5.3.1] Crash on encountering non-secure node (uncaught promise exception)

### ISSUE THREAD

**Issue by RoboPhred** [zwave-js/zwave-js#1042]
I recently upgraded zwave-js from 2 to 5, and am now encountering a hard crash during the interview process.

[zwave-9800.log](https://github.com/AlCalzone/node-zwave-js/files/5388547/zwave-9800.log)

Interestingly, with LOGTOFILE set, the error I am getting does not appear in the log, but seems to be printed to stderr by nodejs itself:

Here is the entire console output from the invocation of my program:
```
Logging to file:
D:\dev\git\RoboPhred\wutwot\packages\wutwot-server\lib\zwave-9800.log
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Node 024 supports Security, but no network key was configured. Continuing interview non-securely.
    at ZWaveNode.interviewCCs (D:\dev\git\RoboPhred\wutwot\packages\wutwot-zwave\node_modules\zwave-js\src\lib\node\Node.ts:1205:7)
    at ZWaveNode.interview (D:\dev\git\RoboPhred\wutwot\packages\wutwot-zwave\node_modules\zwave-js\src\lib\node\Node.ts:901:19)
    at Driver.interviewNode (D:\dev\git\RoboPhred\wutwot\packages\wutwot-zwave\node_modules\zwave-js\src\lib\driver\Driver.ts:783:21)
    at Driver.initializeControllerAndNodes (D:\dev\git\RoboPhred\wutwot\packages\wutwot-zwave\node_modules\zwave-js\src\lib\driver\Driver.ts:753:15)
    at Immediate.<anonymous> (D:\dev\git\RoboPhred\wutwot\packages\wutwot-zwave\node_modules\zwave-js\src\lib\driver\Driver.ts:622:5)
```

**Comment by AlCalzone** [comment]
Can you share how you initialize the driver in your code? This "error" should only be emitted as an `"error"` event on the driver, which can cause crashes if no handler is attached. 
However, this should be enforced since 5.0.0, but that doesn't seem to be working in your case.

**Comment by RoboPhred** [comment]
That would be it.  I do have an error handler set up, but [it is only used in the initialization phase](https://github.com/RoboPhred/wutwot/blob/master/packages/wutwot-zwave/src/impl/ZWaveProviderImpl.ts#L36), and is removed after the driver reports ready.  This explains how your safty check was satisfied despite not having a handler for node interviews.

I built it this way originally because I had assumed only critical errors that stop the driver from operating would be reported over "error", and in such cases I wanted the error to be thrown globally and shut down the program.

I guess this means non-fatal errors are being emitted through the error handler then.  How can I tell the difference between fatal errors that stop the zwave module from operating, and security errors like this that the driver will recover from automatically?

Ideally, errors that do not stop the operation of the driver could come from a "warning" event, leaving "error" to only trap critical failures that stop the driver cold.  A good secondary option would be to have a common base class for all z wave errors that indicates if the error is fatal or not, something like:
```
(err) => {
  if (err.recoverable) {
        // Log and continue
    log.warn(err);
  }
  else {
    // Driver has failed, shut down the program with an error code.
    log.fatal(err);
    process.exit(1);
  }
}
```

**Comment by AlCalzone** [comment]
I really should document this better. There is a common base class `ZWaveError`, which has a `code` property to identify the kind of error independent from the erroor message. So you could do:

```ts
driver.on("error", error => {
  if (error instanceof ZWaveError && error.code === ZWaveErrorCodes.Driver_Failed) {
    // fatal error
  } else {
    // non-fatal error
  }
});
```

**Comment by RoboPhred** [comment]
I had a look through the ZWaveErrorCodes, and I would rather capture and dismiss known 'good' errors rather than only look for known fatal errors and ignore the rest.

To that end, it seems the error I am encountering is not a subclass of ZWaveError:

![image](https://user-images.githubusercontent.com/6816874/96281203-deefe080-0f8d-11eb-928b-2c9a8182c33d.png)

The error seems to come from [here](https://github.com/zwave-js/node-zwave-js/blob/7b8146edc88f9c14e6700fbccebdef480a9028ed/packages/zwave-js/src/lib/node/Node.ts#L1205), and indeed it is using Error rather than ZWaveError.

Could you introduce a status code for this particular error, so I can dismiss this particular one while still bailing for all other unknown errors?

**Comment by RoboPhred** [comment]
The core resolution of this issue was that I need to always have a handler for driver errors, so this issue is completed.

I opened another issue for giving ZWaveError codes to all known errors that the driver can emit: https://github.com/zwave-js/node-zwave-js/issues/1044
