### ISSUE TITLE
Configure logging through driver options

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#1062]
Ideally, this should have preference over env variables. Things to consider:

- [ ] minimum loglevel (currently `LOGLEVEL` env variable) 
- [ ] ability to turn logging off (loglevel: off), should also be supported through the `LOGLEVEL` env variable
- [ ] ability to provide a custom transport for logs (compatible with `winston`)
- [ ] change the logfile location

**Comment by AlCalzone** [comment]
I'm open for suggestions how to elegantly pass these options through to the logger module in `packages\core\src\log\shared.ts`

**Comment by robertsLando** [comment]
> I'm open for suggestions how to elegantly pass these options through to the logger module in packages\core\src\log\shared.ts

I would make the logger a singleton instance and add a method to configure those properties

**Comment by AlCalzone** [comment]
PRs welcome :)
If you like we can get rid of the `default import`s that look like `import log from "../log"`. Auto-importing them does not work.

**Comment by robertsLando** [comment]
I dunno how singletons are managed on Typescript but I could try :)

**Comment by AlCalzone** [comment]
Just like JS :D
