### ISSUE TITLE
[bug] Wrong releases body

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwave-js#1084]
Starting from version 5.3.2 the body of releases is wrong. I think the problem is [here](https://github.com/zwave-js/node-zwave-js/blob/master/.github/workflows/test-and-release.yml#L160-L164)

**Comment by AlCalzone** [comment]
Thanks I didn't notice. Seems that the new GITHUB_ENV solution no longer supports the multiline encoding.

**Comment by AlCalzone** [comment]
Solution is similar to
```
          echo 'ENV_VAR_1<<EOF' >> $GITHUB_ENV
          echo 'foo' >> $GITHUB_ENV
          echo 'bar' >> $GITHUB_ENV
          echo 'do not eval `this`' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo 'ENV_VAR_2=single line' >> $GITHUB_ENV
```

**Comment by robertsLando** [comment]
@chrisns Does this bug reminds something to you? :laughing:

**Comment by robertsLando** [comment]
@AlCalzone What about add it to steps output?

```yaml
id: release
run |
    BODY=$(git show -s --format=%b)
    BODY="${BODY//'%'/'%25'}"
    BODY="${BODY//$'\n'/'%0A'}"
    BODY="${BODY//$'\r'/'%0D'}"
    echo "::set-output name=body::$(echo $BODY)"
```

And then

```
{{steps.release.outputs.body}}
```

**Comment by chrisns** [comment]
Urgh. Giving me flashbacks

**Comment by AlCalzone** [comment]
@chrisns Do you have a preferred solution for this? I'm just rolling with any one that works :)

**Comment by AlCalzone** [comment]
But yeah, the steps output seems somewhat clean. I think that wasn't available when I first wrote that workflow.

**Comment by chrisns** [comment]
On holiday will have a look when I'm back tomorrow

**Comment by AlCalzone** [comment]
steps.output works :)

**Comment by robertsLando** [comment]
@AlCalzone Saw it, good! :)
