### ISSUE TITLE
[bug] Undefined label for valueId CC 51

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwave-js#1087]
Label is `undefined` for:

CommandClass: `51`
Endpoint: `0`
Property: `duration`

**Comment by AlCalzone** [comment]
See, this is why I don't like enums for properties :) I already had to look up the CC id and convert it to hex to find out that this is Color Switch CC.

**Comment by robertsLando** [comment]
@AlCalzone I understand but with enums you could anyway do this without problems, the enum has a key identifier :)
