### ISSUE TITLE
Include variables in "interview failed" event to indicate if failure is final.

### ISSUE THREAD

**Issue by RoboPhred** [zwave-js/zwave-js#1104]
The "interview failed" event includes text data describing the failure, but it would be helpful if this sent a more traditional event argument object containing information like the current interview count and whether the failure is final.  My use case is I want to create a iot device entry describing the failed node, but I would like to avoid using string matching to determine when the failure is final.

In particular, I would like to be able to differentiate between the event given on retry [here](https://github.com/zwave-js/node-zwave-js/blob/4bd610941c3f545ad07f0435b3ab25aa2067f414/packages/zwave-js/src/lib/driver/Driver.ts#L806) and the final failure located [here](https://github.com/zwave-js/node-zwave-js/blob/4bd610941c3f545ad07f0435b3ab25aa2067f414/packages/zwave-js/src/lib/driver/Driver.ts#L824).

It would probably be beneficial to take a breaking change here and send an object instead of a string message, but adding the object as an additional parameter after the string would still cover the use case.

A possible event args interface might be
```ts
interface NodeInterviewFailedEventArgs {
  errorMessage: string;
  attemptCount: number;
  isFinal: boolean
}
```

**Comment by AlCalzone** [comment]
Sounds good. I think the way forward would be adding the parameter in a minor release and removing the string param in the next major release.
