### ISSUE TITLE
Interview incomplete for battery device Sensative Strips Comfort

### ISSUE THREAD

**Issue by larstobi** [zwave-js/zwave-js#1114]
When using the  zwavejs2mqtt service, I can never get it to complete the interview with battery nodes. In this example, a Sensative Strips Comfort.

I woke up the device, then chose Refresh info, and this is what happened in the log:
```
  z2m:Zwave Node 22: notification: Tampering, invalid code  +10s
  z2m:Zwave Node 22 is now awake +55ms
  z2m:App Zwave api call: refreshInfo [ 22 ] +32s
  z2m:Zwave Success zwave api call refreshInfo  +177ms
  z2m:Zwave Node 22: metadata updated: 49-0-Air temperature +11s
  z2m:Zwave Node 22: value added: 49-0-Air temperature => 26.5 +1ms
  z2m:Zwave Node 22 is now asleep +6s
```

The UI still doesn't show the Manufacturer, Product or Productcode, nor are any Configuration parameters available.

**Comment by AlCalzone** [comment]
I would need to see a logfile from zwave-js to know whats going on here. It **might** be that you are running into #1107 which I just fixed yesterday on master.

**Comment by larstobi** [comment]
@AlCalzone 
I have built zwavejs2mqtt from the latest master of node-zwave-js and tested it without success.
I got you the log file in a gist: https://gist.github.com/larstobi/96ccd8a3ffd4b115f72def01a60be619

**Comment by larstobi** [comment]
Node 22 is still a Sensative Strips Comfort.

**Comment by larstobi** [comment]
```
  z2m:Zwave Node 22 is asleep +8s
  z2m:Zwave Node 22: metadata updated: 49-0-Illuminance +883ms
  z2m:Zwave Node 22: value updated: 49-0-Illuminance 1 => 25 +1ms
  z2m:Zwave Node 22: metadata updated: 49-0-Illuminance +1s
  z2m:Zwave Node 22: value updated: 49-0-Illuminance 25 => 1 +1ms
  z2m:Zwave Node 22 is asleep +2s
  z2m:Zwave Node 22: metadata updated: 49-0-Air temperature +6s
  z2m:Zwave Node 22: value updated: 49-0-Air temperature 25.9 => 24.9 +0ms
  z2m:Zwave Node 22: metadata updated: 49-0-Air temperature +45ms
  z2m:Zwave Node 22: value updated: 49-0-Air temperature 24.9 => 24.9 +0ms
  z2m:Zwave Node 22: metadata updated: 49-0-Air temperature +1s
  z2m:Zwave Node 22: value updated: 49-0-Air temperature 24.9 => 24.9 +1ms
  z2m:Zwave Node 22 is asleep +8s
  z2m:Zwave Node 22 is asleep +7s
  z2m:Zwave Node 22 is asleep +7s
  z2m:Zwave Node 22 is asleep +3s
  z2m:Zwave Node 22 is asleep +3s
  z2m:Zwave Node 22 is asleep +3s
  z2m:Zwave Node 22 is asleep +7s
  z2m:Zwave Node 22 is asleep +7s
  z2m:Zwave Node 22 is asleep +4s
  z2m:Zwave Node 22 is asleep +5s
```

**Comment by AlCalzone** [comment]
Sorry that log doesn't really help, I only need the zwave-js part (without lines that start with `  z2m:Zwave`). AFAIK all you need to do is this:

>  * Go to Settings, Zwave section
>  * select log level (preferably DEBUG or VERBOSE if the files are getting too large)
>  * enable "log to file"

and send me the created file (should be called `zwave-<processid>.log`).

**Comment by larstobi** [comment]
@AlCalzone Here you go:
https://gist.github.com/larstobi/a644872f2cfb2b96f5a0fb2c1a0d9e5d

**Comment by AlCalzone** [comment]
It looks like you leave the driver running for a few minutes only. Some battery-powered devices take hours to wake up if you do not wake them up manually.
I do not see anything in the log that looks like the device ever woke up, so either double-check that your manual wakeup procedure is correct, or have some patience.

**Comment by larstobi** [comment]
The driver was running for two hours and ten minutes. The OpenZwave driver is usually able to poll it within that time.

By the way, Node 052 and Node 053 are both Sensative Strips Guard, and they woke up during that time and reported Door State. They still didn't get past the ProtocolInfo step.

I'll try again with Node 022 and manually wake it up.

**Comment by AlCalzone** [comment]
> The driver was running for two hours and ten minutes

```
22:02:37.387 DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                      ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                        ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                       ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                      ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                      ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
22:02:37.424 DRIVER   version 5.3.6
22:02:37.425 DRIVER   
22:02:37.425 DRIVER   starting driver...
```
I'm seeing this **fourteen times** in your log, which means that the driver wasn't running 2 hours non-stop.
It might be that you're affected by an issue I've fixed in version `5.4.0` - it is probably best if you update before doing any more tests.

> By the way, Node 052 and Node 053 are both Sensative Strips Guard, and they woke up during that time and reported Door State.

Yes, they sent messages but they did not wake up. When a device wakes up, it sends the controller a special message and actively listens for commands for a short time. Many battery-powered devices send notifications/unsolicited messages while still asleep.

**Comment by larstobi** [comment]
Okay, I didn't catch that 14 times starting driver... I left the zwavejs2mqtt running for over two hours, in fact. Does that mean the driver crashed fourteen times?

In any case, I have updated to the lastest master and did a new run where I woke Node 022 several times, but it never came beyond ProtocolInfo. The Strips is awake for ten seconds before it sleeps.

**Comment by larstobi** [comment]
It's `zwave-3.log` in the same gist:
https://gist.github.com/larstobi/a644872f2cfb2b96f5a0fb2c1a0d9e5d

It looks like it waits for a ping reply that it doesn't get, and then the Strips falls asleep.

```
18:59:21.512 DRIVER « [Node 022] [REQ] [ApplicationCommand]
18:59:21.583 DRIVER « [Node 022] [REQ] [ApplicationUpdateRequest]
18:59:21.584 CNTRLR « [Node 022] Received updated node info
18:59:21.585 CNTRLR   [Node 022] The node is now awake.
18:59:31.013 CNTRLR   [Node 022] Beginning interview - last completed stage: None
18:59:31.013 CNTRLR   [Node 022] new node, doing a full interview...
18:59:31.013 CNTRLR » [Node 022] querying protocol info...
18:59:36.957 CNTRLR « [Node 022] received response for protocol info:
18:59:36.983 CNTRLR   [Node 022] Interview stage completed: ProtocolInfo
18:59:36.983 CNTRLR » [Node 022] pinging the node...
18:59:46.960 CNTRLR   [Node 022] The node is now asleep.
18:59:46.962 CNTRLR   [Node 022] ping failed: The node is asleep
```

**Comment by AlCalzone** [comment]
Thanks I'll check it out tomorrow. The logs look pretty messed up on mobile.

I'm guessing that either the ping isn't getting prioritized correctly or should even be left out completely since we know the node is awake.

**Comment by AlCalzone** [comment]
nevermind, I found it in the original logs. It is a bug in zwavejs2mqtt:
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read property 'label' of undefined
    at ZwaveClient.initNode (/usr/src/app/lib/ZwaveClient.js:570:46)
    at ZwaveClient.onNodeReady (/usr/src/app/lib/ZwaveClient.js:275:12)
    at ZWaveNode.emit (events.js:326:22)
    at ZWaveNode.EventEmitter.emit (domain.js:483:12)
    at ZWaveNode.onReadyChange (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:433:19)
    at /usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:222:10
    at Interpreter.update (/usr/src/app/node_modules/zwave-js/node_modules/xstate/lib/interpreter.js:253:17)
    at /usr/src/app/node_modules/zwave-js/node_modules/xstate/lib/interpreter.js:125:23
    at Scheduler.process (/usr/src/app/node_modules/zwave-js/node_modules/xstate/lib/scheduler.js:60:13)
    at Scheduler.schedule (/usr/src/app/node_modules/zwave-js/node_modules/xstate/lib/scheduler.js:44:14)
    at Proxy.Interpreter.send (/usr/src/app/node_modules/zwave-js/node_modules/xstate/lib/interpreter.js:121:29)
    at ZWaveNode.onStatusChange (/usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:367:21)
    at /usr/src/app/node_modules/zwave-js/src/lib/node/Node.ts:212:10
    at Interpreter.update (/usr/src/app/node_modules/zwave-js/node_modules/xstate/lib/interpreter.js:253:17)
    at /usr/src/app/node_modules/zwave-js/node_modules/xstate/lib/interpreter.js:125:23
    at Scheduler.process (/usr/src/app/node_modules/zwave-js/node_modules/xstate/lib/scheduler.js:60:13)
```

**Comment by robertsLando** [comment]
Fixed in https://github.com/zwave-js/zwavejs2mqtt/tree/d8a26dab5fe5ded81d7ce64f252c1b04c7f073ec

**Comment by robertsLando** [comment]
@larstobi Feel free to close this if the bug is solved :)

**Comment by larstobi** [comment]
I'll rebuild and do another test run! :-)

**Comment by AlCalzone** [comment]
There's still something fishy with the interview:
```
18:59:21.585 CNTRLR   [Node 022] The node is now awake.
18:59:31.013 CNTRLR   [Node 022] Beginning interview - last completed stage: None
```
From node awake until the first message is sent takes 10s - by that time the node is asleep again.

**Comment by larstobi** [comment]
<img width="1858" alt="Screenshot 2020-11-16 at 16 03 28" src="https://user-images.githubusercontent.com/64238/99268355-57fc8500-2825-11eb-9f58-04dd4ec8b4a0.png">

**Comment by larstobi** [comment]
At least it was able to read Manufacturer and Product ID when I manually woke it up! :-)

**Comment by AlCalzone** [comment]
@robertsLando I think how you display the interview stage might lead to some confusion. The value does not tell you which stage the interview is in, but rather which stage was completed last.

**Comment by larstobi** [comment]
<img width="1611" alt="Screenshot 2020-11-16 at 16 23 12" src="https://user-images.githubusercontent.com/64238/99272402-0dc8d300-2828-11eb-99eb-4c12ff9a0615.png">

**Comment by larstobi** [comment]
One wake-up later it got Complete.

**Comment by larstobi** [comment]
Also only one occurence of the driver starting! 🎉

I added the latest debug log in https://gist.github.com/larstobi/a644872f2cfb2b96f5a0fb2c1a0d9e5d
as zwave-4.log 

I can see that Node 009 is having a hard time being Interviewed. It's a Heatit Z-TRM2 device. Maybe it deserves its own new github issue?

**Comment by robertsLando** [comment]
> I think how you display the interview stage might lead to some confusion. The value does not tell you which stage the interview is in, but rather which stage was completed last

Isn't this good? that's the actual stage

**Comment by robertsLando** [comment]
> Also only one occurence of the driver starting! tada

That was my fault, unfortunally I didn't know I could have an `undefined` deviceCOnfig in zwaveNode :confounded:

**Comment by AlCalzone** [comment]
> Isn't this good? that's the actual stage

Well, if the last completed stage is `NodeInfo`, then the driver is currently interviewing the CommandClasses, **after which** the stage gets set to `CommandClasses`.

**Comment by robertsLando** [comment]
@AlCalzone How do I get the current one so? there should be an event emitted from node like `interview update` ?

**Comment by AlCalzone** [comment]
Not trivial, the property was not intended to do that.
You could do:
* If `Complete`, use that
* If not, add 1. If the result is `RestartFromCache`, add 1 more. Display the result

But no guarantees that this won't break some time in the future.

**Comment by robertsLando** [comment]
> But no guarantees that this won't break some time in the future.

Humm need to think about that...
