### ISSUE TITLE
Automate index file update in config PRs

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#1126]
Without it, the `lint:config` check won't pick up new files.

For example we could check if a device config file was changed but the index file was not. This action could comment on the PR with a command that updates the index file automatically in the PR.

**Comment by robertsLando** [comment]
`npm run config -- -i` ?

**Comment by AlCalzone** [comment]
yep, but I was thinking in the direction of:

> **Comment from Github Actions:**
> You forgot to update the config file index. Would you like me to do that? If so, comment "update index"

> **Comment from PR author:**
> update index

> **Github Actions** creates commit with updated index file
> (triggering a new build that lints the config file)

**Comment by robertsLando** [comment]
Hehehehe that's a little bit tricky, what about simply push it when we detect that he forgot to do it?

**Comment by AlCalzone** [comment]
Hm that could probably result in merge conflicts if the author keeps working on the branch. I'd rather make it explicit.

**Comment by robertsLando** [comment]
@AlCalzone I have wrote a draft, lets discuss about this
