### ISSUE TITLE
RFC: Zwave-js CLI tool

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwave-js#1133]
What about create a command line interface tool based on zwave-js? It would be a nice tool for debugging purposes and also for some future blackbox tests

The tool could be lunched from the cli with `zwave /dev/ttyACM0` (or the path to your usb controller) and it will log to a file that could be tailed in another bash to see the actual output. Once started you can now send commands to query actual driver info and call every function of zwave-js:

Examples commands: 

```
controller beginInclusion
node ls
node <i> values ls
node <i> values get <valueId>
node <i> values set <valueId> <value>
node <i> neightbors
```

**Comment by AlCalzone** [comment]
Some thoughts:

The process should be started in the background, so you can do
```
zwave start /path/to/usb
zwave stop /path/to/usb
zwave status /path/to/usb
```
and have the option to control multiple sticks simultaneously (different processes).

---

List available serial ports (not necessarily guaranteed z-wave, we need to connect to check that)
```
zwave ls
```

---

Ability to turn on / turn off logging / change loglevel, maybe even on the fly.

**Comment by robertsLando** [comment]
@AlCalzone I think that https://github.com/zwave-js/zwave-js-server it's quite similar. Closing this :)
