### ISSUE TITLE
Support GBL format for OTA firmware upgrades of Series 700 devices

### ISSUE THREAD

**Issue by larstobi** [zwave-js/zwave-js#1173]
In order to perform firmware upgrades on SiLabs Series 700 devices,  we need to support the Gecko Bootloader (GBL) file format.

**Describe the solution you'd like**
Add the GBL format to the  guessFormat function in zwavejs.

**Describe alternatives you've considered**

**Additional context**

* Sample GBL firmware files: Update Recessed Door Sensor 7 V1.05 <https://aeotec.freshdesk.com/support/solutions/articles/6000243778-update-recessed-door-sensor-7-v1-05>)"
* Gecko Bootloader User Guide  https://www.wless.ru/files/Silabs/EFR32/ug266-gecko-bootloader-user-guide.pdf

**Comment by AlCalzone** [comment]
Should probably done together with (or after) #1174 since this will affect the same methods.
