### ISSUE TITLE
Add guessFirmwareFormat function

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwave-js#1174]
Actually guessFirmwareFormat is not present in zwave-js

**Comment by AlCalzone** [comment]
PRs welcome - the method can be copied 1:1 from https://github.com/AlCalzone/ioBroker.zwave2/blob/master/src/lib/firmwareUpdate.ts and put into https://github.com/zwave-js/node-zwave-js/blob/master/packages/core/src/util/firmware.ts
Don't forget to export from https://github.com/zwave-js/node-zwave-js/blob/master/packages/zwave-js/src/Utils.ts
