### ISSUE TITLE
isFailedNode not working on a node

### ISSUE THREAD

**Issue by roflmao** [zwave-js/zwave-js#1202]
**Describe the bug**
After running isFailedNode on all nodes (per node doesnt seem to work in zwavejs2mqtt gui) some dead nodes was removed but not Node 007 (battery device)

**Device information**
Node 007, Eurotronic Spirit 
**Logfile:** 
[zwave-1.log](https://github.com/zwave-js/node-zwave-js/files/5678407/zwave-1.log)

**Comment by AlCalzone** [comment]
```
10:25:47.567 DRIVER » [Node 007] [REQ] [SendData]
                      │ transmit options: 0x25
                      │ callback id:      3
                      └─[NoOperationCC]
...
10:26:02.296 DRIVER « [REQ] [SendData]
                        callback id:     3
                        transmit status: NoAck
```
NoAck means no acknowledgement from the node - so it is probably asleep.

The weird thing here is that this battery-powered device is not detected as a sleeping node, so it is marked as dead. Try doing a fresh interview so the potentially corrupted node info gets reset.

**Comment by roflmao** [comment]
Marked as failed after trying to send commands from the device/isFailed from zwavejs2mqtt and removed with removeNode
[zwave-1.log](https://github.com/zwave-js/node-zwave-js/files/5678830/zwave-1.log)
