### ISSUE TITLE
Clear central scene state

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwave-js#1209]
From slack discussion: 

The OZW uses a nice way on Central Scenes, which help you know if the button was pressed
From the logs, you can see it changes to Pressed 1 time and then becomes inactive again.

```
zwave2mqtt-5ff8b44c49-9xwlz z2m 2020-12-13T12:47:35.599Z z2m:Zwave zwave node 87: changed: 91-1-3:Scene 3:Inactive -> Pressed 1 Time
zwave2mqtt-5ff8b44c49-9xwlz z2m 2020-12-13T12:47:36.599Z z2m:Zwave zwave node 87: changed: 91-1-3:Scene 3:Pressed 1 Time -> Inactive
```

Zwave-js:

```
zwavejs2mqtt-7c57b959d6-5476k z2m 2020-12-13T12:53:36.697Z z2m:Zwave Node 87: value updated: 91-0-scene-004 0 => 0
```

for instance after a second becoming undefined also would be nice, and on metadata stay like this (edited) 

the above can cause issues like: Nodered expects value 0, value 0 is coming on metadata on restart nodered "thinks" is a button press!

**Comment by AlCalzone** [comment]
superseded by #1213
