### ISSUE TITLE
Add missing Neo Coolcam devices

### ISSUE THREAD

**Issue by jghaanstra** [zwave-js/zwave-js#1221]
**Is your feature request related to a problem? Please describe.**
I'd like to see some missing Neo Coolcam devices to the database.

* NEO Coolcam plug V2 NAS-WR02ZE with ID 600-4135-512 (0x0258-0x1027-0x0200)
* NEO Coolcam plug of unknown type with ID 1050-8-512 (0x041a-0x0008-0x0200)

**Comment by robertsLando** [comment]
@AlCalzone @billiaz

**Comment by robertsLando** [comment]
@jghaanstra Could you paste here the devices manual?

**Comment by jghaanstra** [comment]
I dont think there is a manual specifically for the V2 but it's similar to the V1 and the unidentified model. See the link below.

https://fccid.io/Z52NAS-WR01Z/User-Manual/User-manual-2948691

[EDIT] Just found the V2 version here.

https://github.com/mruiter/com.neo/files/5674626/NEO.Coolcam.NAS-WR02ZE.v3.pdf

**Comment by AlCalzone** [comment]
@robertsLando what about your PR?

**Comment by robertsLando** [comment]
@AlCalzone I closed my pr because the result had no sense, I used our import method but seems it didn't imported it correctly, check it out in the pr to understand

**Comment by AlCalzone** [comment]
The first one is here: https://github.com/OpenZWave/open-zwave/blob/b0afd4c60b38065fdbc57835cb3eb6035afcc00f/config/manufacturer_specific.xml#L1584
The second one doesn't exist in OZW either - so we'll need a new config file (or add it to the existing ones if applicable).

**Comment by AlCalzone** [comment]
@blhoward2 any chance those are on your TODO list?

**Comment by blhoward2** [comment]
There are some neo coolcams but it is a large number of files so finding a specific id within that is difficult. I didn't see these, but they could be there.

**Comment by ookonbekend** [comment]
Hello,

I use 4 NEO Coolcam Power Plugs V2 
With Device ID: **600-4135-512 (0x0258-0x1027-0x0200)**
and can confirm the following link contains the right information for this model (at least much better).
https://github.com/mruiter/com.neo/files/5674626/NEO.Coolcam.NAS-WR02ZE.v3.pdf

I think the following file should be renamed to **wr01z.json**
https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/devices/0x0258/nas-wr01ze.json
and adjusted like this one
https://github.com/OpenZWave/open-zwave/blob/master/config/shenzen_neo/nas-wr01z.xml

And the current one **wr01ze.json** should be like
https://github.com/OpenZWave/open-zwave/blob/master/config/shenzen_neo/nas-wr01ze.xml

When I check the values (see below) from the log after a Re-interview, you can see these are not possible with the current JSON. 

I can toggle the light by changing the value **16-112-0-3** to 0 or1 

INFO ZWAVE: Node 16: value added 16-112-0-1 => 1
INFO ZWAVE: Node 16: value added 16-112-0-2 => 1
INFO ZWAVE: Node 16: value added 16-112-0-3 => 1
INFO ZWAVE: Node 16: value added 16-112-0-4 => 0
INFO ZWAVE: Node 16: value added 16-112-0-5 => 120
INFO ZWAVE: Node 16: value added 16-112-0-6 => 1
INFO ZWAVE: Node 16: value added 16-112-0-7 => 300
INFO ZWAVE: Node 16: value added 16-112-0-8 => 16
INFO ZWAVE: Node 16: value added 16-112-0-9 => 50
INFO ZWAVE: Node 16: value added 16-112-0-10 => 13

Hopefully this information helps to solve this issue!
Many thanks for your support!

**Comment by porzino** [comment]
Hi.

The new versions have different parameters order.
I have add a comment about this problem and the current manual on this topic: https://github.com/zwave-js/node-zwave-js/issues/1997.

**Comment by AlCalzone** [comment]
Information from another issue:
![grafik](https://user-images.githubusercontent.com/17641229/110465563-d9c63600-80d4-11eb-802f-a9a8a7653a26.png)
device ID: 0x0258:0x0200:0x1027
firmware: 2.23

**Comment by AlCalzone** [comment]
Is this still an issue?

**Comment by jghaanstra** [comment]
Fixed

**Comment by ookonbekend** [comment]
> Is this still an issue?

Issue solved, thx!
