### ISSUE TITLE
UZB Z-Wave USB Stick from Z-Wave Me is detected as HS1DS Window / Door Sensor

### ISSUE THREAD

**Issue by ahochsteger** [zwave-js/zwave-js#1225]
**Describe the bug**
I'm using the UZB Z-Wave USB Stick from Z-Wave Me (https://z-wave.me/products/uzb/) with zwavejs2mqtt but zwave-js detects it as HS1DS Window/Door Sensor.

**To Reproduce**
1. Start zwavejs2mqtt with this USB stick plugged in
2. It shows up as HS1DS Window / Door Sensor
![image](https://user-images.githubusercontent.com/207989/102629272-33107000-414b-11eb-8ddf-7f6e89e16300.png)

**Device information**
Which device(s) is/are affected? UZB Z-Wave USB Stick from Z-Wave Me (https://z-wave.me/products/uzb/)
What are the node IDs? 277-1-1024 (0x0115-0x0001-0x0400)

**Logfile:**
This file contains logs from zwave-js as well as zwavejs2mqtt: [zwavejs2mqtt-uzb.log](https://github.com/zwave-js/node-zwave-js/files/5716418/zwavejs2mqtt-uzb.log)

**Comment by AlCalzone** [comment]
`packages\config\config\devices\0x0115\hs1ds.json` needs to be modified and renamed. Accepting PR
