### ISSUE TITLE
Yale Security YRD120 does not work

### ISSUE THREAD

**Issue by praveen12bnitt** [zwave-js/zwave-js#1231]
**Describe the bug**
Yale Security YRD120 door lock does not work

**To Reproduce**
Yale Security YRD120  is already added the to zwave network with zwave2mqtt. It show fine in zwave2mqtt. Then i moved to zwavejs2mqtt it shows up as a Node, but it does not identity it as a lock and the manufacturer and product also is empty.  Cannot do any operation with it in zwavejs2mqtt

**Device information**
Which device(s) is/are affected?  ale Security YRD120
What are the node IDs? 008

**Comment by praveen12bnitt** [comment]
Logs : [zwave4.log](https://github.com/zwave-js/node-zwave-js/files/5721576/zwave4.log)

Screenshot of the device in zwave2mqtt:
<img width="1005" alt="Screen Shot 2020-12-20 at 4 51 29 PM" src="https://user-images.githubusercontent.com/931290/102725415-92ee4e80-42e4-11eb-951b-b8ac761f1667.png">

Screenshot of the device in zwavejs2mqtt
<img width="1568" alt="Screen Shot 2020-12-20 at 4 55 48 PM" src="https://user-images.githubusercontent.com/931290/102725419-9d104d00-42e4-11eb-85ac-746ea64ced21.png">

**Comment by AlCalzone** [comment]
The interview fails when the driver requests the stored user codes, because an invalid message is received. Could you send me your network key (e.g. on slack) so I can try to figure out why the message is deemed invalid?

**Comment by AlCalzone** [comment]
The problem was caused by a malformed UserCode CC report. The specs require that these commands contain a code with at least 4 digits, even if the requiested code is not in use. Your device left out the code field, thus the message format validation failed.

PR #1235 fixes that - I think it is fair to allow an empty code when it is not in use.
