### ISSUE TITLE
Add a way to load additional config files aside from the bundled ones

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#1238]
e.g. for testing new device configs or devices like Z-Uno (which are basically user-programmed)

**TODOs:**
- [ ] Temporarily load some configs which add to the active db or override single files
- [ ] Specify a different device DB location which override the active db

**Comment by robertsLando** [comment]
I think we could extend this to: allow using an external devices db. Also IMO would be fine to add the possibility to store devices db to a location choosen by user. When zwavejs is lunched it will check if there is a valid index file there, if not it will copy its default db in that location

**Comment by AlCalzone** [comment]
I'm not too keen with copying. I'd rather check if there is a valid index file in the given location and just use it.

**Comment by robertsLando** [comment]
@AlCalzone The problem is when you are using docker, you need to setup volumes

**Comment by AlCalzone** [comment]
Why is that a problem?

**Comment by robertsLando** [comment]
Because usually you create only one volume for each container, in this way we have to create one also for devices db

> Specify a different device DB location which override the active db

About this, we should provide a way to download the devices db IMO, or a command to move/copy actualy db to a specified location

**Comment by robertsLando** [comment]
From our discussion:

> When not in Docker, just updating the @zwave-js/config dependency would do the trick. Applications (or zwave-js in the future) can do that automatically. Or download the tarball with npm pack @zwave-js/config, then extract the device config dir to the target folder

**Comment by blhoward2** [comment]
@AlCalzone @robertsLando Anyone reason not to just put the device files under the store and update them there? Qt-ozw does this so they are more accessible and changes persist across image updates.

**Comment by AlCalzone** [comment]
Mostly because how it is done has to be compatible with non-Docker environments. By including the config files in `@zwave-js/config` allows us to version them semantically and use `npm` to update the definitions.

The idea behind this issue to allow users to store modified files in a "safe" location, just like you ask for.
