### ISSUE TITLE
Support Aeotec Recessed Door Sensor 7

### ISSUE THREAD

**Issue by larstobi** [zwave-js/zwave-js#1259]
Support Aeotec Recessed Door Sensor 7 is currently unknown to zwave-js.

After inclusion (secure) it says:
Unknown manufacturer: 881
Unknown product: 187
Product: 2

User guide:
[Aeotec Recessed Door Sensor 7 Engineering Specification.pdf](https://github.com/zwave-js/node-zwave-js/files/5754360/Aeotec.Recessed.Door.Sensor.7.Engineering.Specification.pdf)

https://aeotec.freshdesk.com/support/solutions/articles/6000226848-recessed-door-sensor-7-user-guide-

Web UI Console Debug log during inclusion:
[recessed7.log](https://github.com/zwave-js/node-zwave-js/files/5754374/recessed7.log)

The log contains some  "DRIVER Message with invalid data received. Dropping it" messages.

**Comment by AlCalzone** [comment]
> The log contains some "DRIVER Message with invalid data received. Dropping it" messages.

That seem to be invalid encrypted messages. I need the full zwave-js log and your network key to debug further.

**Comment by larstobi** [comment]
I removed the device and re-added it, also securely, but wasn't able to reproduce the invalid data messages.

**Comment by larstobi** [comment]
Exported json of node (also, re-added so new node ID is 84):
[node_84.json](https://github.com/zwave-js/node-zwave-js/files/5754598/node_84.json.log)
