### ISSUE TITLE
[FR] Missing association group for device 0x0002/mt_2649.json

### ISSUE THREAD

**Issue by fanningert** [zwave-js/zwave-js#1265]
**Is your feature request related to a problem? Please describe.**
Not a problem, missing feature for a device. Because it's not zwaveplus, association group is not automatically recognized.

**Describe the solution you'd like**
Add association group to the device json (0x0002/mt_2649.json).
[Sorry only German] http://manuals-backend.z-wave.info/make.php?lang=DE&sku=DAN_RS-Z&cert=ZC08-14070002

**Additional context**
![image](https://user-images.githubusercontent.com/365219/103383961-f0f51000-4af4-11eb-8471-e8217e731044.png)

**Comment by AlCalzone** [comment]
I'm german, so no need to apologize for german manuals ;)
Fix up at https://github.com/zwave-js/node-zwave-js/pull/1266
