### ISSUE TITLE
Expose zwave-js version

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwave-js#1288]
Actually would be useful to expose the version of the package

Maybe just export package.json [here](https://github.com/zwave-js/node-zwave-js/blob/master/packages/zwave-js/src/index.ts)

**Comment by AlCalzone** [comment]
Or this:
https://github.com/zwave-js/node-zwave-js/blob/0dabdea5711e3ea6d552bd6e7bab75066b408827/packages/zwave-js/src/lib/driver/Driver.ts#L109

**Comment by AlCalzone** [comment]
Wanna make a PR?
