### ISSUE TITLE
check for duplicate config files 

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#1311]
@AlCalzone I think this may need another bit of work, there is now a 46202.json and a ge_46202.json that refer to the same device IDs.
Also, should there be a test added to the config checker to block having two configs for the same IDs?

__Originally posted by @jcam in https://github.com/zwave-js/node-zwave-js/pull/1303#issuecomment-756005678__

**Comment by blhoward2** [comment]
46202 should have been deleted (I removed this from my commit originally) and ge_46202 amended with the changes. It looks like you amended 46202 instead and ge_46202 wasn’t changed. That’s the only one. 

I’d just delete ge_46202 at this point so the naming convention is the same as for 46201 and 46203.

**Comment by AlCalzone** [comment]
Is the 46202 file correct the way it is?

**Comment by blhoward2** [comment]
Correct. I compared them and 46202 is correct and ahead of ge_46202.

**Comment by blhoward2** [comment]
PR submitted to delete ge_46202

**Comment by blhoward2** [comment]
@AlCalzone lint now checks for duplicate device files, so this should be closed, correct?
