### ISSUE TITLE
[feat] Add previously working questions to the bug template

### ISSUE THREAD

**Issue by blhoward2** [zwave-js/zwave-js#1320]
**Is your feature request related to a problem? Please describe.**
For debugging/troubleshooting purposes, it would be helpful to know whether a recent code change caused the problem or whether this is a brand new device to the user (and maybe it needs cofiguration). It would also be helpful to know whether it was previously working (with no config changes) with a different platform so we could go look at how that platform handles the issue if need be.

**Describe the solution you'd like**
Amend the github bug template to collect this information.

**Describe alternatives you've considered**
Asking many posters the same questions over and over.

**Additional context**
N/A

**Comment by AlCalzone** [comment]
Good point, wanna propose a change in a PR?

**Comment by blhoward2** [comment]
Yes, I can do that tonight.
