### ISSUE TITLE
Incorrect commandClass returned for Multilevel Switch CC targetValue ValueID

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwave-js#1332]
I'm not too familiar with the code, but I'm pretty sure this command class value is incorrect?

https://github.com/zwave-js/node-zwave-js/blob/fdbea264b00b480b5894789b5fac9d486ba72864/packages/zwave-js/src/lib/commandclass/MultilevelSwitchCC.ts#L101-L107

**Comment by AlCalzone** [comment]
Uhh yeah... that is definietly wrong.
