### ISSUE TITLE
[question]  How to correct behaviour of Philio PAN in-wall relay?

### ISSUE THREAD

**Issue by Swiftnesses** [zwave-js/zwave-js#1339]
Hi,

It seems the current behaviour of zwavejs2mqtt is the same as the 1st post here (3 switches, wrong behaviour):

https://github.com/OpenZWave/open-zwave/issues/2426

How can I correct this (with OZW I would modify the xml files), looking for some insight as to how to solve this kind of 'issue'.

Thank you in advance.

**Comment by AlCalzone** [comment]
I am not entirely sure, but if I understand correctly, you'll need to add the compat flag [`preserveRootApplicationCCValueIDs`](https://zwave-js.github.io/node-zwave-js/#/development/config-files?id=preserverootapplicationccvalueids) to keep the root device (endpoint 0) from being hidden.

Part of the confusion might be that OZW starts counting at 1 and zwave-js at 0.

**Comment by Swiftnesses** [comment]
Hi @AlCalzone, sounds a good place to start.

Can you point me in the right direction of how I can test this running zwavejs2mqtt in Docker?

Many thanks for the help - appreciate it.

**Comment by AlCalzone** [comment]
@robertsLando Is an easy way to test device config modifications with Docker?

**Comment by robertsLando** [comment]
@AlCalzone Actually nope. I could create an api that exec the `npm update @zwave-js/config` command?

**Comment by robertsLando** [comment]
The problem is that this in docker needs a new volume in order to make it persistent

**Comment by AlCalzone** [comment]
Okay then (until #1238 is done) we need a branch that changes this config file and @Swiftnesses can build the Dockerfile.contrib with that.

**Comment by Swiftnesses** [comment]
Not sure it helps, but I always use persistent volumes, I wasn't sure if it was possible to implement such changes via a file (a little like OZW allows mapping of a custom config directory, with associated xmls.

**Comment by Swiftnesses** [comment]
This is what I currently have in my docker volume....

<img width="646" alt="Screenshot 2021-01-11 at 10 36 40" src="https://user-images.githubusercontent.com/1001877/104170373-ef7eee00-53f8-11eb-8cd4-0ae84551895a.png">

**Comment by AlCalzone** [comment]
The included configs are not in the mapped volume. You'll find them inside the container in `node_modules/@zwave-js/config/config/devices`.
Once the mentioned PR is implemented, you'll be able to just add additional configs to the volume and zwave-js will load them over the included ones.

**Comment by Swiftnesses** [comment]
@robertsLando did I see a PR for this, if so, please let me know what I can do to test...

**Comment by AlCalzone** [comment]
@Swiftnesses please give https://github.com/zwave-js/node-zwave-js/pull/1399 a try.

**Comment by Swiftnesses** [comment]
@AlCalzone I use the mqtt docker (dev) by @robertsLando, what's the best way to deploy the fix?

**Comment by AlCalzone** [comment]
Using the Dockerfile.contrib:
https://github.com/zwave-js/zwavejs2mqtt/tree/master/docker#building-a-container-using-dockerfilecontrib

**Comment by Swiftnesses** [comment]
To make it easier I've mapped "/usr/src/app/node_modules/@zwave-js/config" in my container to a volume and modified the file as per your pull request. Is a restart / node refresh enough (it's a b**** to include this node again!).

Thanks :)

**Comment by AlCalzone** [comment]
yep, just refresh the node info

**Comment by Swiftnesses** [comment]
I've been waiting for the zwave network to come back up - I have run a refresh and then rediscovered the node. A new switch did appear! Sadly the node stopped responding (likely unrelated) - I'll try again in the morning :)

**Comment by AlCalzone** [comment]
were you able to test yet?

**Comment by Swiftnesses** [comment]
Howdy @AlCalzone I did, but it wasn't working as expected - the extra switch appeared and seemed to control the light, but the status wouldn't stay 'on', after turning it on, the light does in fact come on, but the switch then turns 'off' straight away, so the status is all wrong :(

What do you need to debug this?

**Comment by Swiftnesses** [comment]
Apologies for the slow response - the sensor is in my workshop and it's horrible outside, plus my kids are at home (COVID!).

**Comment by AlCalzone** [comment]
I think what you're seeing is just another case of all the issues concerning wrong status reports.

**Comment by Swiftnesses** [comment]
Perhaps - I don't know, but my initial thought was without the switch showing the right status in Home Assistant, it's not going to be useful. Is there a fix coming, I'll retest if there is..

Thanks :)

**Comment by Swiftnesses** [comment]
@AlCalzone just wondering if the status report fix is coming, until then I'll try and replace the node...

**Comment by Swiftnesses** [comment]
BTW, I confirm it seems to be a switch status issue in Home Assistant. If I switch it on, the light comes on (the switch then goes off, the light remains on). If I quickly turn the switch on and off, the light goes off (obviously the switch goes off, as it always does 😄).

**Comment by AlCalzone** [comment]
The problem is that zwave was not designed in a way that really supports mirroring the true status of devices. Almost all the integrations work around that by polling (which can quickly saturate the network) if the device does not send status updates by itself (which only newer devices do).

I can "fix" the part of a wrong status after changing it through zwave-js, but if the device does not report manual changes, it must be polled regularly. That also means your mirrored status **will** be delayed.

**Comment by Swiftnesses** [comment]
The question is, is the status wrong because of something in zwave-js (with this device, or with status updates in general), or is it because we need to poll the device? I remember in OZW that I only needed to poll when I switched things at the wall (to ensure status matched), I didn't need to poll to get what we're fighting with here working - so my feeling is it's status related (a bug?).

**Comment by AlCalzone** [comment]
OZW does verify the value change after setting it differently and I'm going to try and change that in zwave-js too.

**Comment by Swiftnesses** [comment]
I trust in your knowledge - for now I'll try and find another relay. Give me a shout if I can help test anything!
