### ISSUE TITLE
Add Philio PAT02-A

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#1343]
http://manuals-backend.z-wave.info/make.php?lang=DE&sku=PHIEPAT02-A&cert=ZC10-15040009

Similar to -B and -C

**Comment by stajodude** [comment]
I have a PAT02-1C. How can I help?

**Comment by AlCalzone** [comment]
You could add a config file for the -A version

**Comment by NoellvanH** [comment]
I have a configuration File maybe this works.

[pat02-a.json.txt](https://github.com/zwave-js/node-zwave-js/files/5888928/pat02-a.json.txt)

**Comment by NoellvanH** [comment]
It is working fine now. Thanks.
![grafik](https://user-images.githubusercontent.com/33038587/106498705-ef39b600-64bf-11eb-85ff-95503e65dad3.png)
