### ISSUE TITLE
Use `type: 'duration'` for Duration valueIds

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwave-js#1348]
Ref. https://github.com/zwave-js/zwavejs2mqtt/issues/185

**Comment by AlCalzone** [comment]
In addition we should consider https://github.com/zwave-js/zwavejs2mqtt/issues/185#issuecomment-758256815

**Comment by robertsLando** [comment]
> Keep Duration objects, but give library users a way to work with them (zwave-js/node-zwave-js#1348 as a first step)
Add a method to serialize them as either a timespan string like you proposed or the current object format
Add a method to deserialize them from a timespan string or the current object format. Trying to use an invalid combination will throw.
Devs can then decide whether they need to work with timespan strings, value+unit objects or the original Duration object.
