### ISSUE TITLE
Add iblinds v3 device config

### ISSUE THREAD

**Issue by decairn** [zwave-js/zwave-js#1367]
**Is your feature request related to a problem? Please describe.**
iblinds v3 window blinds motor device configuration is missing and I have one of these to add to my network.

**Describe the solution you'd like**
New device configuration file added to zwavejs
OpenZwave configuration file - https://github.com/OpenZWave/open-zwave/blob/master/config/hab/iblindsV3.xml
Z-Wave product catalogue - https://products.z-wavealliance.org/Search/ProductDetails?productId=4009&selectedFrequencyId=2

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by AlCalzone** [comment]
@zwave-js-bot import config 0x0287-0x0071-0x0004 from ozw
