### ISSUE TITLE
Correctly parse `Compatibility` flags when importing OZW config file

### ISSUE THREAD

**Issue by robertsLando** [zwave-js/zwave-js#1371]
Check for example https://github.com/OpenZWave/open-zwave/blob/master/config/building36/b36-t10.xml

Ref #1370

**Comment by AlCalzone** [comment]
We need to figure out what they mean and how they translate to our format.

**Comment by robertsLando** [comment]
@AlCalzone IMO it mean you have to override/add those CC using that props instead of the one reported from the device

**Comment by AlCalzone** [comment]
so roughly it translates to `compat.commandClasses.add`. Does this only affect the root endpoint or individual endpoints too?

**Comment by robertsLando** [comment]
It depends if there is the `<Instance>` specified (instance is the endpoint).

```xml
<Instance index="1" />
```

**Comment by AlCalzone** [comment]
Guess we could try converting that to our compat options.

Accepting PR 😀

**Comment by robertsLando** [comment]
Will look at that this afternoon if I find some time :)

**Comment by blhoward2** [comment]
> We need to figure out what they mean and how they translate to our format.

https://github.com/OpenZWave/open-zwave/wiki/CommandClass-Compatibility-Flags

**Comment by AlCalzone** [comment]
Oh nice. That also means that the linked file above doesn't actually use any compat flags.

**Comment by robertsLando** [comment]
> Oh nice. That also means that the linked file above doesn't actually use any compat flags.

Yep

**Comment by blhoward2** [comment]
Is that an ozw 1.4 or 1.6 config file? I don’t recall seeing explicit mappings like that in other 1.6 files, though maybe that one just didn’t map right on its own.
