### ISSUE TITLE
Add property to Driver to return driver state

### ISSUE THREAD

**Issue by cgarwood** [zwave-js/zwave-js#1376]
**Is your feature request related to a problem? Please describe.**
If you fire up zwave-js with zwave-js-server but have an application connect to the zwave-js-server after the "driver ready" and/or "all nodes ready" events have fired, there's not a good way for the application to know the state of the network since it missed those events.

**Describe the solution you'd like**
My recommendation is for an additional property on the Driver class that returns the state of the network. ZWave-JS core could update that property when it emits the event. That way if an application fires up and misses one of the events it can still easily know what state the network is in.

**Comment by AlCalzone** [comment]
Off the top of my head:
- driver ready?
- which nodes ready?
- all nodes ready?
- interview for which nodes completed?

**Comment by cgarwood** [comment]
Important states I can think of from an application standpoint:
- is the driver ready
- are all nodes queried or are we still querying

**Comment by AlCalzone** [comment]
@cgarwood I've opened PR #1396 to add two properties (driver ready, all nodes ready). I think this should be enough for your use case. If not, let me know.
You should be able to check whether all queries are done using
```ts
const allInterviewsCompleted = [...driver.controller.nodes.values()].every(n => n.interviewStage === InterviewStage.Complete);
```
