### ISSUE TITLE
propertyKeyName seems not to be exposed for Meter CC

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#1389]
... and maybe others.

**Comment by AlCalzone** [comment]
@robertsLando FYI, people seem to be getting topics like `50/1/value/65537` instead of `50/1/value/electric_kWh_consumed` because of this

**Comment by bdbogjoe** [comment]
let me know if you need any testing

**Comment by robertsLando** [comment]
> @robertsLando FYI, people seem to be getting topics like 50/1/value/65537 instead of 50/1/value/electric_kWh_consumed because of this

Oh that's bad :cry:

**Comment by AlCalzone** [comment]
![grafik](https://user-images.githubusercontent.com/17641229/104616883-1f452480-568b-11eb-9652-1adc9fe7acbf.png)

I can't reproduce. Two different tests, both claim that the propertyKeyName is there. Any chance that property gets lost somewhere in zwavejs2mqtt?

**Comment by AlCalzone** [comment]
~~Might be~~ Most likely because of https://github.com/zwave-js/zwavejs2mqtt/issues/239
