### ISSUE TITLE
Popp Keypad not included successfully

### ISSUE THREAD

**Issue by Swiftnesses** [zwave-js/zwave-js#1405]
Good day,

I'm trying to add my zwave keypad (http://manuals-backend.z-wave.info/make.php?lang=en&sku=POPE700045)

Sadly, activating an inclusion doesn't seem to do anything, perhaps it's not supported? :(

**Comment by robertsLando** [comment]
@Swiftnesses Please attach a log so we can debug this

**Comment by Swiftnesses** [comment]
Working on it now...

**Comment by Swiftnesses** [comment]
Got it added - just need to try and make sense of the 30+ items and settings that get added! 

Will report back if I fail to make sense of it, or get it working!
