### ISSUE TITLE
Support for Zooz Zen31 RGBW LED Dimmer

### ISSUE THREAD

**Issue by jcam** [zwave-js/zwave-js#1418]
Ask bot for Zen31 driver

**Comment by jcam** [comment]
@zwave-js-bot import config 0x027a-0x0902-0x2000 from ozw

**Comment by jcam** [comment]
Well, that didn't work. Opened this instead:
https://github.com/zwave-js/node-zwave-js/pull/1420

**Comment by AlCalzone** [comment]
That command is limited to @robertsLando  and me because it would effectively give people write access to the repo.
