### ISSUE TITLE
Unable to set setpoint temperature without decimal for Everspring AC301

### ISSUE THREAD

**Issue by andresn81** [zwave-js/zwave-js#1421]
**Describe the bug**

I'm trying to set the temperature for my Everspring AC301 but it only works when doing numbers with a decimal, for example 22.5 works but not 22, 22.1 works, etc. 

**Device information**

Which device(s) is/are affected (make/model)?  Everspring AC301
What are the node IDs? 8

**Last Known Working Configuration**
- [x] New device

**Installation information**
How did you install `node-zwave-js`?
- [x] Pkg

**Additional context**
I remembered that I saw something about Heatit TRM3 a while ago ([link here](https://github.com/OpenZWave/open-zwave/files/5483761/Test.of.thermostat.Setpoint.Command.Class.pdf)) where they said that if the precision is wrong, the temperature will not be set. 

So... I went into core/values/primitive.js and had a look. Found encodeFloatWithScale() and I tried to see what the precision returned for 21 and 21.5. For 21, it was 0 (which converted the value to "21") and for 21.5 it was 1 (which converted the value to "215"). Then I hard-coded the precision to 1 in encodeFloatWithScale(), restarted zwave-js and BANG. It worked like a charm.

I don't know where the real issue is though, if there is different interpretations of the zwave standard or a bug in zwave-js. 

**Logfile:**

Included a few different logfiles:

[set_21_celsius.txt](https://github.com/zwave-js/node-zwave-js/files/5825062/set_21_celsius.txt)
[set_22_celsius.txt](https://github.com/zwave-js/node-zwave-js/files/5825064/set_22_celsius.txt)
[set_22.1_celsius.txt](https://github.com/zwave-js/node-zwave-js/files/5825065/set_22.1_celsius.txt)
[set_23.5_celsius.txt](https://github.com/zwave-js/node-zwave-js/files/5825066/set_23.5_celsius.txt)

This is the logfile for when I changed the precision to 1:
[set_22_celsius_precision_1.txt](https://github.com/zwave-js/node-zwave-js/files/5825063/set_22_celsius_precision_1.txt)

**Comment by AlCalzone** [comment]
Can you show me your cache files too please?

**Comment by andresn81** [comment]
Sure, here they are.

[f688c43c.txt](https://github.com/zwave-js/node-zwave-js/files/5825135/f688c43c.txt)
[f688c43c.metadata.txt](https://github.com/zwave-js/node-zwave-js/files/5825134/f688c43c.metadata.txt)
[f688c43c.values.txt](https://github.com/zwave-js/node-zwave-js/files/5825136/f688c43c.values.txt)

**Comment by AlCalzone** [comment]
Ok that does look like a misinterpretation of the Z-Wave specs by the device. The device manual mentions that the setpoint precision is 1:
![grafik](https://user-images.githubusercontent.com/17641229/104823256-29148680-5849-11eb-9cde-246aea353d33.png)

The specs say that the precision is used to indicate how many decimal places are included in the Value field - so that's related to how the current command is meant to be interpreted. There is no mention of a fixed precision or anything alike.

**Comment by andresn81** [comment]
Alright, I guess Heatit does the same with TRM3. Maybe there needs to be some kind of flag in the config for these devices then. Or if the precision could be set manually when sending the command.

**Comment by AlCalzone** [comment]
I'll add a flag.

**Comment by kpine** [comment]
This is the OZW issue for the TRM3: https://github.com/OpenZWave/open-zwave/issues/2435. Not sure if it's the same as this, but that problem was due to the size value. The device requires the size to always be 2 bytes even if the encoded value could fit in one byte.

**Comment by AlCalzone** [comment]
Seems to be very similar. My plan is to add a compat flag to fix the setpoint encoding parameters to specific values.

FYI: The recommended fix for TRM3 is to upgrade the firmware ;)

**Comment by kpine** [comment]
> FYI: The recommended fix for TRM3 is to upgrade the firmware ;)

From my amateur viewpoint, I would agree, but Heat-it is adamant that they have done it to spec and the firmware is a "workaround" for OZW. 🤷‍♂️

**Comment by AlCalzone** [comment]
> From my amateur viewpoint, I would agree, but Heat-it is adamant that they have done it to spec and the firmware is a "workaround" for OZW.

Yeah I can't get it into my head how anyone would interpret the specs that way. But I've also read that they only released an inofficial firmware because they can't change it without losing certification. 🤷🏻‍♂️

**Comment by jcam** [comment]
Would other thermostats fail if there was always a decimal? i.e. generalize by always sending 20.0?

**Comment by AlCalzone** [comment]
I don't like to do workarounds by default.

**Comment by AlCalzone** [comment]
@andresn81 try https://github.com/zwave-js/node-zwave-js/pull/1443 please

**Comment by andresn81** [comment]
Sure, I'll try tonight. Also bought a Z-TRM3, will install it and try there too.

**Comment by AlCalzone** [comment]
Oh that's perfect!
@larstobi can you check too please? I can't find the unofficial firmware anymore, so this might interest more Z-TRM3 users.

**Comment by larstobi** [comment]
I don't have the official firmware either... Maybe @roflmao has it?

**Comment by roflmao** [comment]
My three Z-TRM3's have the modified firmware :\

**Comment by AlCalzone** [comment]
I meant checking with the unofficial firmware if they still work with this change :)

**Comment by roflmao** [comment]
Just set the setpoint to a value and it worked, any special temperatures you want me to test?

**Comment by AlCalzone** [comment]
maybe a whole number once and then one with a decimal point.

**Comment by roflmao** [comment]
@AlCalzone both 22 and 23,5 works ;)

**Comment by AlCalzone** [comment]
So now I just need verification that @andresn81's device works too

**Comment by andresn81** [comment]
I have now tried both devices and they are working properly, it is possible to change the setpoint on them.
