### ISSUE TITLE
[feat] hexColor updates three times, when set - HASS jumps around

### ISSUE THREAD

**Issue by LordMike** [zwave-js/zwave-js#1454]
**Is your feature request related to a problem? Please describe.**
When changing the `hexColor` (which works great, btw..), three updates are pushed back - one for each component with gradually changing hexColors.. Like, if I push out `ffffff` to something that has `000000` today.. It reports back `ff0000`, `ffff00` and finally `ffffff`.

In HASS, this means the colorpicker, and shown color bounce around, like shown in the gif below.

**Describe the solution you'd like**
.. I don't know.. delay reporting the update?.. Is it possible to batch-set three values at once, so only one report occurs?

**Describe alternatives you've considered**
N/A

**Additional context**
![recording](https://user-images.githubusercontent.com/1027111/105083154-d29b8800-5a94-11eb-8d08-f46bde89161f.gif)

**Comment by jcam** [comment]
I was going to mention, this may be a good case to remove the "gets" entirely, but looks like you're already there.
