### ISSUE TITLE
First Alert ZWave Combo [question] 

### ISSUE THREAD

**Issue by ragenhe** [zwave-js/zwave-js#1466]
I've converted from Home Assistant native zwave support to zwavejs2mqtt.

So far so good.  I hope to contribute to this great project.

Is the First Alert ZWave Combo Smoke / CO2 detector supported?

I have excluded it and included it without issue.  I know it can take some time for a battery device to complete the query process, but I'm not sure if it is just taking a while to show it's details or if it is possible not supported.

Thank you!!

**Comment by blhoward2** [comment]
Note that this device has always been terrible to interview under any hub. You generally have to remove the battery and close the door with the button down multiple times to complete the interview process.

```
There is another thread about issues pairing with this device. Summary:

Pair it as stated in the manual. It will go to sleep before finishing, and HA will report “initializing”.
Pull the battery tray out, wait a few seconds. Push test button and keep depressed, insert battery tray. Release button immediately when the device beeps.
Repeat step 2 until HA reports “sleeping” for the device. At this point, I only had a battery_level sensor.
Restart HA. You should now see _alarm_level and _alarm_type sensors for this node.
```
https://community.home-assistant.io/t/first-alert-smoke-detector-and-carbon-monoxide-alarm-setup/66761/42?u=blhoward2

**Comment by ragenhe** [comment]
Yes, it can be a pain, and I've tried from many angles.

So much so the family is over me messing with the thing, LOL.

I'm game to try anything, even a new hub, but this device and hub have been paired prior to using zwavejs.

I'll be patient and wait.  The project is great and I want to help it advance.

**Comment by blhoward2** [comment]
I didn’t mean that there isn’t a problem here. I should have been clearer. That was a note for @AlCalzone that it may still be abnormal in the logs/procedure.

**Comment by ragenhe** [comment]
@blhoward2 - I didn't take it that way, no worries at all!!

**Comment by AlCalzone** [comment]
@ragenhe please try #1505

**Comment by ragenhe** [comment]
I updated my dev docker image. I then entered the container and updated via npm install zwave-js@6.1.1-0-pr-1505-0102cdc.

I then manually woke the device up twice.  I'll give it a little while and will continue the process.

Thanks!

**Comment by AlCalzone** [comment]
if it doesn't work, log please ;)

**Comment by ragenhe** [comment]
I'm going to continue waking the device and then waiting to see if the end result goal is reached.
Node 021

![Screen Shot 2021-01-27 at 9 59 09 AM](https://user-images.githubusercontent.com/19781098/106009527-6ddcc080-6086-11eb-9b9e-02f3d4688d73.png)


But here are the logs so you can see if it is reacting as expected at this point in the process.
[zwavejs2mqtt.log](https://github.com/zwave-js/node-zwave-js/files/5880992/zwavejs2mqtt.log)
[zwavejs_1.log](https://github.com/zwave-js/node-zwave-js/files/5880993/zwavejs_1.log)

**Comment by ragenhe** [comment]
Because this device can be..... is..... difficult, I want to make sure I give you everything I have.

I again manually woke this device up twice and then restarted the container.

No progress towards in result goal.  Logs are attached.

[zwavejs_1.log](https://github.com/zwave-js/node-zwave-js/files/5881603/zwavejs_1.log)
[zwavejs2mqtt.log](https://github.com/zwave-js/node-zwave-js/files/5881604/zwavejs2mqtt.log)

**Comment by ragenhe** [comment]
Another manual wake up....

![Screen Shot 2021-01-27 at 11 55 01 AM](https://user-images.githubusercontent.com/19781098/106025289-98367a00-6096-11eb-9954-699e35a930af.png)

**Comment by AlCalzone** [comment]
Okay, I'll take a look at your logs later

**Comment by ragenhe** [comment]
The status in the screen shot it the same still.  Here are the most recent logs.

No rush! Thanks so much!!!

[zwavejs2mqtt.log](https://github.com/zwave-js/node-zwave-js/files/5882387/zwavejs2mqtt.log)
[zwavejs_1.log](https://github.com/zwave-js/node-zwave-js/files/5882388/zwavejs_1.log)

**Comment by AlCalzone** [comment]
```
13:52:01.268 DRIVER   version 6.0.2
```
@ragenhe doesn't look like your build is actually using the new version.

**Comment by ragenhe** [comment]
I ran this from within the container
`npm install zwave-js@6.1.1-0-pr-1505-0102cdc`

is this the correct approach to update?

**Comment by AlCalzone** [comment]
I don't think so. ==> https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/docker_custom_builds

**Comment by ragenhe** [comment]
I'm on it.  Thanks!

**Comment by ragenhe** [comment]
@AlCalzone - I have followed those directions, but must be missing a step.

I never see the version # get to 6.1.1-0-pr-1505-0102cdc.

**Comment by AlCalzone** [comment]
With the custom build you have to set the branch name to use.
You should be able to find that in the PR header, something like "wants to merge branch xyz into master".

**Comment by ragenhe** [comment]
@AlCalzone - Sorry to be a pain.  I attempted `git checkout cc-no-response` and there isn't one in either repo.

Can you see what I should be using instead of `cc-no-responce`?  Please?

Edit:  I've been evaluating the wrong # to compare to what version # I'm after.  Sorry, I'm a noob at navigation this project, but glad I'm here.  I'm building a new, local image (again) and will let you now what the results are when I'm done testing.

Thanks for all the patience with me!

**Comment by AlCalzone** [comment]
Oh yeah things move fast here. Try the master branch 😅

**Comment by ragenhe** [comment]
@AlCalzone - I finally have an update to report.  Using the current (1/28/2021) master branch of both repos, I successfully included the ZCOMBO and with just one additional manual wake up of the device, it was detected 100% and all expected node entries were found on my MQTT broker.

Please let me know if you want to see any of the logs, or need more details.

EDIT: On the HA side I only have a battery_level sensor and a battery_low sensor, but I will continue working on it all until all sensors make it to HA.

Thanks for all the help!!
Ragen

**Comment by AlCalzone** [comment]
> EDIT: On the HA side I only have a battery_level sensor and a battery_low sensor, but I will continue working on it all until all sensors make it to HA.

Try waking it up a couple of times. Sounds like it is asleep.

**Comment by gregsheremeta** [comment]
@ragenhe I got mine to include, but like you I only see the battery sensors in HA. Did you get the actual alarm sensors working in HA?

**Comment by ragenhe** [comment]
I did.  It all works as it should with the most recent version.
