### ISSUE TITLE
feat(config): add support for Zooz Zen16

### ISSUE THREAD

**Issue by blhoward2** [zwave-js/zwave-js#1506]
**Is your feature request related to a problem? Please describe.**
Import config file

**Describe the solution you'd like**
Working device

**Comment by blhoward2** [comment]
@zwave-js-bot import config 0x027a-0xa00a-0xa000 from ozw

**Comment by blhoward2** [comment]
@AlCalzone I guess the bot doesn't listen to me outside my own PR?

**Comment by AlCalzone** [comment]
That's correct.
@zwave-js-bot import config 0x027a-0xa00a-0xa000 from ozw
