### ISSUE TITLE
A lot of "Failed to execute controller command after..."

### ISSUE THREAD

**Issue by andresn81** [zwave-js/zwave-js#1508]
**Describe the bug**

Every morning when I wake up, a motion detector right outside the bedroom detects when I'm "up" and turns on around 6-7  lights and more. This worked good in 5.7.0 but after I upgraded to 6.0.0, it takes very _long time_ to execute these commands and the log is filled with "Failed to execute controller command after [...]".

I have attached a log file that starts with when motion is detected in the morning. As we can see in the log, it takes almost 4 minutes to turn a few of the devices.

**Device information**

Which device(s) is/are affected (make/model)? Mostly Everspring and Fibaro
What are the node IDs? 51, 66, 53 are a few

**Last Known Working Configuration**
- [x] Previously working device (node-zwave-js)
    - Which library version/docker image/adapter version? 5.7.0

**Installation information**
How did you install `node-zwave-js`?
- [x] Pkg

**Logfile:**

[failed_to_execute.txt](https://github.com/zwave-js/node-zwave-js/files/5878177/failed_to_execute.txt)

**Comment by AlCalzone** [comment]
Power-cycle your Z-Wave stick. In your log, it simply doesn't react at all for a while.
