### ISSUE TITLE
"value added" / "value updated" / "value removed"  still in-use

### ISSUE THREAD

**Issue by marcus-j-davies** [zwave-js/zwave-js#1514]
Ok, Migrating the node-red plugin to 6.1.0 (which doesn't use the Value ID approach).

The docs suggest "value added" / "value updated" / "value removed" are no longer used.
but calling `Driver.controller.nodes.get(number).getEndpoint(0).commandClasses.Configuration.get(param);`

Does not trigger `value notification`, but triggers the former.
Have I mis-understood, and the former is still actively used for certain CC's?

**Comment by AlCalzone** [comment]
You misunderstood. For stateless values (Central Scene, Scene Activation CC, a compat Basic Event), they are no longer used.
They are still used for everything else.
