### ISSUE TITLE
Measure command time, time out responses accordingly

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#1518]
During a node capability discovery or interview, as well as traffic generated due to user activation, a
controlling nodes MUST timeout waiting for responses (reports) as part of the capability discovery or
controlling scenarios.
Two timers named CommandTime and ReportTime are used for timing out during a node discovery
interview. Illustrations are given for secure and non-secure cases in Figure 1 and Figure 2
* CommandTime is measured by the application
* ReportTime timeout SHOULD be set to CommandTime + 1 second.

![grafik](https://user-images.githubusercontent.com/17641229/106122076-9339ff00-6158-11eb-8b99-04b9c0a446a4.png)

**Comment by LordMike** [comment]
#985  ? :)

**Comment by AlCalzone** [comment]
Yes but this issue also affects dynaically changing timeouts in the state machine.

**Comment by LordMike** [comment]
I could sense that, but here's to hoping :)
