### ISSUE TITLE
[bug] recent changes exacerbate issue of switch turning back on in HA during transitions

### ISSUE THREAD

**Issue by blhoward2** [zwave-js/zwave-js#1519]
**Describe the bug**

Changes made in response to #452 exacerbate the switch flipping back on in HA on my setup. Coincidentally, I inadvertently started up an old image from two weeks ago that doesn't have the flipping issue at all, suggesting interim changes are the cause. Regardless, #1453 makes it worse than it was before that PR. The issue is non-existent in a build off 1.0.0-alpha.2+9f99728.9f99728.

**Device information**

This is a GE 14294, with a step of 20 and a timing of 1 (10 ms).

**Last Known Working Configuration**
- [ ] New device
- [ ] Previously working device (node-zwave-js)
    - Which library version/docker image/adapter version?
    - Have you made any recent configuration changes to the device? Describe.

- [ ] Previously working device (other platform)
    - Which platform?
    - Have you made any recent configuration changes to the device? Describe.
    
**Installation information**
How did you install `node-zwave-js`?
- [ ] `zwavejs2mqtt` (latest) docker image
- [ ] `zwavejs2mqtt` (dev) docker image
- [ ] ioBroker.zwave2 adapter
- [ ] Pkg
- [X ] Manual Docker build
    - `node-zwave-js` branch: master
    - `zwavejs2mqtt` branch: master
- [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github)) 
- [ ] Other: 

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Additional context**

**Logfile:**

**Comment by towerhand** [comment]
I'm planning to test the PR in a little while and will report back.

Edit: it works great, as expected.
