### ISSUE TITLE
Discard scheduled polls if an unsolicited update comes

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#1532]
Once #1522 is merged, we have auto-scheduled polls after setting a value through the SET_VALUE API to verify that devices changed their value. We should discard these if an update comes in the meantime to avoid unnecessary polling.

**Comment by LordMike** [comment]
Something like an integer (version) on each value, that increments on `REPORT`'s, that you copy to a GET message.. When sending, check if the version on the GET matches the version on the value in the Db - if not, there was a Report in the meantime..
