### ISSUE TITLE
feat(config): add support for Zooz Zen30

### ISSUE THREAD

**Issue by bs42** [zwave-js/zwave-js#1533]
Please add support for this device.

Device ID: 634-40968-40960 (0x027a-0xa008-0xa000)

**Comment by AlCalzone** [comment]
@blhoward2 is that on your list?

**Comment by blhoward2** [comment]
Yes, it should be in the pile after the pile I'm currently working on.

**Comment by aneisch** [comment]
I just requested #1590 for this.
