### ISSUE TITLE
#1522 but for multicasts

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#1550]
Multicast SETs don't poll (because that would require one GET for each node, defeating the purpose of a multicast). But we should assume that the command was accepted by all nodes if it succeeds like we already do for singlecasts.

_Originally posted by @AlCalzone in https://github.com/zwave-js/zwavejs2mqtt/issues/25#issuecomment-770733578_

**Comment by blhoward2** [comment]
@AlCalzone bumping this since multicast is now in zwaveje2mqtt. More people are beginning to use it via mqtt according to discord.
