### ISSUE TITLE
[bug] SWITCH_MULTILEVEL SET missing on Philio PSE02 Siren

### ISSUE THREAD

**Issue by Gis70** [zwave-js/zwave-js#1553]
### Version

Build/Run method

- [X ] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.1
zwavejs version: 6.1.0

### Describe the bug

Hi, i'm new on Zwave-js2MQTT, i'm come from Jeedom where they have their proper zwave adaptation based on OZW 1.4.

My issue is that's i can't find SWITCH_MULTILEVEL SET for my Philio PSE02 Siren.

So i'm not able to change type of sound as in the manual :

![image](https://user-images.githubusercontent.com/16589132/106451278-9d286e80-6486-11eb-95e4-e7523594ad45.png)

### To Reproduce

![image](https://user-images.githubusercontent.com/16589132/106451346-b7fae300-6486-11eb-9432-5154c8f4578b.png)

### Expected behavior

Have a menu where I can send the sound ID

I can try to modify directly a config file with your help. I opened the json file of this device and compared it with a device which have SWITCH_MULTILEVEL but it seems it's not in this file.

Thanks a lot for your help.

**Comment by Gis70** [comment]
@robertsLando  As i said previously in my edited message, logs are in silly mode and it's the Node 2, the node 13 is shutter, and at the moment it's OK. (begin my merge of all zwave devices)

Do i launch a re interview ?

from my understanding it seems ok for this node
```
13:20:00.941 CNTRLR   [Node 002] The node is alive.
13:20:01.068 CNTRLR   [Node 002] The node is ready to be used
13:20:01.068 CNTRLR « [Node 002] ping successful
13:20:01.133 SERIAL « [ACK]                                                                   (0x06)
13:20:01.134 SERIAL « 0x0104011301e8                                                       (6 bytes)
13:20:01.135 SERIAL » [ACK]                                                                   (0x06)
13:20:01.146 DRIVER « [RES] [SendData]
                        was sent: true
13:20:01.149 CNTRLR   **[Node 002] ManufacturerSpecificCC: doing a partial interview...**
13:20:01.150 CNTRLR   **[Node 002] [~] [Manufacturer Specific] interviewComple [Endpoint 0] [internal]**
                      te: true => true
13:20:01.150 CNTRLR   [Node 002] trying to load device config
13:20:01.150 CNTRLR   [Node 002] no device config loaded
13:20:01.151 CNTRLR   [Node 002] VersionCC: doing a partial interview...
13:20:01.151 CNTRLR   [Node 002] [~] [Version] interviewComplete: true => tr [Endpoint 0] [internal]
                      ue
13:20:01.151 CNTRLR   [Node 002] trying to load device config
13:20:01.153 SERIAL « 0x0107001302000007ee                                                 (9 bytes)
13:20:01.153 SERIAL » [ACK]                                                                   (0x06)
13:20:01.154 DRIVER « [REQ] [SendData]
                        callback id:     2
                        transmit status: OK
```

**Comment by AlCalzone** [comment]
Yes, please re-interview that device and post the logfile and the `<homeid>.json` cache file here.

**Comment by Gis70** [comment]
@AlCalzone @robertsLando this is my lasts logs just after a interview :   
`14:43:35.520 CNTRLR   [Node 002] Beginning interview - last completed stage: None`

[zwavejs_1.log](https://github.com/zwave-js/node-zwave-js/files/5904601/zwavejs_1.log)

[zwavejs2mqtt.log](https://github.com/zwave-js/node-zwave-js/files/5904603/zwavejs2mqtt.log)
[e5248c75.json.log](https://github.com/zwave-js/node-zwave-js/files/5904605/e5248c75.json.log)

Is it the right json file ?

**Comment by AlCalzone** [comment]
```
14:43:36.207 CNTRLR « [Node 002] node info received
                      supported CCs:
                      · Z-Wave Plus Info
                      · Manufacturer Specific
                      · Version
                      · Association Group Information
                      · Powerlevel
                      · Device Reset Locally
                      · Security
                      · Firmware Update Meta Data
```
Doesn't look like it supports Multilevel Switch CC. Which manual do you have?
In [this one](https://www.homecontrols.com/homecontrols/products/pdfs/EZ-Ezlo/EZPHLPSE02US-User-Manual.pdf) there is no mention of that command.

**Comment by AlCalzone** [comment]
zwave-js has an api to send arbitrary commands, I think @robertsLando recently exposed it.
That is preferred here since the notification is not a simple primitive value.
The documentation is lacking though since I will need to automatically generate it.

**Comment by Gis70** [comment]
Ok, if @robertsLando can explain to me how to send such commands. At the end it will be sent from MQTT to zwave-js2mqtt

Thx for your help.

**Comment by AlCalzone** [comment]
So, basically you need to call the `sendReport` method for the `Notification` CC with this argument
```jsonc
{
  notificationType: 0x01, // or 0x06 or 0x07 or 0x0A
  notificationEvent: /* see table */,
}
```
I don't know the exact MQTT command for that.

**Comment by robertsLando** [comment]
@Gis70 https://zwave-js.github.io/zwavejs2mqtt/#/guide/mqtt?id=send-command

**Comment by Gis70** [comment]
Thx guys, you should told me, Read The Fucking Manual ;-)

**Comment by AlCalzone** [comment]
I can't since my part is not documented yet 😅

**Comment by Gis70** [comment]
Hello @robertsLando and @AlCalzone i'm trying to do what it's explained there https://zwave-js.github.io/zwavejs2mqtt/#/guide/mqtt?id=send-command but i'm not doing well.

My topic Name is `zwave`
`Controleur` is my `"yourname"`
What is `_CLIENT`

Does it look like to that :    (i'm trying simple example to getNodes)

`zwave/_CLIENTS/ZWAVE_GATEWAY-Controleur/api/getNodes()`

**Comment by robertsLando** [comment]
`zwave/_CLIENTS/ZWAVE_GATEWAY-Controleur/api/getNodes/set`

**Comment by Gis70** [comment]
Ok it's working for getNodes but it's this name :
![image](https://user-images.githubusercontent.com/16589132/106935456-a7af6600-671b-11eb-9fac-a81782518e2d.png)

But i'm not able to send my command : 

I would send on the nodeId 2 :  
![image](https://user-images.githubusercontent.com/16589132/106935574-cdd50600-671b-11eb-84e3-36cf2c23c7e0.png)

![image](https://user-images.githubusercontent.com/16589132/106935653-e8a77a80-671b-11eb-8767-882c34663be1.png)

For example I want the door chime :  can you help be to send the right syntax

`zwave/_CLIENTS/ZWAVE_GATEWAY-zwavejs2mqtt/api/sendCommand/set`

Value :  `{"args":[{"nodeId":2,"commandClass":113,"endpoint": 3,},"startLevelChange",[{6}]]}`

Debug :   

![image](https://user-images.githubusercontent.com/16589132/106935962-476cf400-671c-11eb-8881-8b495f425b5d.png)


One thing for the non coder like me should be to make a special page where we can add device compatible and what command to make, a little like for zigbee2mqtt :  https://www.zigbee2mqtt.io/information/supported_devices.html  what do you think ? 
@robertsLando

**Comment by robertsLando** [comment]
What is `[{6}]`?? That's not a valid json


> One thing for the non coder like me should be to make a special page where we can add device compatible and what command to make, a little like for zigbee2mqtt : https://www.zigbee2mqtt.io/information/supported_devices.html what do you think ?

It's on todos

**Comment by Gis70** [comment]
Hi @robertsLando @AlCalzone , I need you again, i found on google that we have to modify 1st a parameter here : put in to 128
![image](https://user-images.githubusercontent.com/16589132/108390024-86b53d80-7210-11eb-84e4-f367943babc2.png)

So OK with GUI for this.

Then i found we must using BASIC_SET to select sound :  

![image](https://user-images.githubusercontent.com/16589132/108390412-f0cde280-7210-11eb-8a1b-d6e8aa7e4133.png)

How to send BASIC_SET via API or GUI in feature ?

**Comment by robertsLando** [comment]
You can using mqtt apis and the `sendCommand` api: https://zwave-js.github.io/zwavejs2mqtt/#/guide/mqtt?id=send-command

**Comment by Gis70** [comment]
You already told me the manual @robertsLando but i'm not able to pass the right argument. I want BASIC_SET so i guess it's the basicCC command class : (or i'm wrong?)
![image](https://user-images.githubusercontent.com/16589132/108708625-f88fce80-7511-11eb-9e5e-57c5fdc06d53.png)

But i don't know at all how and which argument i have to use.

Can you help me please ? If it can help and motivate you I will give you some coffees... :-)
