### ISSUE TITLE
Duplicated values on Meter CC

### ISSUE THREAD

**Issue by marcelveldt** [zwave-js/zwave-js#1575]
**Describe the bug**

As discussed a bit on discord, I've noticed the consumed/kWh sensor being duplicated on my dimmers (Fibaro Dimmer 2).
Don't know if this happens to others as well but for completeness sake I report it here.
It's no big deal, it's just a bit confusing to have two sensors that are much a like but not 100% (one is a bit behind).

**Device information**

Which device(s) is/are affected (make/model)?  Fibaro Dimmer 2
What are the node IDs?

**Last Known Working Configuration**
- [ ] New device
- [ ] Previously working device (node-zwave-js)
    - Which library version/docker image/adapter version?
    - Have you made any recent configuration changes to the device? Describe.

- [ ] Previously working device (other platform)
    - Which platform?
    - Have you made any recent configuration changes to the device? Describe.
    

[state_dump_fibaro_dimmer.txt](https://github.com/zwave-js/node-zwave-js/files/5921031/state_dump_fibaro_dimmer.txt)

**Comment by AlCalzone** [comment]
This might be fixed by the endpoint changes in v8.x. Please verify and re-open if necessary.
