### ISSUE TITLE
Add support for HKZW-DWS01 Door/Window Sensor

### ISSUE THREAD

**Issue by EvasionOfTruth** [zwave-js/zwave-js#1595]
Please add support for Hank door/window sensors.
`<Manufacturer id="208" name="HANK Electronics Ltd"><Product type="201" id="8" name="HKZW-DWS01 Door/Window Sensor" />`
http://manuals-backend.z-wave.info/make.php?lang=en&sku=HKZW-DWS01&cert=ZC10-16085158

**Comment by decairn** [comment]
They're supported already, and recognized in my network.  https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/devices/0x0208/dws01.json
