### ISSUE TITLE
Support for TechniSat switch 0x0299-0x1a90-0x0002

### ISSUE THREAD

**Issue by Helidude** [zwave-js/zwave-js#1597]
Missing support for TechniSat on/off switch 0x0299-0x1a90-0x0002
[https://www.technisat.com/en_XX/On-Off-switch-flush-mount,-BJ/352-22702-22935/](url)

Best regards
Ivar

**Comment by blhoward2** [comment]
In progress, see #1600

**Comment by AlCalzone** [comment]
@blhoward2 #1603 is a pretty decent starting point
