### ISSUE TITLE
Store timestamp along with the value

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#1608]
as requested in https://github.com/zwave-js/zwavejs2mqtt/issues/391

**Comment by chrish987** [comment]
any potential timeline on this feature?

**Comment by AlCalzone** [comment]
Tbh, there are more pressing issues on my end and the changes will be pretty invasive since the value storage is a core part of the library and used **everywhere**.

**Comment by chrish987** [comment]
does that mean it is unlikely to be ever implemented? or weeks or months away?

**Comment by AlCalzone** [comment]
I do see some value in this (e.g. auto-idling notifications across a restart could benefit). But looking at my issue pile, it is rather months away.

**Comment by raintonr** [comment]
I had a few moments so took a quick look at the code today. @AlCalzone, how would you like to see this implemented as with anything there are many options?

From what I can tell there is a DB of key/value pairs that store metadata, values, etc. in an underlying `JsonlDB` database.

If we are just interested in timestamps of values then one could modify the `setValue` method (in `ValueDB.ts`) to have the value stored in the underlying DB to itself be a combination of timestamp+value. Then in `getValue` extract those parts out and only return the value part. Then one would need a `getTimestamp` method to do the same and only return the timestamp (or have a method that returns both in a single object for those callers who are aware of this functionality).

Would that work for you? Bit messy so I'm guessing you had something more elegant in mind :clown_face:

**Comment by AlCalzone** [comment]
@raintonr I'd probably do it in the ValueDB, but I haven't thought it through completely. This will also need to consider edge cases like updates that don't actually come from the device.

In any case, a PR for this likely won't land before 2023 -> https://github.com/zwave-js/node-zwave-js/issues/5129
