### ISSUE TITLE
Add compat flag to override values reported by a device

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#1625]
To work around this device firmware (!) issue on the zwave-js side, we need to add a compat flag that allows us to override specific values and avoid querying them from the device (because in this case the supported colors response is simply wrong).

__Originally posted by @AlCalzone in https://github.com/zwave-js/zwavejs2mqtt/issues/477#issuecomment-774475891__

**Comment by scyto** [comment]
Is this fix required per device definition file or somewhere else?
Is this just new integration specific or would apply to the MQTT hass discovery code path?

**Comment by AlCalzone** [comment]
This needs to be done in the device config files where necessary to fix wrong device-specific capability reports.

In the mentioned issue, the device does not report that it supports the blue color channel, based on which the channel is not queried by zwave-js and RGB (hex) support is assumed to be false.

**Comment by scyto** [comment]
thanks, could this be the root cause on the fibaro rgbw v1?  
https://github.com/Z-Wave-Me/z-way-issues/issues/163#issuecomment-774340754 

this person has indicate the device has a pretty bad bug on reporting channels....

I can take point on the fibaro rgbw file if someone tells me what to add (folks seem to mentioning difference devices so i assume we will need to edit multiple device files)

**Comment by AlCalzone** [comment]
That looks different

**Comment by joselito11** [comment]
Will be some update on version 7 for this rgb bug?

**Comment by AlCalzone** [comment]
Sorry, that would require a larger rework of the interview process where I'd have to touch every CC implementation in several locations.

**Comment by joselito11** [comment]
So on HA core-2021.4.0b0 and with zwaveJS addon 0.1.15 the light has color wheel, must click few times to get the color, but it works! Thanks!
![Zaslonska slika 2021-04-01 12-01-39](https://user-images.githubusercontent.com/53316474/113278677-81084880-92e2-11eb-9b9e-4570ffef6f04.png)
![Zaslonska slika 2021-04-01 12-01-53](https://user-images.githubusercontent.com/53316474/113278695-84033900-92e2-11eb-92ad-2d1a07796df4.png)

**Comment by AlCalzone** [comment]
I didn't do anything here 😳

**Comment by joselito11** [comment]
Color picker is gone again, any idea how to get it back? Have deleted zwavejs integration, reinstalled addon
