### ISSUE TITLE
feat(config): add support for Zooz ZEN22 Dimmer

### ISSUE THREAD

**Issue by Sudo-Rob** [zwave-js/zwave-js#1628]
**Which device is missing?**

Zoos ZEN22 Dimmer V2, Ver. 3.0 or later

**What are the IDs?**

Manufacturer ID: 0x015D
Product type: 0x0112
Product ID: 0x241C, 0xb112:0x1f1c

**Did you check if we really don't have it?**

- [ ] It is not in the [configuration DB](https://devices.zwave-js.io/)
- [x] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)
- [x] It is not in the [TODO list](https://github.com/zwave-js/node-zwave-js/issues/1600)

**Do you have a link to the PDF manual?**

https://products.z-wavealliance.org/ProductManual/File?folder=&filename=MarketCertificationFiles/1946/zooz-z-wave-plus-dimmer-switch-zen22-manual.pdf

https://cdn.shopify.com/s/files/1/0218/7704/files/zooz-zen22-VER4.0-manual.pdf?v=1601861689

Other relevant links:

https://www.support.getzooz.com/kb/article/297-zen22-dimmer-change-log/
https://products.z-wavealliance.org/products/1946?selectedFrequencyId=-1
https://www.support.getzooz.com/kb/section/5/
https://www.home-assistant.io/docs/z-wave/device-specific/

**Comment by AlCalzone** [comment]
This one?
https://devices.zwave-js.io/?selectedPath=0x027a:0x1f1c:0xb112:20.15

**Comment by Sudo-Rob** [comment]
Good question.

When I look at the entity attributes, it says "friendly_name: Zooz ZEN22 Dimmer V2", "application_version: 4.01."

My current integration shows 22 Node Configuration Options:
1: Paddle Control 
2: LED Indication Control
3: Enable Auto Turn-Off Timer
4: Auto Turn-Off Timer Duration
5: Enable Auto Turn-On Timer
6: Auto Turn-On Timer Duration
7: Association Reports
8: On Off Status After Power Failure
9: Ramp Rate Control
10: Minimum Brightness
11: Maximum Brightness
12: Double Tap Function
13: Enable/Disable Scene Control
14: Enable/Disable Double-tap
15: Smart Bulb Mode: Enable/Disable Paddle / Z-Wave Control
16: Physical Dimming Speed
17: Zwave Ramp Rate Control
18: Custom Brightness Level On
19: 3-Way Switch Type
20: Zwave tap and hold Control
21: Reporting behavior with disabled physical control
22: Night Light Mode 

The above list is accommodated with Version 3 firmware support in the original OZW integration as modified by the device-specific manual edits to the xml file (https://www.home-assistant.io/docs/z-wave/device-specific/).  There are a couple of additions for V 4 firmware.  These appear in the Change Log.  https://www.support.getzooz.com/kb/article/297-zen22-dimmer-change-log/

Edit:  All recent parameters are defined here:  https://www.support.getzooz.com/kb/article/319-zen22-dimmer-switch-ver-4-01-advanced-settings/

Is there any other info you might need?  I can perhaps do some legwork for you.

**Comment by Sudo-Rob** [comment]
I edited https://devices.zwave-js.io/?selectedPath=0x027a:0x1f1c:0xb112:20.15# to include 13-22 based on the XML file.

https://github.com/Sudo-Rob/Zooz-ZEN22V4.1/tree/main

Please check to see if it conforms to the JSON conventions.  If there's a way to include Help text for each index, let me know so I can add it.

**Comment by AlCalzone** [comment]
@blhoward2 something for the task force 😊

**Comment by Sudo-Rob** [comment]
Don't take action just yet.  The file I started with, `zen22_3.0-19.0.json`, was missing index #7.  When it's added, I'll report here.

**Comment by Sudo-Rob** [comment]
I've updated the file, but might've overachieved.  `Index #7` is pretty arcane.  Looking at the firmware change log, my guess is the configuration will work on V3 and above.  

Here's `Index #7` for the Configuration Parameters chart.

[Index_#7.xlsx](https://github.com/zwave-js/node-zwave-js/files/5939777/Index_.7.xlsx)

**Comment by AlCalzone** [comment]
That parameter looks like what I reviewed here:
https://github.com/zwave-js/node-zwave-js/pull/1635#pullrequestreview-585003590

**Comment by Sudo-Rob** [comment]
Looks like it.  I would expect a bunch of similarity between similar products by the same manufacturer.  Zooz products are made by Willis Electric Co.,LTD.

How are you mapping XLS to JSON?  Do you have an automated tool for that?

**Comment by blhoward2** [comment]
We don't use XLS. We get a json of the device entry from the zwave alliance and use that. In a case like this where we need to split them into partial parameters it is largely a manually process. Where did you get an XLS?

**Comment by Sudo-Rob** [comment]
Oops.  I meant XML.

**Comment by blhoward2** [comment]
Ah, you can download the xmls in json format through a hidden link so we do that. We have an automated script for all of the non-partial parameter pieces which is a work in progress. We are still working through batches of different things updating our files to match.

**Comment by Sudo-Rob** [comment]
Does the manufacturer provide them, or is it the Z-Wave Alliance?

**Comment by blhoward2** [comment]
The manufacturer provides them to the zwave alliance as part of the certification process. Not all devices are certified, though. And they pay varying degrees of attention while doing so.

**Comment by Sudo-Rob** [comment]
I think I understand.  The XML files look like they have a richer set of entities.  Have you compared the two?

**Comment by blhoward2** [comment]
The json we download are the same info in the individual xml, just in json format. We then process them into our format and clean them up. We don't retain everything they provide as we don't need it.

**Comment by Sudo-Rob** [comment]
I think there's value in the help information.  I hope it's in the roadmap.

Let me know what I might be able do to advance this feature request.

**Comment by blhoward2** [comment]
We've added the inclusion, exclusion, and reset info. And a link to the manual. These are used on the website being developed. We can run back through them and load anything we want fairly automatically but there isn't a plan to use the other info at this point.

If the metadata fields aren't yet in this file and the device exists in the database it means we haven't gotten to it yet. That's why we have the todo list so we don't have conflicts. #1600

It looks like this one is on there under Willis, so we'll have to merge them.

**Comment by Sudo-Rob** [comment]
Understand.  I still need to see if any of my other devices are in #1600. 

Just let me know if there's anything else I might be able to do for you.  I'm looking forward to a more capable integration, but OZW is working for me right now.  I had problems getting JS to work.

**Comment by Sudo-Rob** [comment]
Is status "waiting for more info" still accurate?

**Comment by blhoward2** [comment]
He's waiting for me to make the partial parameters for 7, so you can add them to yours.

**Comment by Sudo-Rob** [comment]
Sounds good.  I wasn't sure if I had any pending action.  Do you know I've already filled in #7 on my latest version?
