### ISSUE TITLE
Distinguish between legacy device classes and Z-Wave+ device types

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#1655]

**Comment by blhoward2** [comment]
For what purpose? We just removed the supportsZwavePlus field in the files. Do I need to re-add it? Parse the zwa files and populated it?

**Comment by AlCalzone** [comment]
Nah that is none of your concern. This info is available through zwave itself.

**Comment by robertsLando** [comment]
`isZwavePlus` node property?

**Comment by AlCalzone** [comment]
This issue is about the Z-Wave Plus **Device Types** that are defined in the specification
