### ISSUE TITLE
No Up/stop/Down buttons in HA

### ISSUE THREAD

**Issue by labaland** [zwave-js/zwave-js#1658]
I have this to control my blinds.

**Which device is missing?**
Qubino  Flush Shutter DC - ZMNHOD

**What are the IDs?**
??

**Do you have a link to the PDF manual?**
[https://support.qubino.com/support/solutions/articles/44001757258-qubino-flush-shutter-dc](url)

**Comment by AlCalzone** [comment]
1. Please take a second and read the information we put under the different issue templates
![grafik](https://user-images.githubusercontent.com/17641229/107242564-67f2c200-6a2c-11eb-9f97-273f3bb869e8.png)
They are there for a reason.

2. If something is not working in HA, start by opening an issue in the HA repo.

**Comment by marcus-j-davies** [comment]
@AlCalzone  - You beat me to it,

This already exists : https://devices.zwave-js.io/?selectedPath=0x0159:0x0053:0x0003:0.0.

So shouldn't belong here.
