### ISSUE TITLE
Add bin firmware format. 

### ISSUE THREAD

**Issue by DelusionalAI** [zwave-js/zwave-js#1661]
**Describe the bug**

When trying to update the firmware or my inovelli switch, I get an error when trying go update target one. It says it is unable to detect firmware format. 

    
**Installation information**
How did you install `node-zwave-js`?
- [ X] `zwavejs2mqtt` (latest) docker image
- [ ] `zwavejs2mqtt` (dev) docker image
- [ ] ioBroker.zwave2 adapter
- [ ] Pkg
- [ ] Manual Docker build
    - `node-zwave-js` branch: 
    - `zwavejs2mqtt` branch: 
- [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github)) 
- [ ] Other: 

The firmware in question can be found below. 
https://support.inovelli.com/portal/en/kb/articles/firmware-change-log-lzw31-sn-dimmer-switch-red-series

**Comment by AlCalzone** [comment]
@robertsLando these bin files are for firmware target 1 (i.e. not the z-wave chip) - do you have a way of selecting that?

**Comment by AlCalzone** [comment]
#1703 fixes this. Note that you need to select the firmware target 1 when updating the .bin files. Not sure if that is possible yet.

**Comment by DelusionalAI** [comment]
Yes you can do that now with https://github.com/zwave-js/zwavejs2mqtt/pull/501 on zwavejs2mqtt.
