### ISSUE TITLE
Feature Request: Add method to update Driver logConfig

### ISSUE THREAD

**Issue by raman325** [zwave-js/zwave-js#1698]
**Is your feature request related to a problem? Please describe.**
As far as I can tell, the only way to change the log level is to restart the driver which triggers a re-interview of all nodes. It appears that many Home Assistant users are changing log levels often to help troubleshoot integration issues or device specific issues. It would be great if we could update the log level without restarting the driver so we didn't have to trigger a re-interview

**Describe the solution you'd like**
Add a method to the `Driver` class that can update the `logConfig`, particularly `level`,  while the Driver is running and without having to destroy and recreate it.

**Describe alternatives you've considered**
None at this time

**Additional context**
Add any other context or screenshots about the feature request here. If you want to propose an API, share your thoughts how it could be used (syntax).

**Comment by AlCalzone** [comment]
Damn, I think we had that and it got lost. @robertsLando?

**Comment by AlCalzone** [comment]
The log container has this: https://github.com/zwave-js/node-zwave-js/blob/6cc6466e2ce050b95364b1740cc6d123af3cdba1/packages/core/src/log/shared.ts#L129

**Comment by raman325** [comment]
hmm OK, I think this solves the problem then. I believe we'd just need to call `driver.logContainer.updateConfiguration` then? Seems like something we can expose in the server and then provide a Home Assistant service to call it

**Comment by AlCalzone** [comment]
I think we need a method on the driver to update the config for all loggers

**Comment by robertsLando** [comment]
> I think we need a method on the driver to update the config for all loggers

Yep absolutely, now I don't remember how it works but I thought it worked in that way, doesn't it?

**Comment by AlCalzone** [comment]
We had that at the start but seem to have removed it when refactoring to log containers and logger instances
