### ISSUE TITLE
Linear/Nortek wt00Z-1 needs "treatBasicSetAsEvent": true

### ISSUE THREAD

**Issue by charettepa** [zwave-js/zwave-js#1708]
**Describe the bug**

A clear and concise description of what the bug is. Describe what causes the bug, what you observe, and what happens as a result.

The wt00z-1 sends a CC32 event on button press
this is not processed by zwavejs unless the device is re-interviewed 2x after reboot while pressing a button on the scene controller. at that time it reports a value of 0 for off and 255 for on when button is pressed but only in MQTT platform and loses the ability after reboot unless re-interviewed again 2x while pressing button.  having the "treatBasicSetAsEvent": true set corrects this issue as you can just monitor for zwavejs events.

updated device file in docker to have 
,
	"compat": {
		"treatBasicSetAsEvent": true
	}

device can now be monitored for zwave js event

request is to change device file to include "treatBasicSetAsEvent": true
if not resolve detecting of CC32 without having to re-interview 2x while pressing button on reboot

**Device information**

Which device(s) is/are affected (make/model)?    WT00Z-1
What are the node IDs? 

**Last Known Working Configuration**
- [x ] New device
- [ ] Previously working device (node-zwave-js)
    - Which library version/docker image/adapter version?
    - Have you made any recent configuration changes to the device? Describe.

- [ ] Previously working device (other platform)
    - Which platform?
    - Have you made any recent configuration changes to the device? Describe.
    
**Installation information**
How did you install `node-zwave-js`?
- [x ] `zwavejs2mqtt` (latest) docker image
- [ ] `zwavejs2mqtt` (dev) docker image
- [ ] ioBroker.zwave2 adapter
- [ ] Pkg
- [ ] Manual Docker build
    - `node-zwave-js` branch: 
    - `zwavejs2mqtt` branch: 
- [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github)) 
- [ ] Other: 

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Additional context**

**Logfile:**

**Comment by blhoward2** [comment]
This is a non-zwave plus scene controller without central scene support. I’ll PR the change.
