### ISSUE TITLE
First Alert Zwave Combo - Two version, one works fine other only shows battery level

### ISSUE THREAD

**Issue by kannszzz** [zwave-js/zwave-js#1722]
**Describe the bug**

I have two version of First Alert Zwave combo Smoke and CO alarm system. 
-Version 2 works perfectly fine and shows multiple entities for smoke and CO along with other entities.
-Version 1 only shows two entites and both are battery related

V2 Details  
-https://www.amazon.com/gp/product/B00KMHXFAI
-Node 13
-Json File Attached 

V1 Details
-https://www.amazon.com/gp/product/B08FFB233Y
-Node 15
-Json Attached

**Device information**

Which device(s) is/are affected (make/model)?  
What are the node IDs?
Node 15 - V1 have issue with not showing CO and Smoke alarm. Only shows battery entites
Node 13 - V2 shows both along with other entities

**Last Known Working Configuration**
- Was using with smartthings and both worked. Excluded and added to zwavejs2mqtt and Homeassistant
- [ ] Previously working device (node-zwave-js)
    -V1 never showed alarm just battery
    -V2 shows all alarms
    -ZwaveJS Version 6.1.3 
    -HA Version :2021.2.2
- [ ] Previously working device (other platform)
    - Smartthings
    - Excluded both from smartthings and added to zwavejs
    
**Installation information**
How did you install `node-zwave-js`?
- [ X] `zwavejs2mqtt` (latest) docker image

**To Reproduce**
1. Go to Homeassistant
2. Entites you can see both Smoke/CO sensors
3. But for V1 only batterty entties shows whereas V2 all entities shows including CO/Smoke alarm

**Logfile:**
[zwavejs.log](https://github.com/zwave-js/node-zwave-js/files/5969234/zwavejs.log)
[FirstAlert_v1.txt](https://github.com/zwave-js/node-zwave-js/files/5969189/FirstAlert_v1.txt)
[FirstAlert_v2.txt](https://github.com/zwave-js/node-zwave-js/files/5969191/FirstAlert_v2.txt)

**Comment by blhoward2** [comment]
It's seeing the notification command class in the v1 detector. We need to determine if this is on our end, or in the device creation in HA.

1. When you say you are only seeing battery entities, where is that? In HA? 
2. Are you using the zwave-js server or mqtt discovery through zwavejs2mqtt? 
3. Can you use something like MQTT Explorer to see if the endpoints are created on that node in mqtt (assuming you are using mqtt)? And whether they change when you test the detector?
4. Please send a log showing the detector during a test of the detector.

**Comment by kannszzz** [comment]
1. In Home Assistant
2. ZwaveJS2mqtt
3. Ok will try enabling MQTT and see waht happens. WIll update once I have something.
4. This is what I see in debug log when I manually triggered the Alarm
Debug
2021-02-11 23:04:29.818 INFO ZWAVE: Node 15: value updated: 113-0-alarmType 13 => 12
2021-02-11 23:04:29.821 INFO ZWAVE: Node 15: value updated: 113-0-alarmLevel 255 => 255

**Comment by blhoward2** [comment]
I'm not sure that you need to enable mqtt based on the log. It looks like we're setting that device up correctly, but the zwave-js integration isn't creating an entity for it. They'd have to fix that.

**Comment by kannszzz** [comment]
There were few entities disabled by default at start enabled them and this is what I see.
![image](https://user-images.githubusercontent.com/23491305/107732744-1c0f7980-6cc7-11eb-94eb-46191fa349e1.png)


Compared to V2, which also have quite a few disabled entities.
![image](https://user-images.githubusercontent.com/23491305/107732793-42351980-6cc7-11eb-9899-461da643cdbe.png)

**Comment by blhoward2** [comment]
That looks correct. The 255 is the alarm value. The 12/13 is whether it's a real alarm or test if memory serves. If you search in the HA Community website many people setup a binary sensor of their own for these. The new version supports many more values. 

On our end we create a binary sensor automatically in zwave2jsmqtt for mqtt discovery, but I'm not sure the integration intends to do that. Either way it's working right on our end.

**Comment by kannszzz** [comment]
Thanks for the information, I believe FirstAlert did not implement the binary sensor at hardware level or something which probably was fixed in V2. For those facing same issue, they can create a binary sensor or automation based on the following two entities which are by default disabled when you add the device for some reason but you can enable it from settings in Home Assistant

sensor.living_room_fire_alarmtype  - Alarm Type 
sensor.living_room_fire_alarmlevel - Alarm Level

Alarm-Type         Alarm-Level               Alarm
13                             255                   Default State
12                             0                       Smoke Test
1                               255                   Smoke Alarm
2                               255                   CO Alarm
