### ISSUE TITLE
Inovelli LZW36 (Red Series Fan + Light) is missing meter settings for electric consumption

### ISSUE THREAD

**Issue by carldanley** [zwave-js/zwave-js#1744]
**Describe the bug**

Inovelli LZW36 is missing meter settings. It is supposed to have an `Electric Consumed [W]` and `Electric Consumed [kWh]` just like the Inovelli LZW31-SN  and the Inovelli LZW30-SN.

@blhoward2 requested additional clarity [in discord](https://discord.com/channels/330944238910963714/332357267364249621/810037005073252392) so, **UPDATE**:

I switched out my openzwave configuration to run zwavejs2mqtt. I did not perform any firmware updates between this process; even kept the Zooz S2 stick plugged in to same machine. On ozw, I had a sensor for this device that read the `kWh` from the device (`sensor.kids_room_main_switch_electric_kwh`). After migrating to zwavejs2mqtt, the sensor that read the `kWh` no longer exists; there are not any sensors that represent `kwh` whatsoever for the device -- in zwavejs2mqtt control panel or in home assistant.

> Can you post the json from the node form zwave2jsmqtt?

Link to device export: [node_80.zip](https://github.com/zwave-js/node-zwave-js/files/5975256/node_80.zip)

> Do you see updates from those endpoints in the log?

With debug logging enabled, `docker logs -f zwavejs2mqtt` shows no updates being sent to/from the device when the power demands change on the switch (ie - fan being turned on, light being turned on). On ozw, it did change.

**Device information**

Which device(s) is/are affected (make/model)? `Inovelli LZW36`
What are the node IDs? `Device ID: 798-1-14 (0x031e-0x0001-0x000e)` [Link](https://github.com/zwave-js/node-zwave-js/blob/c695ee81cb2b1d3cf15e3db1cc14b1e41a911cc0/packages/config/config/devices/0x031e/lzw36.json)

**Last Known Working Configuration**
- [x] Previously working device (other platform)
    - Which platform? `openzwave + homeassistant`
    - Have you made any recent configuration changes to the device? Describe. `I have not.`
    
**Installation information**
How did you install `node-zwave-js`?
- [x] `zwavejs2mqtt` (latest) docker image - specifically, [SHA digest: c482b2b83757870a4f937048db2f663cc8734b76eabc1860021338a3b834233d](https://hub.docker.com/layers/zwavejs/zwavejs2mqtt/latest/images/sha256-c482b2b83757870a4f937048db2f663cc8734b76eabc1860021338a3b834233d?context=explore). I believe this is the `1.1.1` release (as the digests match).

**To Reproduce**
Brand new install of homeassistant; completely empty. Added zwavejs2mqtt (using websockets). I just let zwave do it's thing ;)

**Comment by AlCalzone** [comment]
Please make a zwave-js log, loglevel `debug` and attach it here as a file.
Please also post the cache files `<homeid>.json` and `.values.jsonl`.

**Comment by AlCalzone** [comment]
Also, please update to `6.3.0` and re-interview your device - this might be related to https://github.com/zwave-js/node-zwave-js/pull/1749

**Comment by BluGeni** [comment]
I dont know if it is related but if I add an inovelli switch from zwavejs2mqtt I dont get kW but I do get kWh. If I add the switch from HA through the zwavejs integration, I do get kW and kWh.

**Comment by AlCalzone** [comment]
Might be a coincidence. If the node does not respond to the one query for some reason it could be that the value doesn't exist yet when zjs2m or HA create the entities.
I don't know how dynamically they react to new values that come in later.
