### ISSUE TITLE
Nortek Security & Control LLC Garage Door Controller	GD00Z-7

### ISSUE THREAD

**Issue by trentjw** [zwave-js/zwave-js#1747]
**Which device is missing?**

Nortek Security & Control LLC Garage Door Controller	GD00Z-7 
it shows up as a sensor only, does not show up as a controller to operate the door network key is working as my kwikset locks are working as intended

**What are the IDs?**

Manufacturer ID: 0x14f
Product type: 0x4744
Product ID: 0x3531

**Did you check if we really don't have it?**

- [ ] It is not in the [configuration DB](https://devices.zwave-js.io/)
- [ ] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)
- [ ] It is not in the [TODO list](https://github.com/zwave-js/node-zwave-js/issues/1600)

**Do you have a link to the PDF manual?**
XML file

If so, it helps in creating the config file.
it shows up as a sensor only, does not show up as a controller to operate the door network key is working as my kwikset locks are working as intended

**Comment by AlCalzone** [comment]
The checkboxes are meant for you to check **before** opening an issue. We have a config file for that device:
![grafik](https://user-images.githubusercontent.com/17641229/107872188-a9f68a80-6ea8-11eb-8f3b-f9e1bbe6891b.png)

If something is not working, we have a separate issue template where we require different information from you.
