### ISSUE TITLE
Nortek Security & Control LLC Garage Door Controller GD00Z-7 MISSING BUTTONS TO CONTROL DOOR

### ISSUE THREAD

**Issue by trentjw** [zwave-js/zwave-js#1751]
**Which device is missing?**
MISSING BUTTONS TO CONTROL GARAGE DOOR DEVICE FILE IS NOT BEING BUILT PROPER
Nortek Security & Control LLC Garage Door Controller GD00Z-7
it shows up as a sensor only, does not show up as a controller to operate the door network key is working as my kwikset locks are working as intended
**What are the IDs?**

Manufacturer ID: 0x14f
Product type: 0x4744
Product ID: 0x3531

**Did you check if we really don't have it built correct?**

- [x] Does not work proper
- [x] Missing Features
- [x] It is not in the [TODO list](https://github.com/zwave-js/node-zwave-js/issues/1600)

**Do you have a link to the PDF manual?**

If so, it helps in creating the config file.

**Comment by AlCalzone** [comment]
I told you on the last issue - please use the bug report template. We have the configuration file.

![grafik](https://user-images.githubusercontent.com/17641229/107882159-13e25480-6ee8-11eb-802e-95f6d3c577cc.png)
