### ISSUE TITLE
Nortek Security & Control LLC Garage Door Controller GD00Z-7 MISSING CONTROL BUTTONS 

### ISSUE THREAD

**Issue by trentjw** [zwave-js/zwave-js#1752]
MISSING BUTTONS TO CONTROL GARAGE DOOR DEVICE FILE IS NOT BEING BUILT PROPER
Nortek Security & Control LLC Garage Door Controller GD00Z-7
it shows up as a sensor only, does not show up as a controller to operate the door network key is working as my kwikset locks are working as intended
**What are the IDs?**

Manufacturer ID: 0x14f
Product type: 0x4744
Product ID: 0x3531

If so, it helps in creating the config file.

**Comment by AlCalzone** [comment]
Dude! Just use the bug report template, fill it out. Don't delete it!
Next time you just copy in the same information I'm gonna block you.

**Comment by trentjw** [comment]
Fine won't submit it anymore if you want to fix the faulty config file for zwave js for this device you can pull the xml file from one of the closed ones my zwave 1.4 is working fine so I don't need to use this anyways
