### ISSUE TITLE
FGRM222 Roller Shutter 2  FIBARO support for Manufacturer Proprietary controls

### ISSUE THREAD

**Issue by terriblefox** [zwave-js/zwave-js#1762]
Manufacturer Proprietary Control would enable the tilt control for lamellas in Venetian Blind mode. of the fibaro roller shutter. That would be awesome!

https://github.com/home-assistant/open-zwave/pull/6

**Comment by AlCalzone** [comment]
The fibaro proprietary CC is supported by zwave-js. If something is not working, I suggest you raise an issue in the HASS repo.

**Comment by terriblefox** [comment]
Ok, your are right I see the Manufacturer Proprietary in ZwaveJS is working ! Seems to be a HASS problem that its just not showing up and is not controllable. Thanks you.

**Comment by andre-richter** [comment]
@terriblefox did you get tilt control working in the meantime?
