### ISSUE TITLE
bug: heal seems to fail with silicon labs 700 controller

### ISSUE THREAD

**Issue by scyto** [zwave-js/zwave-js#1764]
**Describe the bug**

When i perform a heal it doesn't appear to work based on the logs..

**Device information**

All devices and all node IDs.
What are the node IDs?

**Last Known Working Configuration**
- [ ] New device
- [X] Previously working device (node-zwave-js) 
    - zwavejs2mqtt with razberry pi hat zwave controler - multiple versions
    - swapped to  the silicon labs SLUSB001A
  
    
**Installation information**
How did you install `node-zwave-js`?
- [ ] `zwavejs2mqtt` (latest) docker image
- [ ] `zwavejs2mqtt` (dev) docker image
- [ ] ioBroker.zwave2 adapter
- [ ] Pkg
- [X] Manual Docker build
    - `node-zwave-js` branch: master
    - `zwavejs2mqtt` branch: master
- [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github)) 
- [] Other: 

**To Reproduce**
1. Go to '.ontrol pane;'
2. Click on 'heal network'
4. See error in logs

**Additional context**
App Version
1.1.1+94ff7ed.94ff7ed

Zwavejs Version
6.3.0-8f22052

**Logfile:**
```
00:38:45.842 CNTRLR » [Node 002] refreshing neighbor list (attempt 1)...
00:38:45.853 DRIVER » [Node 002] [REQ] [RequestNodeNeighborUpdate]
                        callback id: 132
00:38:45.854 CNTRLR » [Node 003] refreshing neighbor list (attempt 1)...
00:38:45.860 CNTRLR » [Node 004] refreshing neighbor list (attempt 1)...
00:38:45.864 CNTRLR » [Node 005] refreshing neighbor list (attempt 1)...
00:38:45.867 CNTRLR » [Node 006] refreshing neighbor list (attempt 1)...
00:38:45.871 CNTRLR » [Node 007] refreshing neighbor list (attempt 1)...
00:38:45.874 CNTRLR » [Node 008] refreshing neighbor list (attempt 1)...
00:38:45.881 CNTRLR » [Node 009] refreshing neighbor list (attempt 1)...
00:38:45.884 CNTRLR » [Node 010] refreshing neighbor list (attempt 1)...
00:38:45.888 CNTRLR » [Node 011] refreshing neighbor list (attempt 1)...
00:38:45.891 CNTRLR » [Node 012] refreshing neighbor list (attempt 1)...
00:38:45.895 CNTRLR » [Node 013] refreshing neighbor list (attempt 1)...
00:38:45.900 CNTRLR » [Node 014] refreshing neighbor list (attempt 1)...
00:38:45.904 CNTRLR » [Node 015] refreshing neighbor list (attempt 1)...
00:38:45.907 CNTRLR » [Node 017] refreshing neighbor list (attempt 1)...
00:38:45.911 CNTRLR » [Node 018] refreshing neighbor list (attempt 1)...
00:38:45.914 CNTRLR » [Node 019] refreshing neighbor list (attempt 1)...
00:38:45.920 CNTRLR » [Node 020] refreshing neighbor list (attempt 1)...
00:38:49.396 DRIVER « [REQ] [RequestNodeNeighborUpdate]
                        callback id:   132
                        update status: UpdateStarted
00:39:26.956 DRIVER « [Node 020] [REQ] [BridgeApplicationCommand]
                      └─[ClockCCReport]
                          clock setting: Tuesday, 01:00
00:39:26.959 CNTRLR   [Node 020] detected a deviation of the node's clock, updating it...
00:39:26.995 DRIVER « [Node 020] [REQ] [BridgeApplicationCommand]
                      └─[ClockCCReport]
                          clock setting: Tuesday, 01:00
00:39:26.998 CNTRLR   [Node 020] detected a deviation of the node's clock, updating it...
00:39:54.419 DRIVER » [Node 003] [REQ] [RequestNodeNeighborUpdate]
                        callback id: 133
00:39:54.420 CNTRLR   [Node 002] refreshing neighbor list failed: Timeout while waiting for a callba
                      ck from the controller
00:39:54.421 CNTRLR » [Node 002] refreshing neighbor list (attempt 2)...
00:39:57.324 DRIVER « [REQ] [RequestNodeNeighborUpdate]
                        callback id:   133
                        update status: UpdateStarted
00:41:02.338 DRIVER » [Node 004] [REQ] [RequestNodeNeighborUpdate]
                        callback id: 134
00:41:02.340 CNTRLR   [Node 003] refreshing neighbor list failed: Timeout while waiting for a callba
                      ck from the controller
00:41:02.340 CNTRLR » [Node 003] refreshing neighbor list (attempt 2)...
00:41:04.925 DRIVER « [REQ] [RequestNodeNeighborUpdate]
                        callback id:   134
                        update status: UpdateStarted
```
this continue through all devices and then reports heal failed.

**Comment by AlCalzone** [comment]
Looks like the command was changed and the callback isn't correctly detected.

**Comment by scyto** [comment]
I assume nothing I can to do to help?

**Comment by AlCalzone** [comment]
Not at the moment

**Comment by kpine** [comment]
I initiated a heal on my network with the silicon labs 700-series controller. There didn't seem to be any problem that I could tell. I've attached my log for comparison.

[zwavejs_1.log](https://github.com/zwave-js/node-zwave-js/files/5991537/zwavejs_1.log)

**Comment by AlCalzone** [comment]
In the log above, we get the confirmation that the healing process was started, but for some reason the "Completed" message never comes. I'm investigating whether that is something we need to handle differently.

**Comment by kpine** [comment]
Three of my nodes are battery devices that never wake up, perhaps that's why?

**Comment by AlCalzone** [comment]
Sorry, I was talking about scyto's log

**Comment by scyto** [comment]
@kpine yeah your log  is different
I wonder if there is a difference between your SLUSB001A and mine?

I am in middle of trying to produce complete heal log, but after an hour I am at this, no idea how long it will take --edit seems it tries 5 times per device.
```
15:15:44.944 CNTRLR   [Node 014] refreshing neighbor list failed: Timeout while waiting for a callback from the controller
15:15:44.944 CNTRLR » [Node 014] refreshing neighbor list (attempt 4)...
                                        
```

**Comment by kpine** [comment]
Do you know what version of firmware your stick has? I can't seem to find this information in zwave-js, but [according to](https://github.com/zwave-js/node-zwave-js/issues/1357#issuecomment-761520370) the PC Controller software mine is 7.11.

**Comment by scyto** [comment]
Yes 7.11 here too.
ControllerBridgeLib is ver.8
![image](https://user-images.githubusercontent.com/11369180/108137993-e5908080-7071-11eb-8b79-2deae0f4d3a3.png)


I am running zwavejs in docker on a raspberry pi4 if that matters.
Very odd, i could try switching from my container built off the dockerfile.contrib to one off docker hub.....


Full log from start of heal to stop FWIW which isn't much more than the fragment, interestingly the first time i ever tried this i swear it said failed in the log and the UI.  But that was on previous zwavejs version.

[network.heal.log](https://github.com/zwave-js/node-zwave-js/files/5992366/network.heal.log)
it took just under 2 hours to attempt the heal.

UI at end showed 
![image](https://user-images.githubusercontent.com/11369180/108137503-d6f59980-7070-11eb-99b9-11315d267c0f.png)

**Comment by scyto** [comment]
yup same on issue for me on

  App Version = 1.1.1
  Zwavejs Version = 6.3.0

So that eliminates the self-built docker container being the issue.

**Comment by AlCalzone** [comment]
@scyto same thing still happens in the last log 🤷🏻‍♂️

**Comment by scyto** [comment]
@AlCalzone yup, I am confused why @kpine has no issue with his stick doing heal.

**Comment by AlCalzone** [comment]
@scyto how large is your network? How many mains-powered nodes, how many frequent listening (FLIRS), how many sleeping nodes (old school battery powered)?

**Comment by scyto** [comment]
@AlCalzone 19 device nodes, 16 mains powered, 3 FLIRS locks, and no battery devices.
All the  Jasco devices were bought circa 2013 as were all locks except the BE469ZP one.
The Fibaro is from 2013.
The aeotec devices are mixes of ages.

Heal worked on zwavejs with the wonky razBerry zwave hat (series 500 chip) on this pi.
when i remade the network last week on the 700 stick i started fresh and re-included everything. 

![image](https://user-images.githubusercontent.com/11369180/108246867-cd1e7580-7106-11eb-9876-0a7efc40bd6b.png)

**Comment by scyto** [comment]
Today I:

updated to latest public dev container
    - App Version 1.1.1
    - Zwavejs Version 6.4.0
    - Zwavejs-server Version 1.0.0-beta.
 
at the suggestion of @billiaz updated controller FW to 7.15 and raised gain to +4

looks like this fixed it:
```
13:24:30.297 SERIAL » 0x010600460a0171c5                                                   (8 bytes)
13:24:30.298 DRIVER » [Node 010] [REQ] [AssignReturnRoute]
                        payload: 0x0a0171
13:24:30.314 SERIAL « [ACK]                                                                   (0x06)
13:24:30.316 SERIAL « 0x0104014601bd                                                       (6 bytes)
13:24:30.317 SERIAL » [ACK]                                                                   (0x06)
13:24:30.319 DRIVER « [RES] [AssignReturnRoute]
                        has started: true
13:24:31.095 SERIAL « 0x01210046710000000000000000000000000000000000000000000000000000000 (35 bytes)
                      000e9
13:24:31.100 SERIAL » [ACK]                                                                   (0x06)
13:24:31.102 DRIVER « [REQ] [AssignReturnRoute]
                        callback id:     113
                        transmit status: OK
13:24:31.112 SERIAL » 0x010600460b0172c7                                                   (8 bytes)
13:24:31.113 DRIVER » [Node 011] [REQ] [AssignReturnRoute]
                        payload: 0x0b0172
13:24:31.123 SERIAL « [ACK]                                                                   (0x06)
13:24:31.125 SERIAL « 0x0104014601bd                                                       (6 bytes)
13:24:31.126 SERIAL » [ACK]                                                                   (0x06)
13:24:31.128 DRIVER « [RES] [AssignReturnRoute]
                        has started: true
13:24:32.688 SERIAL « 0x01210046720000000000000000000000000000000000000000000000000000000 (35 bytes)
                      000ea
13:24:32.689 SERIAL » [ACK]                                                                   (0x06)
13:24:32.690 DRIVER « [REQ] [AssignReturnRoute]
                        callback id:     114
                        transmit status: OK
13:24:32.699 SERIAL » 0x010600460c0173c1                                                   (8 bytes)
13:24:32.700 DRIVER » [Node 012] [REQ] [AssignReturnRoute]
                        payload: 0x0c0173
13:24:32.717 SERIAL « [ACK]                                                                   (0x06)
13:24:32.720 SERIAL « 0x0104014601bd                                                       (6 bytes)
13:24:32.720 SERIAL » [ACK]                                                                   (0x06)
13:24:32.722 DRIVER « [RES] [AssignReturnRoute]
                        has started: true
13:24:32.794 SERIAL « 0x01210046730000000000000000000000000000000000000000000000000000000 (35 bytes)
                      000eb
13:24:32.795 SERIAL » [ACK]                                                                   (0x06)
```
we can close if we want to call it a day and put this down to FW and/or gain?
It took 4 mins to do complete heal.

**Comment by AlCalzone** [comment]
Cool!

**Comment by scyto** [comment]
yeah, if those per controller plugins happen (i saw an issue somewhere on that) we might want to expose gain for controllers that support it? 
Want me to close?

**Comment by kpine** [comment]
> updated controller FW to 7.15 and raised gain to +4

Do you have a reference on how to perform the update?

**Comment by scyto** [comment]
> > updated controller FW to 7.15 and raised gain to +4
> 
> Do you have a reference on how to perform the update?

high level only:
- install simplicity studio and zwave tools (why do they make that so hard)
- do a backup of the stick
- when in the controller top level UI click OTW icon
- navigate to C:\SiliconLabs\SimplicityStudio\v5\developer\sdks\gecko_sdk_suite\v3.1\protocol\z-wave\Apps\bin\gbl
- choose (for US) ZW_SerialAPI_Controller_7.15.2_214_EFR32ZG14_REGION_US.gbl (the LR version won't buy you anything unless you have some LR devices, and i don't think they exist yet?)
- wait, and its done

For gain:
- install simplicity studio and zwave tools
- on the controller top level menu pick the 'transmit settings'
- change the first box to +4
![image](https://user-images.githubusercontent.com/11369180/108272178-c273d880-7126-11eb-93ae-ee3d29ce7130.png)

**Comment by scyto** [comment]
![image](https://user-images.githubusercontent.com/11369180/108274438-c2290c80-7129-11eb-8dbc-8a3d6d0ac4e3.png)

**Comment by hanskroner** [comment]
> For gain:
> 
> * install simplicity studio and zwave tools
> * on the controller top level menu pick the 'transmit settings'
> * change the first box to +4

It looks like you're based in the US. You should know the FCC has power output limitations on the 916MHz ISM channels used by Z-Wave in that region - they don't allow for anything higher than +0dBm.

My guess is that your controller is situated somewhere where there's "a lot" of RF interference. Older 500-series hardware uses region-specific SAW filters to combat this. The newer Z-Wave 700 hardware has better RF blocking performance, and the region-specific SAW filters aren't typically needed anymore (which is great for manufacturers, as it means they no longer have to make region-specific hardware). Maybe in your particular case, the controller is located too close to another RF source - is it possible for you to try repositioning it?

If there is an interference issue, just raising the output power will leave you with flaky connections anyway. Being able to "shout louder" is only half of the equation - you also need to be able to "listen better", which you don't have a setting for.

**Comment by scyto** [comment]
@hanskroner  thanks for the insight. interesting.

All i can say is that no i placed this in a part of my house with the least RF i know, away from all other devices. (i have a stupid long cable so i could do just this :-) during testing.

That according to the log the stick was only having an issue when waiting for a response back - the logs were clear it was waiting for packet back and once i made *all* the changes the problem went away, but i made multiple changes at same time (stupid me).

I will back off the db setting and see if problem returns, if not then we may conclude the issue was something else.

If the problem returns I can also try a short usb extension cable and see if distancing the USB stick from the raspberry pi makes a difference (in case the pi is generating RF - maybe the poe hat wit fan and oled screen is causing an issue.....)

**Comment by scyto** [comment]
i backed off the +4db and heal is still working so at this point ¯\(°_o)/¯
i will stop saying the +4db is what fixed it for me

**Comment by scyto** [comment]
backing off the +4db was a big mistake, issues came back (healing, missing lifelines, etc)
someone else pointed out that +4db with 33 measured is actually -2.9 db so well under the 0db

I get this is transmission - for beam formed packets used to wake up locks transmit is key....

**Comment by hanskroner** [comment]
> backing off the +4db was a big mistake, issues came back (healing, missing lifelines, etc)
> someone else pointed out that +4db with 33 measured is actually -2.9 db so well under the 0db

I'm not intimately familiar with how the FCC testing is performed, I just remember the +0dBm figure. If you didn't need to tweak anything on your 500-series stick, that was outputting +0dBm as well, which is why my mind went to "interference issues." If you're missing Lifeline reports, an interference issue sounds even more likely - your stick isn't transmitting anything in that scenario, only receiving. Bumping your stick's output power doesn't affect the output power of any other nodes in the network.

> I get this is transmission - for beam formed packets used to wake up locks transmit is key....

Z-Wave doesn't do beam forming. The "beaming" used to wake-up FLiRS nodes is, in the US, essentially a second-long jam with a repeating pattern that FLiRS nodes scan for either 1 or 4 times per second, depending on the way they're setup. The output power these "beams" are transmitted at is the same as all other regular frames.

It's also only the last "hop" in a route that beams the FLiRS node, so your USB stick is responsible for beaming your lock only if the lock is in direct range of your stick.

**Comment by scyto** [comment]
It is in direct range of all four locks in a 3000 sq ft house.
