### ISSUE TITLE
Pending Node Interviews, waiting for the lowest NodeID to be interviewed.

### ISSUE THREAD

**Issue by marcus-j-davies** [zwave-js/zwave-js#1781]
**Describe the bug**
It seems, for battery operated nodes that have a pending interview, they will not get interviewed, until the lowest NodeID, has been woken up, and interviewed.

As an example, if Nodes 3,4 have a pending interview, waking up node 4, does not result in an interview,
until node 3 has been woken up/interviewed. Once that happens, the interview for 4 then immediately starts. 

**Device information**
2 x Aeotec Door/Window Sensor 7 (but may affect others)
https://devices.zwave-js.io/?jumpTo=0x0371:0x0002:0x0007:0.0

**Last Known Working Configuration**
- [ ] New device
- [x] Previously working device (node-zwave-js)
    - I have only noticed this since 6.3.0 (but can't be sure)
    - Only updating the lib version

**Installation information**
- [ ] `zwavejs2mqtt` (latest) docker image
- [ ] `zwavejs2mqtt` (dev) docker image
- [ ] ioBroker.zwave2 adapter
- [ ] Pkg
- [ ] Manual Docker build
- [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github)) 
- [x] Other: Node-Red Plugin

**To Reproduce**
1 - Ensure is new environment (no cache)
2 - Ensure battery operated nodes are a sleep - to cause an interview to be queued.
3 - wake up a node - but ensure its not the lowest ID node pending an interview (it will not get interviewed).
4 - Wake up the lowest NodeID pending an interview, (it will get interviewed, including the previous awaken one)

Line : 1203 -> Waking up Node 4 (no interview)
Line : 1217 -> Waking up Node 3 (interview, +interview for Node 4)

[zwave-2336.log](https://github.com/zwave-js/node-zwave-js/files/5988415/zwave-2336.log)

Hopefully have submitted this all correctly?

**Comment by AlCalzone** [comment]
@marcus-j-davies in a few minutes a debug build will be available in https://github.com/zwave-js/node-zwave-js/pull/1783
Please install that and send me another log.

**Comment by marcus-j-davies** [comment]
@AlCalzone ,
[zwave-7504.log](https://github.com/zwave-js/node-zwave-js/files/5988604/zwave-7504.log)

**Comment by marcus-j-davies** [comment]
@AlCalzone 
https://github.com/zwave-js/node-zwave-js/pull/1784 fixes the bug (log Attached).

Oddly (but maybe more device location specific)
the interview for the first awaken node, is super fast (<=5 seconds) Node 3 ~7 seconds

I checked the cache, to ensure it really was interviewed - it was

[zwave-3120.log](https://github.com/zwave-js/node-zwave-js/files/5988926/zwave-3120.log)
 
 EDIT:
 Node 3 travels via node 2 - so a littler mileage involved, which explains the speed difference.

**Comment by AlCalzone** [comment]
Yup, Node 4 has a really low delay in responses.
