### ISSUE TITLE
ZXT-120 Remotec

### ISSUE THREAD

**Issue by eonnet** [zwave-js/zwave-js#1827]
The Remotec ZXT-120 AC Master is missing controls for Fan speed, I used it in the past on Vera system and you were able to change fan speed from auto to on and vice versa, also I was able to control the fan speed with z-wave2mqtt but here its missing.

**Which device is missing?**

Remotec ZXT-120

**What are the IDs?**

Manufacturer ID: 0x5254  
Product type: 0x8377  
Product ID: 0x0101  

**Did you check if we really don't have it?**
You have it in the database its just missing fan control
- [ ] It is not in the [configuration DB](https://devices.zwave-js.io/)
- [ ] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)
- [ ] It is not in the [TODO list](https://github.com/zwave-js/node-zwave-js/issues/1600)

**Do you have a link to the PDF manual?**

If so, it helps in creating the config file.

**Comment by AlCalzone** [comment]
> You have it in the database its just missing fan control

Then this is not the correct issue template.

Also, fan support is released with `v6.3.0`:
https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md#features-1
