### ISSUE TITLE
Aeon Recessed Door Sensor 5 wakeup 0 [bug]

### ISSUE THREAD

**Issue by chrish987** [zwave-js/zwave-js#1833]
**Describe the bug**

The Aeon Recessed Door sensor seems to have wakeup default to 0. 

I noticed this as these nodes (i have 2) never seem to complete the reinterview process after a server restart. Looking at the configuration I am guessing that a configured wakeup of 0 is stopping the node ever waking up.

When discovered these nodes show up as ZW089-B. Can workaround be manually forcing wakeup (click button on node).

I have manually updated value to 3600 will see if this fixes issue on next restart, but seems like the 0 default value is probably a problem.

**Device information**
Device ID: 134-89-514 (0x0086-0x0059-0x0202)
![Capture-zw2](https://user-images.githubusercontent.com/77754678/108571865-f2fd8180-7375-11eb-8dbb-3afa590be42a.JPG)

**Comment by AlCalzone** [comment]
The issue template is there for a reason, you should not simply delete half of it. Looking into my glass sphere I see the following:

The nodes should be ready almost immediately after a restart - even if they are in the RestartFromCache stage. If not, you probably need to update to the latest zwave-js version.
We cannot do anything about the default configuration value.
The query after restart will not be done once #1787 is merged.

**Comment by blhoward2** [comment]
You need to wake the sensor back up to have it take the value. The zero is what was stored on the device, we're not setting the default each time. Mine work just fine.

**Comment by chrish987** [comment]
The odd thing is that the minimum value for wakeup is 240 yet default 0. I thought it might be a wrong setting in the node definition. I have fixed it by manually changing.

I have some other 'quirks' with behaviors on server restart (e.g. nodes staying in ProtocolInfo when I know they have been through the wakeup cycle (seen it in the logs).

I guess most of this is really cosmetic as the nodes 'work' they send values and notifications - so just the display in the node list.

I will wait until #1787 is released and see what new behavior is.

Thanks

**Comment by blhoward2** [comment]
What makes you think 240 is the minimum? 0 disables wake ups.

**Comment by chrish987** [comment]
this is from the Gen7 docs, Gen5 hard to find for some reason. Anyway - happy for this issue to be closed - will wait for the #1787 release.
![Capture-ds](https://user-images.githubusercontent.com/77754678/108610154-551ebb00-7438-11eb-8638-0c51023fb8c0.JPG)

**Comment by blhoward2** [comment]
Well, our config files have no impact on the wake up. That default value is coming from the device itself I imagine. In any event it accepts 0 and that disables wake ups.

**Comment by AlCalzone** [comment]
> That default value is coming from the device

👆🏻 this.

> I have some other 'quirks' with behaviors on server restart (e.g. nodes staying in ProtocolInfo

If the nodes have been interviewed before, they should not be in the ProtocolInfo stage. But since you didn't provide a log like the template asks for, all we can do here is guess.

**Comment by chrish987** [comment]
My log is 95M, I am guessing you do not want all that. Before next restart I will delete the log and send through more relevant information - or will you need things from an earlier log? (i.e. when the device was first included?)

My log file also seems to not have dates, just times, lines look like this:
_03:13:28.018 DRIVER   starting driver...
03:13:28.023 DRIVER   opening serial port /dev/ttyAMA0_
Is this something in my config, or is there a way to enable dates? (i am running the zwavejs2mqtt docker image)

**Comment by AlCalzone** [comment]
It compresses fairly well but having a fresh log without old cruft would be better, I agree

**Comment by robertsLando** [comment]
Hi @chrish987, sorry for bothering you in a issue but I don't have your email, could you reach me out via private email or give me your email? I need to ask you something, thanks 🙏🏼 

My email is: daniel.sorridi@gmail.com
