### ISSUE TITLE
Network heal times out too early

### ISSUE THREAD

**Issue by maivorbim** [zwave-js/zwave-js#1842]
Network heal command fails with error: _refreshing neighbor list failed: Timeout while waiting for a callback from the controller_

Healing starts at `13:33:09.939 CNTRLR   starting network heal...`

Running Zwavejs 6.4.0. Please let me know if any further details are required to debug this. Thank you.

[zwavejs_4017.log](https://github.com/zwave-js/node-zwave-js/files/6017631/zwavejs_4017.log)

**Comment by AlCalzone** [comment]
Which stick are you using? I've had reports that healing on the new 700 series sticks only worked after a firmware update.

**Comment by maivorbim** [comment]
Aeotec Zstick Gen5+. I remember healing working on 6.1.0 or 6.2.0, so I don't think it is related to the stick.

**Comment by AlCalzone** [comment]
> Timeout while waiting for a callback from the controller

Often means that the controller is stuck somehow and could use a power cycle.
In case of a network heal it is possible that the timeout is chosen too short, but I don't guess your network grew substantially?

**Comment by maivorbim** [comment]
it did actually...I think i have doubled network size from 6.1.0/6.2.0 to 6.4.0. I will try doing a power cycle and let you know if that solves it.

**Comment by AlCalzone** [comment]
Hm how many nodes? Of those, how many are mains powered, how many FLIRS and how many oldschool (sleeping) battery powered?

**Comment by maivorbim** [comment]
56 total nodes, out of which 11 mains powered nodes (including 2 Aeotec Range Extender 7), 36 battery flirs nodes and 9 battery non-flirs nodes.

**Comment by AlCalzone** [comment]
I'll need to calculate, but this could actually mean we're not waiting long enough.

**Comment by maivorbim** [comment]
You might be right about the timeout. I shutdown the machine, removed power cable, powered it back on, started HA, let it finish node interview and still getting the same errors as before.

I also saw this in the log:  _17:19:55.575 DRIVER     no handlers registered!_

```
17:19:29.649 DRIVER « [REQ] [RequestNodeNeighborUpdate]
                        callback id:   174
                        update status: UpdateFailed
17:19:29.650 CNTRLR « [Node 092] refreshing neighbor list failed...
17:19:29.650 CNTRLR   [Node 092] failed to update the neighbor list after 5 attempts, healing failed
17:19:55.569 SERIAL « 0x01050048ae223e                                                     (7 bytes)
17:19:55.570 SERIAL » [ACK]                                                                   (0x06)
17:19:55.571 DRIVER « [REQ] [RequestNodeNeighborUpdate]
                        callback id:   174
                        update status: UpdateDone
17:19:55.575 DRIVER   handling request RequestNodeNeighborUpdate (72)
17:19:55.575 DRIVER     no handlers registered!
17:21:28.375 SERIAL « 0x010b0004005a05310505011788                 
```

I have also tested healing on a different smaller network (19 nodes), also on 6.4.0, and there the healing worked, so I don't think it is a bug, more likely a timeout issue as you suspected.

**Comment by AlCalzone** [comment]
Okay, based on your network size it seems like we should be waiting around 3 minutes for the callback, rather than the fixed 65 seconds we currently wait.

**Comment by scyto** [comment]
should the timeout dynamically scale with the number of devices?

**Comment by AlCalzone** [comment]
It should, but doesn't right now.

**Comment by AlCalzone** [comment]
@maivorbim can you test the linked PR please?
