### ISSUE TITLE
Use complete ISO8601 timestamps with timezone in debug log

### ISSUE THREAD

**Issue by robinsmidsrod** [zwave-js/zwave-js#1968]
When I'm trying to ingest the debug log using filebeat/logstash the timestamp emitted in the log doesn't contain a date section, and it's unclear if the timestamp is in UTC or local time zone.

It would be really helpful if the timestamp used the standard ISO8601 timestamp format with millisecond accuracy and timezone information. For ease of implementation it would be most practical if it was in the UTC timezone, because then you wouldn't have to care about how the timezone part is formatted (it would just be `Z`) and daylight savings workarounds would be a non-issue (because UTC doesn't have daylight savings).

An ISO8601-formatted timestamp looks like this: `YYYY-MM-DDThh:mm:ss.SSSZ`, so right now would be `2021-03-01T20:14:28.670Z`, which you can emit with a command like this: `date -u '+%FT%T.%3NZ'`

Most programming languages have a way to emit timestamps using strftime formats like the one used by `date(1)` above in some way or another.

**Comment by AlCalzone** [comment]
fixed in https://github.com/zwave-js/node-zwave-js/pull/2030
