### ISSUE TITLE
removeNodeFromAllAssocations misspelled

### ISSUE THREAD

**Issue by MartinHjelmare** [zwave-js/zwave-js#1999]
**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I am **not** using ZWaveJS2MQTT. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog and my problem was **not** mentioned there.

**Describe the bug**

A clear and concise description of what the bug is. Describe what causes the bug, what you observe, and what happens as a result.

---

The controller command `removeNodeFromAllAssocations` seems to be misspelled. Looks like it should be `removeNodeFromAllAssociations`.

- Docs: https://zwave-js.github.io/node-zwave-js/#/api/controller?id=managing-associations
- Code: https://github.com/zwave-js/node-zwave-js/blob/fc5492fbe517901ea0fd30a81b6be6eb2020be4c/packages/zwave-js/src/lib/controller/Controller.ts#L2027

Would it be possible to fix this typo, even though it could be considered a breaking change?

---

**Device information**

Which device(s) is/are affected (make/model)?  
What are the node IDs?

**Did you change anything?**
- [ ] **Yes**: *(please describe)*
- [x] **No**

**Did this use to work before?**
- [ ] **Don't know**, this is a new device
- [x] **No**, it never worked anywhere
- [ ] **Yes**, in: *(specify application with versions)*
    
**How are you using `node-zwave-js`**
- [ ] `zwavejs2mqtt` (latest) docker image
- [ ] `zwavejs2mqtt` (dev) docker image
- [ ] `zwavejs2mqtt` Manual Docker build
    - `node-zwave-js` branch: 
    - `zwavejs2mqtt` branch: 
- [ ] ioBroker.zwave2 adapter
- [x] `HomeAssistant` version XYZ
- [ ] Pkg
- [ ] Manual Docker build
    - `node-zwave-js` branch: 
    - `zwavejs2mqtt` branch: 
- [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github)) 
- [ ] Other: 

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Additional context**

**Logfile:**

**Comment by AlCalzone** [comment]
I'm collecting a bunch of breaking changes for 7.x, so this is just another one for that heap :)

**Comment by AlCalzone** [comment]
fixed in https://github.com/zwave-js/node-zwave-js/pull/2030
