### ISSUE TITLE
zw6302.json motion sensor config is saved under "zooz" please copy or move to "GE/Jasco"

### ISSUE THREAD

**Issue by djaydev** [zwave-js/zwave-js#2008]
The config for zw6302 Portable Smart Motion Sensor is saved under `node-zwave-js/packages/config/config/devices/0x027a/zw6302.json` in github, but I believe this config should instead be saved under `node-zwave-js/packages/config/config/devices/0x0063/zw6302.json` in github. From what I can find there isn't a device called Zooz zw6302 but if it is, please copy the file to GE/Jasco folder.

Thank you

**Comment by djaydev** [comment]
zwave-js/zwavejs2mqtt#416

**Comment by AlCalzone** [comment]
@blhoward2 that's your turf :)

**Comment by blhoward2** [comment]
Interesting. Not really sure how that would have happened. I haven't yet pushed the file I referenced so this must have come in wrong at some point before.

**Comment by blhoward2** [comment]
It turns out I already merged a file for this last night. It'll get cleaned up when I template the GE devices but it's there.
