### ISSUE TITLE
[V7 Alpha 0]: Unable to output a log

### ISSUE THREAD

**Issue by marcus-j-davies** [zwave-js/zwave-js#2031]
I would attach a log - to detail a problem with the log 🤣 .

The console is all glitched.
setting the ENV `LOGTOFILE` doesn't produce anything.

CMD: set LOGTOFILE=true
PS: $env:LOGTOFILE=1
PS: $env:LOGTOFILE="true"

Apologies, if I am missing something here? 

![image](https://user-images.githubusercontent.com/55892693/110646661-02226300-81af-11eb-87ec-719d9b52d336.png)

**Comment by AlCalzone** [comment]
Seems that the env variable no longer works. The recommended approach via driver options does:
https://zwave-js.github.io/node-zwave-js/#/api/driver?id=zwaveoptions
https://zwave-js.github.io/node-zwave-js/#/api/driver?id=logconfig

**Comment by marcus-j-davies** [comment]
Cool,

On the school run currently.

Will give that a go soon
This is to grab a log for another potential early bug for V7.
