### ISSUE TITLE
[V7 Alpha 0]: Could not assemble partial CCs because the payload is invalid. Dropping them

### ISSUE THREAD

**Issue by marcus-j-davies** [zwave-js/zwave-js#2034]
The original bug I wanted to report.

My network key is: [0x7a,0x29,0xfa,0x5f,0xbb,0xf5,0x54,0xf9,0x1c,0xb7,0xf1,0x41,0x53,0x34,0x7b,0xe8]
its only a test system - so not worried about visibility.

Pressing the buttons 0-9, should yield an Entry Control Notification (wrapped in the Notification event), is not happening.

[log.txt](https://github.com/zwave-js/node-zwave-js/files/6117180/log.txt)

Sorry its short, and to the point, but I'm logging them as I find them.

**Comment by AlCalzone** [comment]
Well, that's another case of a manufacturer that does not read the specifications correctly... I looked at the first message that is being dropped.

The specs mandate for the event data:
> The format of this field MUST comply with the data format advertised by the Data Type field.

The device is sending an Entry Control Notification with a data type of 0x02 (ASCII)., which means the event data **MUST** satisfy:
> **1 to 32** ASCII encoded characters. ASCII codes MUST be in the value range 0x00-
0xF7. The string MUST be padded with the value 0xFF to fit 16 byte blocks when sent
in a notification.

Your device sends 0 bytes for the event data, which is less than 1. Either it should use the format `0x00` (No Data) or it should include data that match the specs.

I can add a workaround for empty buffers (which is clearly not correct but shouldn't hurt). But in any case you should bug the manufacturer to fix their stuff.

**Comment by marcus-j-davies** [comment]
I guess this is an inconsistent bug, with said manufacturer 
it seems to come though on PC Controller and the early CC implementation.

But then, they both may not have been spec compliant

**Comment by AlCalzone** [comment]
I added the checks before merging the draft implementation because most of these constraints were not reflected in the draft implementation.

It working in the PC controller does not mean it should be working. It is a dev tool and not bound by certification requirements.

That being said, I don't think it hurts to re-interpret those commands as having no data, but it certainly is not correct.
