### ISSUE TITLE
Document `node.ready` property

### ISSUE THREAD

**Issue by hufftheweevil** [zwave-js/zwave-js#2063]
**Is your feature request related to a problem? Please describe.**
Need to know the ready status of all nodes after the nodes have already emitted their ready event.

**Describe the solution you'd like**
There should be a `.ready` or `.isReady` property on each node. It is my understanding that `.interviewStage == "Complete"` does not exactly equate to being "ready". But perhaps I am wrong.

**Describe alternatives you've considered**
Storing a local array that is appended when the ready event is emitted. And then referencing that array later. However, this is only good for one scope. If the driver/controller is shared among more than one scope, than an array is needed for each - or some way of linking the array among the scopes.

**Comment by AlCalzone** [comment]
There is:
https://github.com/zwave-js/node-zwave-js/blob/ec2757843b4acb8c7947ded92f1d20deb6552466/packages/zwave-js/src/lib/node/Node.ts#L435

It just seems to be missing from the docs.
