### ISSUE TITLE
[bug] UNKNOWN units in device METER CC

### ISSUE THREAD

**Issue by Masterz69** [zwave-js/zwave-js#2076]
### Version

HA OS 5.12 on RPi4 4G

![image](https://user-images.githubusercontent.com/15225823/110006099-e425b000-7d21-11eb-801d-5a1301f84381.png)

### Describe the bug

UNKNOWN entries in Plug device METER section.
Initially no one, but now 9.

### To Reproduce

When device paired - no UNKNOWN entries.
After several Core & Host restart - appears.

### Expected behavior

Only entries actually exposed by device.

### Additional context

![image](https://user-images.githubusercontent.com/15225823/110005372-11259300-7d21-11eb-80f0-fbbb74bddb06.png)

[node_2.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6085653/node_2.zip)

**Comment by AlCalzone** [comment]
Ok, closing for now. If it reappears and you happen to catch it in a log, feel free to reopen.

**Comment by Masterz69** [comment]
Sure. Not appeared anymore.
