### ISSUE TITLE
Firmware OTA does not seem to work for Qubino device?

### ISSUE THREAD

**Issue by ualex73** [zwave-js/zwave-js#2078]
**Checklist:**

- [X] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [X] I am **not** using ZWaveJS2MQTT. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog and my problem was **not** mentioned there.

**Describe the bug**

I got a newer firmware for my Qubino Smart Plug 16A and I am trying to upgrade the firmware via OTA (2.0 to 4.0). I see in the log it tries to start, but it seems to retry every time packet 1 (out of 2266).

**Device information**

Which device(s) is/are affected (make/model)? Qubino Smart Plug 16A
What are the node IDs? 007

**Did you change anything?**
- [ ] **Yes**: *(please describe)*
- [X] **No**

**Did this use to work before?**
- [ ] **Don't know**, this is a new device
- [X] **No**, it never worked anywhere
- [ ] **Yes**, in: *(specify application with versions)*
    
**How are you using `node-zwave-js`**
- [X] `zwavejs2mqtt` (latest) docker image
- [ ] `zwavejs2mqtt` (dev) docker image
- [ ] `zwavejs2mqtt` Manual Docker build
    - `node-zwave-js` branch: 
    - `zwavejs2mqtt` branch: 
- [ ] ioBroker.zwave2 adapter
- [ ] `HomeAssistant` version XYZ
- [ ] Pkg
- [ ] Manual Docker build
    - `node-zwave-js` branch: 
    - `zwavejs2mqtt` branch: 
- [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github)) 
- [ ] Other: 

**To Reproduce**

1. Click on firmware update
2. Select target 0
3. Select firmware

**Additional context**

**Logfile:**
[zwavejs_X.log](https://github.com/zwave-js/node-zwave-js/files/6141251/zwavejs_X.log)

**Comment by AlCalzone** [comment]
zwave-js doesn't decide which fragment to send, because the device requests it from the controller. It looks like the command with the firmware fragment is received by the device but then it doesn't understand it or something.

I'll ask my contact at Qubino if they can make sense of this - for me it looks like zwave-js does the right thing.

**Comment by ualex73** [comment]
@AlCalzone thanks for the quick response, and hopefully you get something from you Qubino contact.

**Comment by AlCalzone** [comment]
Okay I was told that Qubino tested the OTA functionality with the PC controller and Z-Wave.me in unsecure, S0 and S2 mode and that it should work.

Can you try to do the update with PC controller (included in [Simplicity Studio](https://www.silabs.com/developers/simplicity-studio#releasenotes)) to check if it works there?

If it doesn't, there's likely a problem with your device and you should contact the Qubino support.
If it does work, please let me know so Qubino can try to replicate the issue.

**Comment by ualex73** [comment]
Ok, i will give the simplicity studio a try.

**Comment by ualex73** [comment]
I tried it, but not-secure and secure (S0) both end successfully with uploading the firmware. I hear a click after the firmware upgrade, but when I re-check firmware (checksum and version), nothing has changed.

**Comment by AlCalzone** [comment]
Alright, can you contact the Qubino support about this please?

**Comment by ualex73** [comment]
yes, I did ... so I will close this one.

**Comment by AlCalzone** [comment]
Please keep me updated when you know more.
