### ISSUE TITLE
[V7, BETA 0] protocolVersion is not retained after a restart

### ISSUE THREAD

**Issue by marcus-j-davies** [zwave-js/zwave-js#2081]
- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I am **not** using ZWaveJS2MQTT. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog and my problem was **not** mentioned there.

**Describe the bug**
After the initial interview, the `protocolVersion` of the ZWaveNode is available. but after a restart, that property is `undefined`.
after re-interviewing, the `protocolVersion` property is once again available

**Device information**
All devices

**Did you change anything?**
- [ ] **Yes**: *(please describe)*
- [x] **No**

**Did this use to work before?**
- [x] **Don't know**, have only paid attention to testing V7 BETA 0
- [ ] **No**, it never worked anywhere
- [ ] **Yes**, in: *(specify application with versions)*
    
**How are you using `node-zwave-js`**
- [x] Other: Node-Red (using ZWJS V7, BETA 0)

**To Reproduce**
1 - After initial interview, you should find `protocolVersion` has been provided
2 - Restart the driver, it has become `undefined`

**Logfile:**
Line 247 - is the re-interview

EDIT:
Sorry wrong log
[log.txt](https://github.com/zwave-js/node-zwave-js/files/6141711/log.txt)

**Comment by marcus-j-davies** [comment]
Oddley, line 246 is...
`Beginning interview - last completed stage: None`

not sure it makes a difference, but the `interviewStage `is `Complete` prior to re-interview

Edit:
You may want this also (development network key - not secret) 
[0x7a,0x29,0xfa,0x5f,0xbb,0xf5,0x54,0xf9,0x1c,0xb7,0xf1,0x41,0x53,0x34,0x7b,0xe8]

**Comment by AlCalzone** [comment]
> Beginning interview - last completed stage: None

Re-interview resets all the information, including the interview stage.

**Comment by marcus-j-davies** [comment]
Yup, thought it be something like that.
