### ISSUE TITLE
Metadata for Notification CC V1 alarmLevel/Type has changed

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwave-js#2127]
**Checklist:**

- [ ] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [ ] I am **not** using ZWaveJS2MQTT. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog and my problem was **not** mentioned there.

**Describe the bug**

Since v6.5.1, the metadata for alarmLevel/Type values in Notification CC V1 has changed:
* In 6.5.0, type was "number" and "writeable" was false.
* In 6.5.1+, type is "any" and "writeable" is true.

The change has caused the corresponding entities in Home Assistant to become unavailable. The discovery schema assumes the notification cc-based sensor values will be of type "number", which was true from v6.5.0. Since that has changed, the entities are no longer discovered. I did not see anything in the changelog that would indicate a change in value type, although there look to be some notification cc-related changes.

The "writeable" property, while mostly benign, does cause zwavejs2mqtt to show it as an editable field, and setting it  obviously fails since these values aren't actually writable. In 6.5.0 it is a read-only field.

6.5.0:

<img width="490" alt="6 5 0" src="https://user-images.githubusercontent.com/791794/111921806-d8d9c080-8a53-11eb-961e-292971075b50.png">

6.5.1:

<img width="472" alt="6 5 1" src="https://user-images.githubusercontent.com/791794/111921817-e98a3680-8a53-11eb-8520-bf29b686fe9d.png">

**Device information**

Which device(s) is/are affected (make/model)?  ZCOMBO smoke alarm (gen 1)
What are the node IDs? 10

**Did you change anything?**
- [X] **Yes**: *(please describe)* Upgraded zwave-js from v6.5.0 to a newer version (any version from 6.5.1).
- [ ] **No**

**Did this use to work before?**
- [ ] **Don't know**, this is a new device
- [ ] **No**, it never worked anywhere
- [X] **Yes**, in: *(specify application with versions)* zwavejs2mqtt 2.0.0 with node-zwave-js 6.5.0.
    
**How are you using `node-zwave-js`**
- [X] `zwavejs2mqtt` (latest) docker image: I used tagged versions, 2.0.0 shows this problem, 2.0.1 and later does not.
- [ ] `zwavejs2mqtt` (dev) docker image
- [ ] `zwavejs2mqtt` Manual Docker build
    - `node-zwave-js` branch: 
    - `zwavejs2mqtt` branch: 
- [ ] ioBroker.zwave2 adapter
- [ ] `HomeAssistant` version XYZ
- [ ] Pkg
- [ ] Manual Docker build
    - `node-zwave-js` branch: 
    - `zwavejs2mqtt` branch: 
- [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github)) 
- [ ] Other: 

**To Reproduce**

1. Start the software
2. If HA is installed, observe the entities are unavailable, see metadata type of values is "any"
3. If using zwavejs2mqtt, see that the alarmLevel/Type are editable, sending the value fails

I was able to reproduce by simply downgrading to 6.5.0 using the existing cache files.

**Additional context**

Reported by another user in the HA forums, which prompted me to check my own instance, where I discovered the same problem. https://community.home-assistant.io/t/lets-start-talking-about-the-new-z-wave-js-integration/269731/927

**Logfile:**
Logs/cache/dumps from 6.5.0: [6.5.0.zip](https://github.com/zwave-js/node-zwave-js/files/6178455/6.5.0.zip)
Logs/cache/dumps from 6.5.1: [6.5.1.zip](https://github.com/zwave-js/node-zwave-js/files/6178457/6.5.1.zip)
Logs/cache/dumps from 6.6.3: [6.6.3.zip](https://github.com/zwave-js/node-zwave-js/files/6178458/6.6.3.zip)

**Comment by AlCalzone** [comment]
I'll need to see a log which includes a re-interview of the affected node and the receipt of a notification report.

**Comment by kpine** [comment]
Which version do you need to see an interview of, and notification report, 6.5.0, 6.6.3, or both? The device was originally included in 6.5.0 or earlier. The type provided is based on whichever version is installed, no interview necessary to see it change.

**Comment by AlCalzone** [comment]
One where it is broken.

**Comment by kpine** [comment]
Re-interview seems to have fixed that, type is number and writeable is false now. 

A side effect of the re-interview: my node's manufacturer and product information are all unknown now.

[zwavejs.log](https://github.com/zwave-js/node-zwave-js/files/6200264/zwavejs.log)
[node_10.json.txt](https://github.com/zwave-js/node-zwave-js/files/6200267/node_10.json.txt)

EDIT: restarting zwavejs2mqtt brought back the correct names, still strange.

**Comment by AlCalzone** [comment]
> Re-interview seems to have fixed that, type is number and writeable is false now.

Probably because I changed how this metadata is defined (static -> dynamic). Its generally a good idea to re-interview a node if some of the reported info seems off.

> A side effect of the re-interview: my node's manufacturer and product information are all unknown now.

You had two interviews going on in parallel which corrupted each other. 7.0.0 fixes that (hopefully).
