### ISSUE TITLE
[bug] Firmware update not working with unknown manufacturer

### ISSUE THREAD

**Issue by atterdal** [zwave-js/zwave-js#2136]
Hi!

Non-updated Aeotec Nano Dimmers register as "Unknown product 0x006f" by "Unknown manufacturer 0x0086".

This makes it so that it's not possible to update firmware OTA.

<img width="1647" alt="Skärmavbild 2021-03-22 kl  10 45 16" src="https://user-images.githubusercontent.com/2734444/111970579-b8654100-8afb-11eb-9591-d030dbc6d943.png">

**Comment by AlCalzone** [comment]
@atterdal I need a zwave-js logfile to debug this. => https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report?id=export-logs

**Comment by SAABoholic** [comment]
FYI
I just successfully updated my US version ZW111 from 2.2 to 2.3 via the interface from ZWaveJS2MQTT 3.0 and ZWaveJS 6.6.0
using the .exe file in the FW package from Aotecs website.

[EDIT] It was listed as unknown prior to the update and showed up correctly after the update followed by a re-interview.
