### ISSUE TITLE
Document how to use the default formats for custom log transports

### ISSUE THREAD

**Issue by andresn81** [zwave-js/zwave-js#2142]
**Checklist:**

- [ ] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [ ] I am **not** using ZWaveJS2MQTT. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog and my problem was **not** mentioned there.

**Describe the bug**

Since the log files can get pretty big I'm using winston file transport with maxsize/maxFiles configured and this worked great in pre v7 but when I upgraded to version 7.0.0 today, I'm only seeing "undefined" in the log file. I have attached the log file.

**Did this use to work before?**
- [ ] **Don't know**, this is a new device
- [ ] **No**, it never worked anywhere
- [x] **Yes**, in: pre v7
    
**How are you using `node-zwave-js`**
- [x] Pkg

**To Reproduce**

Use this as a custom transport in logConfig:

```
const rotationTransportation = new winston.transports.File({
  filename: './zwave/logs/zwave.log',
  maxsize: 5*1000000,
  maxFiles: 5
})
```

**Logfile:**

[zwave.log](https://github.com/zwave-js/node-zwave-js/files/6195910/zwave.log)

**Comment by AlCalzone** [comment]
The loggers were refactored in 7.0.0. As a result, part of the `format` is defined on the loggers and part of it is needs to be defined on the transports now. If you don't need to do anything special, you can use the default format for the transports like this:

```ts
import { createDefaultTransportFormat } from "@zwave-js/core";

const rotationTransportation = new winston.transports.File({
	filename: "./zwave/logs/zwave.log",
	maxsize: 5 * 1000000,
	maxFiles: 5,
	format: createDefaultTransportFormat(false, false),
});
