### ISSUE TITLE
After system reboot some binary sensor HA entities are changed

### ISSUE THREAD

**Issue by jaimevisser** [zwave-js/zwave-js#2157]
Running HA and ZwaveJsToMqtt docker containers with a AeonLabs z-stick.

After rebooting my server the motion detectors on my AeonLabs multisensors (usb/mains powered, not sleeping) report their motion sensors unavailable. A new "any" sensor has appeared that seems to report motion now.

![Capture](https://user-images.githubusercontent.com/3132806/112438905-bf34c380-8d48-11eb-853e-49b8f6e3bef3.PNG)

The same is happening on battery powered Neo Coolcam door/window sensors.

**Comment by AlCalzone** [comment]
Please fill out the issue template (and follow it). We cannot act on just a screenshot.
