### ISSUE TITLE
Fibaro FGRGBWM-441 - Missing state

### ISSUE THREAD

**Issue by 0rsa** [zwave-js/zwave-js#2158]
Hello,

If I change the value of a module FGRGBWM-441 (class MultiLevelSwitch), it works but there is no event reporting this change, except for the power consumed.

I get only this event in node-red:
![fibaro](https://user-images.githubusercontent.com/769750/112457334-f365af80-8d5b-11eb-97c4-12bfcc1aa6bf.png)

I have no problem using Fibaro roller shutter using the same class (MultiLevelSwitch).

What is expected? To get an event with the newValue of module MultiLevelSwitch

**Comment by AlCalzone** [comment]
Please choose an appropriate issue template and fill it out completely when opening an issue. That helps us investigate your issue quicker because all the necessary information is there. Otherwise, the issue will go to the bottom of the pile - and that pile is growing quickly.

**Comment by 0rsa** [comment]
Ok it works if I specify a endpoint when changing the value.
