### ISSUE TITLE
Kwikset 888 alarmType and alarmLevel missing attributes

### ISSUE THREAD

**Issue by cppsse** [zwave-js/zwave-js#2166]
Kiwkset 888 Deadbolt is missing alarmType and alarmLevel attributes.  See issue #1713 ([specifically here](https://github.com/zwave-js/node-zwave-js/issues/1713#issuecomment-808504726))

Similar work was recently done for Kwikset 910, 912, 914 and Yale locks.  The existing merge for the 910, 912, and 914 models should work for the 888.  I used a generic Kwikset template sensor under OZW 1.4 to report on which keypad codes were used.

![Screen Shot 2021-03-26 at 1 56 55 PM](https://user-images.githubusercontent.com/28080250/112693742-5fb8df80-8e3e-11eb-83d3-a51b1b821fad.png)
![Screen Shot 2021-03-26 at 1 57 03 PM](https://user-images.githubusercontent.com/28080250/112693744-60517600-8e3e-11eb-9b88-b14e8bab1b8f.png)

**Comment by AlCalzone** [comment]
Just to be sure that you're not misunderstanding. You're not going to see the alarmType and alarmLevel values if the mapping is applied. Instead zwave-js will emit `"notification"` events and update the lock status for you.

**Comment by acalcutt** [comment]
Hi @AlCalzone , I also have a Kwikset 888 and am trying to move my configuration over to Zwave JS. I am using Z-Wave JS 0.1.16. From what I can tell, the lock statuses are working properly, however "alarmType" and "alarmLevel" still list as unknown. Does you post above mean these values will still not get updated? 
![unknow_type_level](https://user-images.githubusercontent.com/3792408/113326394-9764d300-92e7-11eb-8ada-4c8c6f04e8fd.png)

One thing I used to do with a combination of "alarmType" and "alarmLevel" was figure out which user was entering. When a user entered it would give a alarmLevel of the user associated with the pin (1,2,3...30), and an alarmType of 19 (PIN Unlock). Using the combination of those I could see whos pin was used like this in node red.
![Unlock_User](https://user-images.githubusercontent.com/3792408/113324727-756a5100-92e5-11eb-8c90-02c99a7c3784.png)

With "alarmType" and "alarmLevel" still listed as unknown, I'm not sure I see any way to do something similar. If they were just exposed I could still use something like my node red setup to fill the gap. Unless there is something that can be done to catch the last user with the "alarmType" (19) and "alarmLevel" (number associated with the user)  and emit a notification for that.

**Comment by AlCalzone** [comment]
We have a mapping defined for the Kwikset 888 - you'll receive events (I think HA calls them zwavejs_event) which specify that a `RF (Un)lock` happened and which includes the user ID as a parameter.

**Comment by acalcutt** [comment]
Thanks, based on your comment I was able get something working with the "zwave_js_event" In node red I was able to listen to "zwave_js_event" with an "Events All" node. Once I had that I looked for a payload with "Keypad unlock operation" at $msg.payload.event.label and like you mentioned the UserID was there in the payload at $msg.payload.event.parameters.userId

My updated node red looks like this
![zwave_js_event_node_red](https://user-images.githubusercontent.com/3792408/113350061-f128c580-9306-11eb-8e09-958e8bef59be.png)

 thanks for your help, I think watching "zwave_js_event" should be fine

EDIT: I ended up throwing in a device_id check in case I ever get another lock. I was also able to use some other event labels ("Manual lock operation" and  "Manual unlock operation") and it all seemed to work great. thanks again

**Comment by acalcutt** [comment]
@AlCalzone I will say I found one issue with the lock status. This lock has a feature where the lock automatically locks after X seconds. When the lock automatically locks itself, it does not get updated in hass.io (it still shows "lock", like it is unlocked). 

I can see it does send a "Auto lock locked operation" event but the status doesn't change in hass. I had this problem with my old configuration, so right now I am just doing like I did then... if I see a "Auto lock locked operation" event I am just calling the lock.lock service (telling hass to lock even though the lock is already locked, which updates the status...which is a hack but works)
![auto_locked](https://user-images.githubusercontent.com/3792408/113358645-2be52a80-9314-11eb-93c0-1c6ac6a36172.png)

**Comment by AlCalzone** [comment]
I think that's already fixed on master but not released yet

**Comment by cweakland** [comment]
Would it be possible to add alarmtype 161 "Bad Code Entered" to the list of notifications?

**Comment by AlCalzone** [comment]
I'll need to check but AFAIK there is no direct translation to Notification CC events for this. In that case you should have the alarm values to work with though.

**Comment by AlCalzone** [comment]
Yep, I remembered correctly. The V2 notifications distinguish between trying to lock and trying to unlock with an invalid user code. I assure you that if we map it to one of them, there will be reports that someone wants to have the other mapping.

So I'm not going to map either and let everyone decide themselves.
