### ISSUE TITLE
Configuration queries timing out

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#2204]
The numbers in the brackets are the config param numbers - it is likely that they don't exist on the given firmware.

Node 26 (7, 8) - Zooz ZEN22 Dimmer v2, Manuaf. ID 634, Prod Type: 45330, Prod. ID 7964,  Firmware 1.7
Node 27 (7, 8) - Zooz ZEN22 Dimmer v2, Manuaf. ID 634, Prod Type: 45330, Prod. ID 7964,  Firmware 1.7
Node 29 (7, 8) - Zooz ZEN22 Dimmer v2, Manuaf. ID 634, Prod Type: 45330, Prod. ID 7964,  Firmware 1.7
Node 39 (7, 8) - Zooz ZEN22 Dimmer v2, Manuaf. ID 634, Prod Type: 45330, Prod. ID 7964,  Firmware 1.7
Node 40 (7, 8) - Zooz ZEN22 Dimmer v2, Manuaf. ID 634, Prod Type: 45330, Prod. ID 7964,  Firmware 1.7
Node 41 (7, 8) - Zooz ZEN22 Dimmer v2, Manuaf. ID 634, Prod Type: 45330, Prod. ID 7964,  Firmware 1.7
Node 51 (132, 137, 185) - Trane XR524 Thermostat,  Manuaf. ID 139, Prod Type: 21586, Prod. ID 21570,  Firmware 1.30
Node 58 (9, 10) - Zooz ZEN21 Dimmer v2, Manuaf. ID 634, Prod Type: 45329, Prod. ID 7708,  Firmware 3.0
Node 38 (2, 250) - AEON Labs Micro Switch G2 DSC26103-ZW, Manuaf. ID 134, Prod Type: 3, Prod. ID 26,  Firmware 2.14

**Comment by blhoward2** [comment]
Zooz ZEN22: Parameter 7 is incorrect but 8 looks like it was added in v.1.07 (https://www.support.getzooz.com/kb/article/297-zen22-dimmer-change-log/)

Trane XR524 (terrible documentation, looks like users have reverse engineered parameters over time):
- 132: Not documented anywhere, could be write-only but I can't verify it exists at all - deleting
- 137: Not documented anywhere, could be write-only but I can't verify it exists at all - deleting
- 185: This would purport to do the same thing as 132. Can't find documented anywhere - deleting

Zooz ZEN21: Parameters added in v3.1. Condition added. Will combine these when I do the Zooz folder.

Aeon Micro Switch G2: Confirmed with Aeotec that parameter 2 should be write only. Fixed.
