### ISSUE TITLE
Notification events for keypad unlock events not including a userId when firing for Yale YRD110 lock

### ISSUE THREAD

**Issue by raman325** [zwave-js/zwave-js#2206]
**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I am **not** using ZWaveJS2MQTT. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog and my problem was **not** mentioned there.

**Describe the bug**

I am posting this on behalf of another user (@PrayerDropful) due to two other tickets they opened:
https://github.com/FutureTense/keymaster/issues/145
https://github.com/home-assistant/core/issues/48543

The gist is that they updated to `zwave-js 7.0.1` via `zwave-js-server 1.3.0` and they are now receiving events for lock and unlock events, but they do not include the `userId` parameter as expected. I tested this with my Schlage BE469 lock which already supported Notification events and I can see the `userId`, so I suspect the issue lies in the mapping logic introduced here: https://github.com/zwave-js/node-zwave-js/pull/2045

Here's the event we fire in Home Assistant. We blindly pass the parameters dictionary to the Home Assistant event
```json
{
    "event_type": "zwave_js_event",
    "data": {
        "type": "notification",
        "domain": "zwave_js",
        "node_id": 63,
        "home_id": 4172338759,
        "device_id": "bedc99ab52b31dc30915eb5ce6e18d2f",
        "label": "Keypad unlock operation",
        "parameters": {}
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-31T19:58:53.500648+00:00",
    "context": {
        "id": "fe98e38617eef0de785ff341b6fc289c",
        "parent_id": null,
        "user_id": null
    }
}
```

Here's the keypad lock event for my Schlage lock:
```json
{
    "event_type": "zwave_js_event",
    "data": {
        "type": "notification",
        "domain": "zwave_js",
        "node_id": 23,
        "home_id": 3601639587,
        "device_id": "1cd7780d78d799dc3a8387cbe55db356",
        "label": "Keypad lock operation",
        "parameters": {
            "userId": 1
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-31T20:46:32.341089+00:00",
    "context": {
        "id": "f8fc6e2b4a85b16ff50909bc77ae91a6",
        "parent_id": null,
        "user_id": null
    }
}
```

**Device information**

Which device(s) is/are affected (make/model)?  
What are the node IDs?

**Did you change anything?**
- [ ] **Yes**: *(please describe)*
- [x] **No**

**Did this use to work before?**
- [ ] **Don't know**, this is a new device
- [x] **No**, it never worked anywhere
- [ ] **Yes**, in: *(specify application with versions)*
    
**How are you using `node-zwave-js`**
- [ ] `zwavejs2mqtt` (latest) docker image
- [ ] `zwavejs2mqtt` (dev) docker image
- [ ] `zwavejs2mqtt` Manual Docker build
    - `node-zwave-js` branch: 
    - `zwavejs2mqtt` branch: 
- [ ] ioBroker.zwave2 adapter
- [x] `HomeAssistant` version 2021.3.4
- [ ] Pkg
- [ ] Manual Docker build
    - `node-zwave-js` branch: 
    - `zwavejs2mqtt` branch: 
- [ ] `node-red-contrib-zwave-js`
    - Module version (double click node): 
- [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github)) 
- [ ] Other: 

**To Reproduce**

Lock or Unlock a Yale YRD110 with the keypad and check the event that fires.

**Additional context**

**Logfile:**

**Comment by xhemp** [comment]
This is happening to the Yale Conexis L1 as well.
