### ISSUE TITLE
Incorrect device config for ZWN-RSM2-PLUS

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#2280]
https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/devices/0x011a/zwn-rsm2.json
https://github.com/zwave-js/zwavejs2mqtt/discussions/985#discussioncomment-568172

- 0x011a:0x0111:0x0606 is called ZWN-RSM2-PLUS
- Association groups 2/3 (Switch Binary Report EP1 / 2) need to be auto-assigned

**Comment by floatiepen** [comment]
If any more logs or info are needed from me, I'm happy to provide more details.
