### ISSUE TITLE
Philio Tech PAN04-1B switch not reporting status in ZwaveJS

### ISSUE THREAD

**Issue by quizzical86** [zwave-js/zwave-js#2290]
@AlCalzone already explained on discord the input he needed for this issue. I'm now putting this same information in Github as I  assume it is more appropriate to log it here.

I have migrated a Philio Tech PAN04-1B ([link to zwave JS config DB](https://devices.zwave-js.io/?jumpTo=0x013c:0x0001:0x0003:0.0);  [link to manual](https://www.zwavetaiwan.com.tw/s/PAN04-manual-20181015-1.pdf)) from my old home automation solution to Home Assistant and ZwaveJS.

Trouble is that in Z-waveJS it doesn't report it's status when I manually click the light switch (it does when I turn on/off the light in Home Assistant). 

@AlCalzone and [this forum post](https://community.home-assistant.io/t/philo-pan04-problem/189800/2?u=quizzical) already hinted to the need to manually add associations so that group 2 and 3 point at the controller.

I have set an association to NodeID_1 for Load1 and Load2 using ZwaveJS2MQTT but that didn't solve the problem.

With these changes, the logs show [these reports](https://paste.ubuntu.com/p/tcPRSNpCky/) being sent when physically turning off one of the lights and [these reports](https://paste.ubuntu.com/p/5RwsZQBxKG/) when physically turning on that same light.

Here is the [homeid.json file](https://paste.ubuntu.com/p/YVqsdVx7Tb/)  and here is the [homeid.values.jsonl file](https://paste.ubuntu.com/p/TFy2j24k3N/).

This is all the information @AlCalzone asked for (and I produced it using the ZwaveJS2MQTT addon) but here is also the JSON dump which I produced using the ZwaveJS addon:
[zwave_js_dump.zip](https://github.com/zwave-js/node-zwave-js/files/6288045/zwave_js_dump.zip)

**Comment by AlCalzone** [comment]
Hmm - seems like the device doesn't want to tell us **which** load was switched. I think the only way to get the actual status is to poll the values for endpoint 1/2 status whenever the value on endpoint 0 is changed.

To get these endpoint 0 values to exist, you'll need to edit the config file. Take the one I attached, and mount it as `/???/node_modules/@zwave-js/config/config/devices/0x013c/pan04.json` into the container (I am not sure what the first part of the path is in HA).
Afterwards, re-interview the device.

[pan04.json.txt](https://github.com/zwave-js/node-zwave-js/files/6288646/pan04.json.txt)

**Comment by quizzical86** [comment]
@AlCalzone thank you.
As zwavejs doesn't allow re-interviewing the node I installed this file also in zwavejs2mqtt.
I reinterviewed the node using zwavejs2mqtt.

The change you did to the file is:
```
	"compat": {
		"preserveRootApplicationCCValueIDs": true
	}
```

I understand from what you write that this should somehow give me new values, but I didn't see any changes in what's available in zwavejs2mqtt.

EDIT: I guess this is more useful to you than the files below: here is the debug info zwavejs2mqtt provides for this node:
[debug info.txt](https://github.com/zwave-js/node-zwave-js/files/6289566/debug.info.txt)


Not sure you need it but just in case I attach here some logs (I have described for each report what action I took in terms of turning on or off a light):
[zwavejs.log](https://github.com/zwave-js/node-zwave-js/files/6289530/zwavejs.log)

I also attach instructions in case ever usefull for someone else how to get new device config files into zwavejs or zwavejs2mqtt (for me this was quite challenging):
[instructions to install zwave device config file into zwavejs or zwavejs2mqtt addon.txt](https://github.com/zwave-js/node-zwave-js/files/6289533/instructions.to.install.zwave.device.config.file.into.zwavejs.or.zwavejs2mqtt.addon.txt)

**Comment by quizzical86** [comment]
I'm wondering whether the fact that it doesn't say which load was switched isn't related to this configuration parameter described in the manual:
![image](https://user-images.githubusercontent.com/75372713/114265128-61160a80-99ef-11eb-8c89-d7dba39a92b5.png)
And then there's also this configuration parameter:
![image](https://user-images.githubusercontent.com/75372713/114265167-a33f4c00-99ef-11eb-8b0d-e67672381e2b.png)

**Comment by AlCalzone** [comment]
Ohhh. I missed the last parameter there. That looks good, can you select the multi channel option?

**Comment by quizzical86** [comment]
When we discussed yesterday on Discord I mentioned that z-wavejs and z-wavejs2mqtt do not have the configuration parameter for this defined. 
I've tried to set this manually in home assistant in the developers tools panel using zwave_js.set_config_parameter with parameter 31, value 2 and bitmask 1, but I' not sure whether that is the correct way of doing it.

**Comment by AlCalzone** [comment]
Leave out the bitmask, just set parameter 31 to value 2

**Comment by quizzical86** [comment]
When I launch the following service call:
```
service: zwave_js.set_config_parameter
target:
  entity_id: switch.licht_kelder_beide
data:
  parameter: '31'
  value: '2'
```
The log shows the error:
"Unexpected error for call_service at pos 1: Configuration parameter with value ID 22-112-0-31 could not be found"

Does that mean that I can't set any parameters that have not been defined in the Z-wave JS config DB?

**Comment by AlCalzone** [comment]
Not entirely sure about HA. You could try defining the new config parameter in your mounted file and try with that.

**Comment by quizzical86** [comment]
OK I have guessed a bit how to do that and confirm that with this file it's working (also power consumption).
[pan04NEW.json.txt](https://github.com/zwave-js/node-zwave-js/files/6289927/pan04NEW.json.txt)
What is the next step now to get this fix in zwavejs for everyone?
Other's will probably still have difficulties finding out they need to change this default configuration parameter to get it working in z-waveJS, but I guess there's no way for zwavejs to override the default setting.

**Comment by AlCalzone** [comment]
@blhoward2 what do you think? Should we add something to our device files under metadata to mention known quirks?

I'm hesitant to change the configuration on users' devices by default, but we could at least mention it.

**Comment by quizzical86** [comment]
This would for example also be usefull for the Aeotec Smart switch 6, where Basic CC is disabled by default. The result is that if a user pushes the little button on this power plug to turn it on, ZwaveJS won't get notified. I guess allmost all users will want to turn this on and mentioning it as a known quirk would be helpfull. “Send Automatic Reports When Exceeding Thresholds” is also disabled by default and i had to turn this on to get power consumption information.

**Comment by blhoward2** [comment]
What makes you believe this would apply to the Aeotec device? It doesn't have this parameter and we don't disable the Basic CC we map it usually. You should open your own issue so we can take a look.

**Comment by quizzical86** [comment]
Perhaps I wasn't clear enough. I was just illustrating how AlCalzone's suggestion to have a place where users can read about known quirks can be usefull. This Philip Tech device clearly has a quirk that is worth flagging to the user, and I was trying to illustrate it is not the only case as the aeotec also has some quirks that are worth flagging to the user.

**Comment by quizzical86** [comment]
OK well it was just a suggestion, in any case it is crystal clear that there's a crucial configuration parameter missing for this device and this configuration file adds it (https://github.com/zwave-js/node-zwave-js/files/6289927/pan04NEW.json.txt) so could we include this in zwaveJS so that at least the smart people (who can figure out they need to change the default value of this parameter without having read it in a 'known quirks' section) can use this z-wave device?

**Comment by AlCalzone** [comment]
Yeah, that makes sense!

**Comment by blhoward2** [comment]
I misread your post. I thought you meant to add the parameter to the Aeotec file. I'm fine with describing quirks.

**Comment by AlCalzone** [comment]
@quizzical86 are you sure about the parameter number 11? The manual says this is parameter 31.
![grafik](https://user-images.githubusercontent.com/17641229/114620007-6a330000-9cab-11eb-971a-178637ce8df0.png)

**Comment by quizzical86** [comment]
No I'm not. This is a mistake on my side, it should indeed be parameter 31. However, what is very strange: I double checked and indeed I have configured it incorrectly with parameter 11 and yet this really solved my problem:

```
    {
      "id": "22-112-0-11",
      "nodeId": 22,
      "commandClass": 112,
      "commandClassName": "Configuration",
      "endpoint": 0,
      "property": 11,
      "propertyName": "Select Auto Report Type",
      "type": "number",
      "readable": true,
      "writeable": true,
      "label": "Select Auto Report Type",
      "default": 1,
      "stateless": false,
      "min": 0,
      "max": 255,
      "list": true,
      "allowManualEntry": false,
      "states": [
        {
          "text": "Basic type",
          "value": 1
        },
        {
          "text": "Multichannel type",
          "value": 2
        }
      ],
      "value": 2,
      "lastUpdate": 1618349712195,
      "newValue": 2
    },
```

I have no explanation how this is possible, this device is not even supposed to have a parameter 11.

**Comment by AlCalzone** [comment]
WTF... Maybe it does have both parameters. Anyways - I've merged it with parameter 31. Once the update is available, can you please test if the device reacts to that param too?

**Comment by quizzical86** [comment]
OK but my device which wasn't working is now working (with a non-existing parameter 11 set to "2").
Does that mean that to be able to test the new version you will be releasing I should:
1: remove the device from the network
2: factory reset it
3: add it back to the network and set the parameter 31 which you added
?

**Comment by AlCalzone** [comment]
Yeah you can do that to make sure parameter 31 exists and is working.

**Comment by quizzical86** [comment]
I removed the device from the network reset the device multiple times and then added it back.
Either my resets were unsuccesful or the reset does not restore the parameters to factory defaults, since some parameters I had set did not go back to default and in addition my device works perfectly which probably indicates the multichannel parameter is still set.
So I don't seem able to do tests whether using parameter 31 (as specified in the manual) also works; unless there's another way to undo the fact that I have changed the non-existing parameter 11.

**Comment by quizzical86** [comment]
I knew I shouldn't have touched it while it was working perfectly :'-(
I wanted to test it for the good of others who use this device. So I downloaded the new file you created (the latest version is not yet available in home assistant) and installed it manually. Removed the z-wave device, did my best to reset it (not completely sure I succeeded but tried many many times) and then added it back.

So now the situation is that only Endpoint 3 (this is a virtual entity that controls both switches in the Z-wave device at the same time and can also show the sum of the wattage used by both lights) is updated.
So when I physically click the switch to turn on light 1 or light 2, this shows in this endpoint 3 (both in terms of the on/off status and the wattage) but does not show in Z-waveJS for the light in question.

Going back to the file I created (with the incorrect parameter 11, but which did solve my problem at the time) gives me the same result.

This is super frustrating as I had just gotten all my automations that are based on these lights working :-s
I have tried for many hours but can't find a way to get my device back to working condition :-(

**Comment by AlCalzone** [comment]
What are your current configuration settings and associations?

**Comment by quizzical86** [comment]
My heart skipped a beat I think when you posted this reply!
Because z-waveJS in home assistant doesn't support associations I had forgotten about that.
I fired up ZwaveJS2MQTT and set an association to NodeID_1 for Load1 and Load2.
Now it's working again :)
So if we add a 'known quirks' it should definitely include the need to set these associations for stupid people like me.

So I conclude that through some black magic this device accepts both parameter 11 and parameter 31 and the result is the same in both cases. 
And the more important conclusion is that your new configuration file for this device works well if the user subsequently implements the known quirks of changing the default value of parameter 31 and sets the associations for Load1 and Load2 (using ZwaveJS2MQTT).

**Comment by AlCalzone** [comment]
> So I conclude that through some black magic this device accepts both parameter 11 and parameter 31 and the result is the same in both cases.

Might be that they realized their typo too late and subsequently changed the firmware to match 🤷🏻‍♂️

**Comment by gratjetost** [comment]
Same Issue with the PAN06 switch from Philio. older version of the PAN04. Can this be fixed too? I cannot get it managed by myself.

**Comment by blhoward2** [comment]
Don't comment on a closed issue. Open a new one and reference this issue number if need be.
