### ISSUE TITLE
[bug]Zooz Zen20 powerstrip not being queried 

### ISSUE THREAD

**Issue by faspina** [zwave-js/zwave-js#2334]
🚨🚨🚨 STOP! STOP! STOP! 🚨🚨🚨
  Before opening an issue, please read and follow these steps:

  1. Are you using HomeAssistant?
Yes but the problem is with one devices , converting from zwave2mqtt docker to zwavejs2mqtt docker  

  2. Check the troubleshooting section if your problem is described there:
  https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report
Did this 

  🙏🏻🙏🏻🙏🏻 Thanks, now onto your issue:
-->

### Version

zwavejs/zwavejs2mqtt:latest docker 

Log error for the Zen20 zooz powerstrip
2021-04-13T15:38:35.139Z CNTRLR [Node 056] Timed out while waiting for a response from the node
2021-04-13T15:38:35.154Z CNTRLR [Node 056] Interviewing Multi Channel... [Endpoint 1]
2021-04-13T15:38:35.155Z CNTRLR » [Node 056] Querying endpoint count for CommandClass Binary Switch...
2021-04-13T15:38:35.155Z CNTRLR [Node 056] Error during node interview: This virtual node (Endpoint 1) does not support the command GetV1!

Build/Run method

- [X ] Docker

zwavejs2mqtt version: 3.2.1
zwave-js version: 7.2.2

### Describe the bug

moveng to ZwaveJS all device queried except the Zoos Zen20 I get the error above in the log. 
[zwavejs2mqtt.log](https://github.com/zwave-js/node-zwave-js/files/6305013/zwavejs2mqtt.log)
[node_56.txt](https://github.com/zwave-js/node-zwave-js/files/6305016/node_56.txt)

**Comment by AlCalzone** [comment]
@faspina I need the `zwave-js` logfile, not the one from `zwavejs2mqtt`. Best if you re-interview the device and capture a log of that.

**Comment by faspina** [comment]
[zwavejs_1.log](https://github.com/zwave-js/node-zwave-js/files/6305157/zwavejs_1.log)

**Comment by AlCalzone** [comment]
Ok thanks, I think I found it.
