### ISSUE TITLE
[bug] Controller has no neighbours after updating to zwave-js 7.0.0

### ISSUE THREAD

**Issue by andras-tim** [zwave-js/zwave-js#2335]
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt: 3.2.0
zwave-js: 7.1.1

but the bug cames with:

zwavejs2mqtt: 3.0.0
zwave-js: 7.0.0

### Describe the bug

![screencapture-core-tia-8091-mesh-2021-04-10-20_37_08](https://user-images.githubusercontent.com/619016/114281079-95fc7e80-9a3c-11eb-82e6-9af7a96aaf1b.png)
(took on v3.0.0)

### To Reproduce

1 Upgrade from [v2.4.1 (0a723f9)](https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v2.4.1) to [v3.0.0 (b48c1f7)](https://github.com/zwave-js/zwavejs2mqtt/releases/tag/v3.0.0)

### Expected behavior

![screencapture-core-tia-8091-mesh-2021-04-10-20_44_10](https://user-images.githubusercontent.com/619016/114281238-90ebff00-9a3d-11eb-951c-918ff5ca9dfb.png)
(took on v2.4.1)

### Additional context

In general, I use HA, but when I add/remove node I always turn off that to avoid unwanted states/nodes... e.g. when I add a new node, I always rename that, but the HA remembers the original ids...

[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/6290565/zwavejs2mqtt.log)
[zwavejs_1.log](https://github.com/zwave-js/zwavejs2mqtt/files/6290566/zwavejs_1.log)

**Comment by AlCalzone** [comment]
If you can easily revert, then I'd be interested in another heal log from 2.4.1. From what I've seen, your stick immediately responds to the commands that tell it to update the nodes' neighbors with "cannot do that". I can't imagine that the zwave-js version has anything to do with that.

**Comment by AlCalzone** [comment]
Anything new?

**Comment by andras-tim** [comment]
Sorry, I had personal issues. I'm going to reply this weekend.

**Comment by AlCalzone** [comment]
Still waiting for any info to narrow this down 🤷🏻‍♂️

**Comment by DayRunner131** [comment]
@AlCalzone, I started following this bug thread after I started having the same issue. Been working with @robertsLando on the ZwaveJS2MQTT side with issue https://github.com/zwave-js/zwavejs2mqtt/issues/739. Could be on the ZwaveJS side? Maybe an issue with how HassOS boots the Raspi and thus the controller?

I followed your recommendations from an earlier post;

> Stop the container
shut down the host
pull the stick
wait a few seconds
put the stick back in
start everything
wait until zwave-js has booted completely
heal

My notes:

1) Something is happening during the HassOS boot where the controller is being bogged down by excessive node messages. I have 4x Zooz 4in1 motion sensors that will send motion/temp/humidity messages non-stop during/after boot which prevents the controller from polling the other nodes. Upon startup, I'd find almost all other nodes missing info, and no communication with the controller.
2) In this state, when a Heal is attempted, it's unsuccessful and fails to bring back missing node information. I found that if I removed the batteries from the 4x Zooz 4in1 sensors to relieve the network congestion, the heal process could begin. Since I have a total of 12 nodes, once the first 8 nodes healed, I would install the battery on each 4in1 one at a time till I could see the node heal. Ultimately, after spending almost an hour trying to heal the last 4in1 node, I gave up. The Zwave network again seemed bogged down.
3) During my second reboot and reheal attempt I did the following, removed the batteries from the four 4in1 motion detectors and the zooz multisiren. Viola, after reboot, the controller saw all nodes immediately except for the ones with the batteries removed. I then started a heal process, 7 nodes healed quickly, installed the batteries in the multisiren and it healed. Then I restarted each 4in1 multisensor one at a time and they healed quickly.
4) The unfortunate kicker, after this successful heal of all 12 nodes, **I still have a flatlined network with no neighbors.**

Setup:
-RASPI 4 8GB running HA OS 64bit v5.03
-240GB Kingston mSATA running on a DGZOMYTEK mSATA to USB 3.1 Gen2 10GBPS SSD
-Zooz Z-Wave Plus S2 USB Stick ZST10
-supervisor-2021.04.3
-core-2021.4.6

The good news is that I was running my debug logs on silly during this whole shutdown, disconnect, reconnect, reboot, heal, repeat. You should have a great record of everything I saw an hopefully will be able to see where the issue is coming from with this network flatline. Perhaps it's happening during the boot sequence when the controller is listening to nodes prior to fully loading?

[zwavejs2mqtt-store (5).zip](https://github.com/zwave-js/node-zwave-js/files/6424021/zwavejs2mqtt-store.5.zip)
[zwave_js_dump (2).json.txt](https://github.com/zwave-js/node-zwave-js/files/6424030/zwave_js_dump.2.json.txt)
[nodes_dump (1).json.txt](https://github.com/zwave-js/node-zwave-js/files/6424032/nodes_dump.1.json.txt)

**Comment by AlCalzone** [comment]
@DayRunner131 it would be interesting to see the first few lines of the log when the controller itself is interviewed. To do that, you need to edit the `<homeid>.json` file in the cache while the driver is not running. That file should start with 
```
{
    "nodes": {
        "1": {
            "id": 1,
            "interviewStage": "Complete",
```
Delete the line with "interviewStage", save and start zwavejs2mqtt. You should now see lines like
```
23:34:13.289 DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                      ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                        ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                       ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                      ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                      ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝

...

23:34:15.590 CNTRLR   [Node 001] Beginning interview - last completed stage: None
23:34:15.591 CNTRLR   [Node 001] new node, doing a full interview...
23:34:15.591 CNTRLR » [Node 001] querying protocol info...
...
23:34:15.674 CNTRLR « [Node 001]   node neighbors received: 7, 15, 17
...
23:34:15.676 CNTRLR   [Node 001] Interview completed
```
in the log. I'll need to see everything from that first log until `[Node 001] Interview completed`


I think the problem here is that the controller stick reports no neighbors, but the network map drawing code relies on that.

**Comment by DayRunner131** [comment]
@AlCalzone, hmm. Let me see if I can find this in the HassOS/Supervisor instance and get back to you.

To clarify what you want, I can just shut down ZwaveJS2MQTT in the Supervisor. Edit this file, then restart and copy the logs?

**Comment by AlCalzone** [comment]
> I can just shut down ZwaveJS2MQTT in the Supervisor. Edit this file, then restart and copy the logs?

If that's possible, yes. I know the Docker stuff makes simple changes like this unnecessarily complicated.

**Comment by DayRunner131** [comment]
@AlCalzone @robertsLando, Having difficulty locating the filepath in HassOS where this file may exist. Any help with the location would speed this along.

**Comment by dkmcgowan** [comment]
in your supervisor go to Store in the control panel ui, and you will see the json file there, I'm not sure how to stop it, edit it, then start it again though, because if you stop it you cannot save it from the store, maybe save it, stop really quick and start again...  also, I have this same issue, I only have 2 test nodes right now so I was going to try a hard reset on the controller and see what happens

**Comment by DayRunner131** [comment]
> in your supervisor go to Store in the control panel ui, and you will see the json file there, I'm not sure how to stop it, edit it, then start it again though, because if you stop it you cannot save it from the store, maybe save it, stop really quick and start again... also, I have this same issue, I only have 2 test nodes right now so I was going to try a hard reset on the controller and see what happens

Sorry, not seeing this in the add-on store. Only see Repositories, Reload, Registries in the upper right corner. None of which allow me to edit files.

Opened a HA Community issue for this: https://community.home-assistant.io/t/zwave2mqtt-supervisor-add-ons-filepath/305268

**Comment by dkmcgowan** [comment]
sorry, go to your z-wave js control panel, either from the HA sidebar or go to the add-on and load the web ui, once inside the control panel click the top left menu button, inside the control panel, same place where you see settings, you will see an option inside the z-wave control panel for store, from there you will see a list of files, one of the files will be the <homeid>.json, will look something like d23845ac.json

**Comment by andras-tim** [comment]
> Still waiting for any info to narrow this down 🤷🏻‍♂️

Hi @AlCalzone, sorry again for the long skip.

Here is the wanted debug info (fresh pc start + dongle plug + container start + healing):
* v2.1.2 (OK):
  * [2.1.2-a_ok_zwavejs2mqtt-store.zip](https://github.com/zwave-js/node-zwave-js/files/6424194/2.1.2-a_ok_zwavejs2mqtt-store.zip)
  * [2.1.2-b_ok_zwavejs2mqtt-store.zip](https://github.com/zwave-js/node-zwave-js/files/6424195/2.1.2-b_ok_zwavejs2mqtt-store.zip)
* v2.4.1 (OK):
  * [2.4.1_ok_zwavejs2mqtt-store.zip](https://github.com/zwave-js/node-zwave-js/files/6424196/2.4.1_ok_zwavejs2mqtt-store.zip)

**Comment by DayRunner131** [comment]
@AlCalzone using the @dkmcgowan suggestion, these are the logs I generated at silly.

Hope this helps and hopefully the .json file change took.
[zwavejs_356 (3).log](https://github.com/zwave-js/node-zwave-js/files/6424285/zwavejs_356.3.log)

**Comment by andras-tim** [comment]
Wow! It works now... :slightly_smiling_face: 

1. Before I started the investigation I tried **v4.0.1**, but the chart was flat...
2. I stopped the whole machine, pulled out the **Z-Wave.Me** dongle.
3. Started the machine, re-connected the dongle, rolled back my zwave-js env as I wrote before and collect the material in https://github.com/zwave-js/node-zwave-js/issues/2335#issuecomment-832291843
4. After that I switched back to **v4.0.1**, AND NOW everything is working!
5. I tried the reproduction on **v3.2.1** also, but this is working too...


### Maybe helps

What I tried before, w/o success?
* Turn off and on the fuses to "restart" my Qubino stuff
* Restart the container
* Pull out the dongle

What I tried only now?
* added `stop_signal: SIGINT` to my **docker-compose.yml** as I read nowadays
* Restart my PC...

_If the restart was missing for the success, I should say sorry!_

**Comment by dkmcgowan** [comment]
I just removed all devices on my controller and did a hard reset, then I restart container, and then added one device back, but still no neighbors on the controller.  I then removed the line mentioned above and captured the log, but don't see the full interview start

2021-05-04T23:08:59.509Z DRIVER   ███████╗ ██╗    ██╗  █████╗  ██╗   ██╗ ███████╗             ██╗ ███████╗
                                  ╚══███╔╝ ██║    ██║ ██╔══██╗ ██║   ██║ ██╔════╝             ██║ ██╔════╝
                                    ███╔╝  ██║ █╗ ██║ ███████║ ██║   ██║ █████╗   █████╗      ██║ ███████╗
                                   ███╔╝   ██║███╗██║ ██╔══██║ ╚██╗ ██╔╝ ██╔══╝   ╚════╝ ██   ██║ ╚════██║
                                  ███████╗ ╚███╔███╔╝ ██║  ██║  ╚████╔╝  ███████╗        ╚█████╔╝ ███████║
                                  ╚══════╝  ╚══╝╚══╝  ╚═╝  ╚═╝   ╚═══╝   ╚══════╝         ╚════╝  ╚══════╝
2021-05-04T23:08:59.510Z DRIVER   version 7.3.0
2021-05-04T23:08:59.510Z CONFIG   version 7.3.0
2021-05-04T23:08:59.510Z DRIVER   
2021-05-04T23:09:04.823Z CNTRLR   beginning interview...
2021-05-04T23:09:04.824Z CNTRLR   querying version info...
2021-05-04T23:09:04.942Z CNTRLR   received version info:
                                    controller type: Static Controller
                                    library version: Z-Wave 4.05
2021-05-04T23:09:04.942Z CNTRLR   querying controller IDs...
2021-05-04T23:09:04.953Z CNTRLR   received controller IDs:
                                    home ID:     0xe2d2d610
                                    own node ID: 1
2021-05-04T23:09:04.953Z CNTRLR   querying controller capabilities...
2021-05-04T23:09:04.963Z CNTRLR   received controller capabilities:
                                    controller role:     primary
                                    is in other network: false
                                    is SIS present:      true
                                    was real primary:    true
                                    is a SUC:            true
2021-05-04T23:09:04.963Z CNTRLR   querying API capabilities...
2021-05-04T23:09:04.975Z CNTRLR   received API capabilities:
                                    serial API version:  4.32
                                    manufacturer ID:     0x00
                                    product type:        0x01
                                    product ID:          0x01
                                    supported functions: 
                                    · GetSerialApiInitData (0x02)
                                    · FUNC_ID_SERIAL_API_APPL_NODE_INFORMATION (0x03)
                                    · ApplicationCommand (0x04)
                                    · GetControllerCapabilities (0x05)
                                    · SetSerialApiTimeouts (0x06)
                                    · GetSerialApiCapabilities (0x07)
                                    · FUNC_ID_SERIAL_API_SOFT_RESET (0x08)
                                    · UNKNOWN_FUNC_UNKNOWN_0x09 (0x09)
                                    · UNKNOWN_FUNC_RF_RECEIVE_MODE (0x10)
                                    · UNKNOWN_FUNC_SET_SLEEP_MODE (0x11)
                                    · FUNC_ID_ZW_SEND_NODE_INFORMATION (0x12)
                                    · SendData (0x13)
                                    · SendDataMulticast (0x14)
                                    · GetControllerVersion (0x15)
                                    · SendDataAbort (0x16)
                                    · FUNC_ID_ZW_R_F_POWER_LEVEL_SET (0x17)
                                    · UNKNOWN_FUNC_SEND_DATA_META (0x18)
                                    · FUNC_ID_ZW_GET_RANDOM (0x1c)
                                    · GetControllerId (0x20)
                                    · UNKNOWN_FUNC_MEMORY_GET_BYTE (0x21)
                                    · UNKNOWN_FUNC_MEMORY_PUT_BYTE (0x22)
                                    · UNKNOWN_FUNC_MEMORY_GET_BUFFER (0x23)
                                    · UNKNOWN_FUNC_MEMORY_PUT_BUFFER (0x24)
                                    · UNKNOWN_FUNC_FlashAutoProgSet (0x27)
                                    · UNKNOWN_FUNC_UNKNOWN_0x28 (0x28)
                                    · UNKNOWN_FUNC_NVMGetId (0x29)
                                    · UNKNOWN_FUNC_NVMExtReadLongBuffer (0x2a)
                                    · UNKNOWN_FUNC_NVMExtWriteLongBuffer (0x2b)
                                    · UNKNOWN_FUNC_NVMExtReadLongByte (0x2c)
                                    · UNKNOWN_FUNC_NVMExtWriteLongByte (0x2d)
                                    · GetNodeProtocolInfo (0x41)
                                    · HardReset (0x42)
                                    · FUNC_ID_ZW_REPLICATION_COMMAND_COMPLETE (0x44)
                                    · FUNC_ID_ZW_REPLICATION_SEND_DATA (0x45)
                                    · AssignReturnRoute (0x46)
                                    · DeleteReturnRoute (0x47)
                                    · RequestNodeNeighborUpdate (0x48)
                                    · ApplicationUpdateRequest (0x49)
                                    · AddNodeToNetwork (0x4a)
                                    · RemoveNodeFromNetwork (0x4b)
                                    · FUNC_ID_ZW_CREATE_NEW_PRIMARY (0x4c)
                                    · FUNC_ID_ZW_CONTROLLER_CHANGE (0x4d)
                                    · FUNC_ID_ZW_SET_LEARN_MODE (0x50)
                                    · AssignSUCReturnRoute (0x51)
                                    · FUNC_ID_ZW_REQUEST_NETWORK_UPDATE (0x53)
                                    · SetSUCNodeId (0x54)
                                    · DeleteSUCReturnRoute (0x55)
                                    · GetSUCNodeId (0x56)
                                    · UNKNOWN_FUNC_SEND_SUC_ID (0x57)
                                    · FUNC_ID_ZW_EXPLORE_REQUEST_INCLUSION (0x5e)
                                    · RequestNodeInfo (0x60)
                                    · RemoveFailedNode (0x61)
                                    · IsFailedNode (0x62)
                                    · ReplaceFailedNode (0x63)
                                    · UNKNOWN_FUNC_UNKNOWN_0x66 (0x66)
                                    · UNKNOWN_FUNC_UNKNOWN_0x67 (0x67)
                                    · UNKNOWN_FUNC_UNKNOWN_0x78 (0x78)
                                    · GetRoutingInfo (0x80)
                                    · UNKNOWN_FUNC_LOCK_ROUTE_RESPONSE (0x90)
                                    · UNKNOWN_FUNC_GET_PRIORITY_ROUTE (0x92)
                                    · UNKNOWN_FUNC_SET_PRIORITY_ROUTE (0x93)
                                    · UNKNOWN_FUNC_UNKNOWN_0x98 (0x98)
                                    · UNKNOWN_FUNC_UNKNOWN_0xB4 (0xb4)
                                    · UNKNOWN_FUNC_WATCH_DOG_ENABLE (0xb6)
                                    · UNKNOWN_FUNC_WATCH_DOG_DISABLE (0xb7)
                                    · UNKNOWN_FUNC_WATCH_DOG_KICK (0xb8)
                                    · UNKNOWN_FUNC_UNKNOWN_0xB9 (0xb9)
                                    · UNKNOWN_FUNC_RF_POWERLEVEL_GET (0xba)
                                    · UNKNOWN_FUNC_GET_LIBRARY_TYPE (0xbd)
                                    · UNKNOWN_FUNC_SEND_TEST_FRAME (0xbe)
                                    · UNKNOWN_FUNC_GET_PROTOCOL_STATUS (0xbf)
                                    · UNKNOWN_FUNC_UNKNOWN_0xD2 (0xd2)
                                    · UNKNOWN_FUNC_UNKNOWN_0xD3 (0xd3)
                                    · UNKNOWN_FUNC_UNKNOWN_0xD4 (0xd4)
                                    · undefined (0xee)
                                    · UNKNOWN_FUNC_UNKNOWN_0xEF (0xef)
2021-05-04T23:09:04.975Z CNTRLR   finding SUC...
2021-05-04T23:09:04.984Z CNTRLR   This is the SUC
2021-05-04T23:09:05.009Z CNTRLR   querying node information...
2021-05-04T23:09:05.077Z CNTRLR   received node information:
                                    controller role:            primary
                                    controller is a SUC:        true
                                    controller is a slave:      false
                                    controller supports timers: false
                                    nodes in the network:       1, 2
2021-05-04T23:09:05.086Z CNTRLR   [Node 001] Embedded device config loaded
2021-05-04T23:09:05.089Z CNTRLR   [Node 002] Embedded device config loaded
2021-05-04T23:09:05.094Z CNTRLR   setting serial API timeouts: ack = 1000 ms, byte = 150 ms
2021-05-04T23:09:05.102Z CNTRLR   serial API timeouts overwritten. The old values were: ack = 1000 ms, byte = 15
                                  0 ms
2021-05-04T23:09:05.102Z CNTRLR   Interview completed
2021-05-04T23:09:05.113Z CNTRLR   [Node 001] The node is alive.
2021-05-04T23:09:05.115Z CNTRLR   [Node 001] The node is ready to be used
2021-05-04T23:09:05.115Z CNTRLR » [Node 002] pinging the node...
2021-05-04T23:09:05.162Z CNTRLR   [Node 002] The node is alive.
2021-05-04T23:09:05.182Z CNTRLR   [Node 002] The node is ready to be used
2021-05-04T23:09:05.182Z CNTRLR   All nodes are ready to be used
2021-05-04T23:09:05.184Z CNTRLR « [Node 002] ping successful

**Comment by dkmcgowan** [comment]
I reset the device again, rebooted the machine, unplugged it from the extension cable and directly into the USB port, tried other USB ports, nothing makes the neighbors show up for the controller for me so far

**Comment by dkmcgowan** [comment]
ok, after the hard reset the home id had changed, so I removed the interviewstage again, restart the container, and it came up, did the full interview again, and neighbors are there now

**Comment by DayRunner131** [comment]
> ok, after the hard reset the home id had changed, so I removed the interviewstage again, restart the container, and it came up, did the full interview again, and neighbors are there now

@dkmcgowan could you define hard reset?

**Comment by dkmcgowan** [comment]
in the zwavejs control panel, on the main page, click advanced, there is a "hard reset" option, it will remove all your devices...  I removed all my nodes first to make them easier to add later, then did the hard reset...  I don't know if that is what did it, changing the usb port, the cable, rebooting, or doing the interview remove from config again

**Comment by dkmcgowan** [comment]
I still think there is an issue, the neighbors list is not updating...  I added the controller and then 1 powered device, I got neighbors list on both of those, they knew about each other.  I then added a second powered device, it came back and new about both the controller and the first device, but the controller and first device did not update their neighbors list.  I tried multiple heal networks and they still did not.  I added a 3rd and the process repeated itself

**Comment by dkmcgowan** [comment]
I removed the interviewStage: Completed line again and it updated all the neighbors

   "nodes": {
        "1": {
            "id": 1,
            "interviewStage": "Complete",

I'm more curious if it's an actual issue with routing or just all the data isn't coming back for some reason, but the network is working correcly

**Comment by dkmcgowan** [comment]
btw, when I removed that one line on node 1, aka the controller, it updated the neighbors on not just the controller, but also all the nodes

**Comment by AlCalzone** [comment]
> I'm more curious if it's an actual issue with routing or just all the data isn't coming back for some reason, but the network is working correcly

That's more likely and Compounded by the fact that the neighbors of devices are no longer re-queried after the very first interview. In fact retrieving the neighbor list basically just means _"Hey controller, what are your known neighbors of node XYZ"?_
I wonder if your controller's memory was actually a bit messed up, since it worked for you after the hard-reset now.

> when I removed that one line on node 1, aka the controller, it updated the neighbors on not just the controller, but also all the nodes

It shouldn't, but 🤷🏻‍♂️

**Comment by dkmcgowan** [comment]
I think the controller is fine now and all I think is happening is zwavejs doesn't get the node neighbors list unless I remove that interview line and restart to do a full interview, then all the nodes update their neighbors in zwavejs, not on the devices themselves...  I added another node, it had neighbors correct, all other nodes and controller did not, I unplugged controller and plugged into a PC and looked at it with zwave pc controller from silabs, it was all fine, all neighbors were correct, plugged back into zwavejs, removed line, did a full interview, all the neighbors showed up

**Comment by AlCalzone** [comment]
> I added another node, it had neighbors correct, all other nodes and controller did not

Heh, we should probably refresh these lists after adding a node.

**Comment by dkmcgowan** [comment]
great, I think that will help, at least with people trying to visualize their network and see how to best move devices around, could possibly also give an advanced feature in the control panel to update neighbors information to force a full interview on the nodes, thanks!

**Comment by AlCalzone** [comment]
#2559 will fix this by adding a method that returns the up to date list of neighbors for each node instead of relying on stale cached data. zwavejs2mqtt will need to add support for this too.

**Comment by cperuffo3** [comment]
For those, like me, stumbling across the internet trying to find out why their controller shows no neighbors either in the network graph OR in the debug screen under the controller node when using a combined zwaveJS integration with zwavejs2mqtt control panel:

[https://github.com/zwave-js/zwavejs2mqtt/issues/739](url)

I used the discussion above. Clearing browser cache seems to fix this problem. Unknown why the debug screen of the node shows no neighbors until a cache clear but I'll take it at face value for now.

**Comment by AlCalzone** [comment]
@robertsLando

**Comment by robertsLando** [comment]
I don't store any node info in localstorage or cache, this is really weird and I will investigate into this

**Comment by robertsLando** [comment]
Keep it monitored and tell me if this happens again
