### ISSUE TITLE
August Smart Lock gen 3 pairs and creates a Z-wave node but then does not discover any parameters or is modifiable.

### ISSUE THREAD

**Issue by liquidbear99** [zwave-js/zwave-js#2348]
I am happy to help in any way possible. When I pair the august smart lock 3 with z wave JS a node is created. It does not discover any parameters. I have tried factory resetting the lock and am only doing this as secure inclusion. It does tell me that the lock supports S2 but successfully paired and will be functional with S0. I know z wave JS does not support S2 yet but the august app says that it should still work on S0. Let me know how I can help diagnose the problem here.

**Comment by AlCalzone** [comment]
You can start by not deleting the issue template and following it.

**Comment by liquidbear99** [comment]
How can I access the template so I can follow it's format? I'm very new to GitHub and trying to learn.

**Comment by AlCalzone** [comment]
You click <kbd>New issue</kbd> and then select **Bug report** from the list.
![grafik](https://user-images.githubusercontent.com/17641229/114889171-29053200-9e0a-11eb-89c6-bf76dfda5f5c.png)
