### ISSUE TITLE
Add compat flag forcing number of scene groups to query

### ISSUE THREAD

**Issue by blhoward2** [zwave-js/zwave-js#2403]
Add a compat flag forcing the number of scene groups should be queried. Add to Leviton scene controllers. #2397

>> I'm unclear why we only query four scene IDs when there are eight. 

>>Straight from the Z-Wave specs:
> >The Scene Controller Configuration Command Class is used to configure nodes launching scenes using
their **association groups**. [...]
>> The grouping identifier values MUST be a sequence starting from 1. The **Association Supported Groupings
Get Command** may be used to request the number of groupings that a node supports.

>So, yeah... The device supports 4 association groups, so zwave-js queries 4 scene groups. There's currently no way to detect that there are in fact 8 groups. We'd need a compat flag for this.

**Comment by AlCalzone** [comment]
fixed by https://github.com/zwave-js/node-zwave-js/pull/3354
