### ISSUE TITLE
Add Zooz ZSE11

### ISSUE THREAD

**Issue by blhoward2** [zwave-js/zwave-js#2474]
Requested by Zooz: https://products.z-wavealliance.org/products/4152?selectedFrequencyId=-1

The sensor reports binary sensor for motion by default instead of notification because we discovered some issues on other platforms so Parameter 16 is set to value 1 by default which means send binary sensor report (don't send notification). If parameter 16 is set to value 0, the sensor won't send binary sensor reports and will send notification reports instead.

**Comment by AlCalzone** [comment]
@zwave-js-bot import config 4152 from zwa

**Comment by paulcusick3** [comment]
Seeing that motion is being received as the tamper sensor, not the motion sensor.  Am I alone?

**Comment by blhoward2** [comment]
No, they sent me one of these to test and this was just step one. I suspect we need to undo the mapping. Can you get a silly log of the motion tripped and post it? I’m going to move this to a new issue. #2558

**Comment by paulcusick3** [comment]
Here is the log set to debug - let me know if you need verbose.   Device is
Node 046

**Comment by paulcusick3** [comment]
[zwavejs_log.txt](https://github.com/zwave-js/node-zwave-js/files/6430629/zwavejs_log.txt)

**Comment by AlCalzone** [comment]
```
2021-05-05T22:28:02.307Z CNTRLR   [Node 046] [~] [Binary Sensor] Motion: true => false              [Endpoint 0]
...
2021-05-05T22:28:07.623Z CNTRLR   [Node 046] [~] [Notification] Home Security[Cover status]: 0 => 3 [Endpoint 0]
```
I see both motion and cover status being reported by the device.

**Comment by blhoward2** [comment]
Yes, if you go to the other issue I confirmed it. I've let Zooz know.
