### ISSUE TITLE
Not able to add node

### ISSUE THREAD

**Issue by RobbyRash** [zwave-js/zwave-js#2482]
**Checklist:**

-   [X ] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
-   [X ] I am **not** using ZWaveJS2MQTT. **Or:** a developer has told me to come here.
-   [X] I have checked the troubleshooting section and my problem is **not** described there.
-   [X ] I have read the changelog and my problem was **not** mentioned there.

**Describe the bug**

Node can't be added in it's home location ~ 8 feet away from the nearest powered node.  It CAN be added next to the hub.

**Device information**

Which device(s) is/are affected (make/model)?  NAS-WR01ZE Switch/HUSBZB-1 Hub
What are the node IDs? 20/1

**Did you change anything?**

-   [ ] **Yes**: _(please describe)_
-   [X ] **No**

**Did this use to work before?**

-   [ ] **Don't know**, this is a new device
-   [X ] **No**, it never worked anywhere
-   [ ] **Yes**, in: _(specify application with versions)_

**How are you using `node-zwave-js`**

-   [ ] `zwavejs2mqtt` (latest) docker image
-   [ ] `zwavejs2mqtt` (dev) docker image
-   [ ] `zwavejs2mqtt` Manual Docker build
    -   `node-zwave-js` branch: 
    -   `zwavejs2mqtt` branch: 
-   [ ] ioBroker.zwave2 adapter
-   [X ] `HomeAssistant` version XYZ
-   [ ] Pkg
-   [ ] Manual Docker build
    -   `node-zwave-js` branch: 
    -   `zwavejs2mqtt` branch: 
-   [ ] `node-red-contrib-zwave-js`
    -   Module version (double click node): 
-   [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github))
-   [ ] Other: 

**To Reproduce**

1. Go to 'Configure'
2. Click on 'Add node'
3. Scroll down to 'Devices'

**Additional context**

Steps taken in order:

1. Plugged switch in near hub (not home location) and added it.  Oops
2. Plugged switch in home location and it didn't work
3. Removed (exclusion process) from HA
4. Factory reset device
5. Restarted HA
6. Plugged switch in home location
7. Tried to add to HA and only get generic info and no response to switch commands
[zwave_js_dump (2).zip](https://github.com/zwave-js/node-zwave-js/files/6394749/zwave_js_dump.2.zip)

**Logfile:**

**Comment by AlCalzone** [comment]
Please make a zwave-js log, loglevel `debug` or `silly` and attach it here as a file.
I can't do much without that.

**Comment by AlCalzone** [comment]
> transmit status: NoAck
> 2021-04-28T21:06:41.310Z CNTRLR [Node 020] Node 20 did not respond after 1 attempts, it is presumed dead

The node does not respond or its responses don't reach the controller, so zwave-js cannot communicate with it. You could try healing the network so the device can learn how to reach the controller. Other than that, I don't see many options, except moving the device or adding another repeater between it and the controller.

**Comment by RobbyRash** [comment]
First question.  What is the preferred method to heal the network with ZWave JS in Home Assistant?
Second question. The device is within 10 -15 feet of the nearest zwave node (plugged in).  Since ZWave is a mesh network, isn’t this OK?  Why does it have to be in close proximity to the controller?

**Comment by AlCalzone** [comment]
> What is the preferred method to heal the network with ZWave JS in Home Assistant?

I'm not familiar with HA, you're better off asking on the HA discord. If you have zwavejs2mqtt, there are options to do it.

> The device is within 10 -15 feet of the nearest zwave node (plugged in).  Since ZWave is a mesh network, isn’t this OK?  Why does it have to be in close proximity to the controller?

To be honest, I don't know. Z-Wave is a mesh, but routing is handled by the chip firmwares. Maybe something is weird there, maybe your stick is in a bad location, maybe the desired location for the device is bad. Maybe you have interference somewhere.

**Comment by blhoward2** [comment]
You can't heal in HA yet. You have to use zjs2mqtt.

**Comment by ivdimitro** [comment]
On all zwave devices I have used it explicitly states to make the inclusion within the range of the controller. 
Also I think the routing is based on ids which are provided by the controller so I am not sure how a new devices can be routed to the controller it is is not already part of the network. 
Some controller have batteries so you can bring them close to the new device that needs inclusion. You can try with such controller.

**Comment by AlCalzone** [comment]
> I am not sure how a new devices can be routed to the controller it is is not already part of the network.

There is a thing called network-wide inclusion, but the device to include has to support it. Sounds like yours don't.

> Some controller have batteries so you can bring them close to the new device that needs inclusion. You can try with such controller.

No, don't do that. https://github.com/zwave-js/node-zwave-js/issues/1995 for the reason why.
