### ISSUE TITLE
Zwave.JS - Everspring HAC01/Eminent EM6514 Wall Remotes not working

### ISSUE THREAD

**Issue by Flight777** [zwave-js/zwave-js#2567]
**Checklist:**

-   [**X**] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
-   [ ] I am **not** using ZWaveJS2MQTT. **Or:** a developer has told me to come here.
-   [ ] I have checked the troubleshooting section and my problem is **not** described there.
-   [ ] I have read the changelog and my problem was **not** mentioned there.

**Describe the bug**

As per Home Assistant issue: https://github.com/home-assistant/core/issues/49061 we were referred to here.

Eminent EM6514 switches or better known as Everspring HAC01 are not giving out proper events/commands and only return a BasicCC log entry, despite the configuration showing available in the database: https://devices.zwave-js.io/

`2021-04-11T13:13:31.938Z CNTRLR [Node 019] treating BasicCC::Set as a report 2021-04-11T13:13:32.367Z CNTRLR [Node 019] treating BasicCC::Set as a report 2021-04-11T13:13:32.414Z CNTRLR [Node 019] treating BasicCC::Set as a report 2021-04-11T13:13:32.483Z CNTRLR [Node 019] treating BasicCC::Set as a report 2021-04-11T13:14:14.003Z CNTRLR [Node 019] treating BasicCC::Set as a report 2021-04-11T13:14:15.653Z CNTRLR [Node 019] treating BasicCC::Set as a report 2021-04-11T13:14:38.378Z CNTRLR [Node 019] treating BasicCC::Set as a report 2021-04-11T13:14:39.656Z CNTRLR [Node 019] treating BasicCC::Set as a report 2021-04-11T13:14:40.222Z CNTRLR [Node 019] treating BasicCC::Set as a report 2021-04-11T13:14:40.248Z CNTRLR [Node 019] treating BasicCC::Set as a report 2021-04-11T13:14:40.273Z CNTRLR [Node 019] treating BasicCC::Set as a report 2021-04-11T13:14:40.299Z CNTRLR [Node 019] treating BasicCC::Set as a report 2021-04-11T13:14:40.364Z CNTRLR [Node 019] treating BasicCC::Set as a report 2021-04-11T13:14:40.405Z CNTRLR [Node 019] treating BasicCC::Set as a report 2021-04-11T13:14:40.794Z CNTRLR [Node 019] treating BasicCC::Set as a report 2021-04-11T13:14:40.840Z CNTRLR [Node 019] treating BasicCC::Set as a report`

**Device information**

Which device(s) is/are affected (make/model)?  

Eminent EM6514 switches or better known as Everspring HAC01

What are the node IDs?

Node 009
Node 019

**Did you change anything?**

-   [ ] **Yes**: _(please describe)_
-   [**X**] **No**

**Did this use to work before?**

-   [ ] **Don't know**, this is a new device
-   [ ] **No**, it never worked anywhere
-   [**X**] **Yes**, in: Home Assistants old (deprecated) Zwave integration as well as in Homey before.

**How are you using `node-zwave-js`**

-   [**X**] `HomeAssistant` version 2021.5.0

**To Reproduce**

Add device and try the switching

**Additional context**

N/A

**Logfile:**

See attached
[zwave_js_dump (2).zip](https://github.com/zwave-js/node-zwave-js/files/6440845/zwave_js_dump.2.zip)

**Comment by AlCalzone** [comment]
Please make a zwave-js log, loglevel `debug` or `silly` and attach it here as a file.

Have you tried re-interviewing the device?

What do you mean by this?

> are not giving out proper events/commands and only return a BasicCC log entry

**Comment by Flight777** [comment]
Thanks for the quick reply and apologies for confusion I might cause in my limited knowledge around this!

I've attached an excerpt of the log, search for Node 009 and Node 019

[zwavejs.log](https://github.com/zwave-js/node-zwave-js/files/6441136/zwavejs.log)

I have tried multiple time to re-interview/remove and add the device, always the same result.

What I mean by that, is that this should be a relatively simple on/off switch but is not recognised as such by Home Assistant and I'm not able to tell any scenes or value changes coming from Zwave.JS other than that line.

**Comment by AlCalzone** [comment]
There are changes in the `Basic CC` `currentValue`, but I'm not sure if that is all the device offers:

> 2021-05-07T11:17:38.124Z CNTRLR   [Node 009] [~] [Basic] currentValue: 0 => 99                      [Endpoint 0]

Can you please re-interview the node and capture another log of that?

On a side note: Your node 14 is reporting its current power every second. That seems a bit excessive and causes a bunch of RF traffic. Might be worth to configure this differently

**Comment by ehindriks** [comment]
Hi, I have the same issue with this device. Below a log of a re-interview (if this is what you mean with the log at least).

2021-05-21 10:53:44.235 INFO ZWAVE: Calling api refreshInfo with args: [ 4, [length]: 1 ]
2021-05-21 10:53:44.286 INFO ZWAVE: Node 4: interview started
2021-05-21 10:53:44.347 INFO ZWAVE: Success zwave api call refreshInfo { success: true, message: 'Success zwave api call', result: undefined }
2021-05-21 10:53:44.377 INFO ZWAVE: Node 4: interview stage PROTOCOLINFO completed
2021-05-21 10:53:44.457 INFO ZWAVE: Node 4: interview stage NODEINFO completed
2021-05-21 10:53:44.574 INFO ZWAVE: Node 4: value added: 114-0-manufacturerId => 96
2021-05-21 10:53:44.577 INFO ZWAVE: Node 4: value added: 114-0-productType => 16
2021-05-21 10:53:44.579 INFO ZWAVE: Node 4: value added: 114-0-productId => 1
2021-05-21 10:53:44.806 INFO ZWAVE: Node 4: value added: 134-0-libraryType => 6
2021-05-21 10:53:44.809 INFO ZWAVE: Node 4: value added: 134-0-protocolVersion => 3.42
2021-05-21 10:53:44.812 INFO ZWAVE: Node 4: value added: 134-0-firmwareVersions => 2.0
2021-05-21 10:53:45.380 INFO ZWAVE: Node 4: metadata updated: 112-0-1
2021-05-21 10:53:45.384 INFO ZWAVE: Node 4: metadata updated: 112-0-2
2021-05-21 10:53:45.535 INFO ZWAVE: Node 4: value added: 112-0-1 => 99
2021-05-21 10:53:45.590 INFO ZWAVE: Node 4: value added: 112-0-2 => 1
2021-05-21 10:53:45.640 INFO ZWAVE: Node 4: interview stage COMMANDCLASSES completed
2021-05-21 10:53:45.645 INFO ZWAVE: Node 4: interview stage OVERWRITECONFIG completed
2021-05-21 10:53:45.676 INFO ZWAVE: Node 4: interview stage NEIGHBORS completed
2021-05-21 10:53:45.690 INFO ZWAVE: Node 4: interview stage COMPLETE completed
2021-05-21 10:53:45.732 INFO ZWAVE: Node 4: interview COMPLETED, all values are updated
2021-05-21 10:53:45.768 INFO ZWAVE: Node 4: value added 4-134-0-libraryType => 6
2021-05-21 10:53:45.769 INFO ZWAVE: Node 4: value added 4-134-0-protocolVersion => 3.42
2021-05-21 10:53:45.770 INFO ZWAVE: Node 4: value added 4-134-0-firmwareVersions => 2.0
2021-05-21 10:53:45.772 INFO ZWAVE: Node 4: value added 4-114-0-manufacturerId => 96
2021-05-21 10:53:45.773 INFO ZWAVE: Node 4: value added 4-114-0-productType => 16
2021-05-21 10:53:45.774 INFO ZWAVE: Node 4: value added 4-114-0-productId => 1
2021-05-21 10:53:45.776 INFO ZWAVE: Node 4: value added 4-112-0-1 => 99
2021-05-21 10:53:45.777 INFO ZWAVE: Node 4: value added 4-112-0-2 => 1
2021-05-21 10:53:45.782 INFO ZWAVE: Node 4 ready: Everspring - HAC01 (In-Wall Remote Insert)

**Comment by AlCalzone** [comment]
> Below a log of a re-interview (if this is what you mean with the log at least).

Yes, that is what I meant, but I need the driver log, not the one from zwavejs2mqtt.

**Comment by ehindriks** [comment]
Can you please give me a hint on how to get it?

**Comment by AlCalzone** [comment]
https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report?id=export-logs
The first one (zwave-js)

**Comment by ehindriks** [comment]
Thanks! Found it. It's node 4.
[zwavejs2mqtt-store.zip](https://github.com/zwave-js/node-zwave-js/files/6521492/zwavejs2mqtt-store.zip)

**Comment by AlCalzone** [comment]
@zwave-js-bot add compat flag to 0x0060:0x0010:0x0001
```json
enableBasicSetMapping: true
```

**Comment by Flight777** [comment]
Apologies for my extremely late reply... I've been out of the running for a bit unfortunately.

I was happy to see progress, however, I'm not yet sure what to do with it. Updated ZwaveJS in Home Assistant, reinterviewed the devices but there still seems no way how I can capture the switch. It does not show up as entity, nor as any Home Assistant recognised ZwaveJS event. Any pointers what I'm doing wrong? :)

**Comment by AlCalzone** [comment]
This should be coming in as a `"value event"` - I'm not sure how that can be accessed in HA. A driver log on loglevel "debug" would be good to verify.

**Comment by ehindriks** [comment]
Could be me, but I also didn't notice any difference. I even excluded and re-included the device. I also checked the events in the developer tools of HA, but nothing pops up when I press the button, but the basic value changes in the zwave-js control page. I added a driver log below. Can you please have a look if you can find something in it @AlCalzone?

It is node 23. The log contains an interview and a button press.

[zwavejs_2021-06-10.log](https://github.com/zwave-js/node-zwave-js/files/6634166/zwavejs_2021-06-10.log)

**Comment by AlCalzone** [comment]
> 2021-06-10T20:06:54.728Z CNTRLR   [Node 023] treating BasicCC::Set as a report

Nothing is being mapped, but I know why. The device doesn't support any CC we could map to. The NIF includes `Binary Switch`
```
2021-06-10T20:06:43.497Z CNTRLR « [Node 023] node info received
                                  supported CCs:
                                  · Binary Switch
                                  · Basic
                                  · Version
                                  · Manufacturer Specific
                                  · Association
                                  · Configuration
```
but then later tells us it doesn't support that CC:
```
2021-06-10T20:06:43.895Z DRIVER « [Node 023] [REQ] [ApplicationCommand]
                                  └─[VersionCCCommandClassReport]
                                      CC:      Binary Switch
                                      version: 0
2021-06-10T20:06:43.898Z CNTRLR   [Node 023]   does NOT support CC Binary Switch (0x25)
```
The manual also doesn't mention it:
![grafik](https://user-images.githubusercontent.com/17641229/121596584-e6de2280-ca3f-11eb-8648-6b022e727dd1.png)

If it actually supports `Binary Switch CC`, we can override what it tells us. This is described in https://zwave-js.github.io/zwavejs2mqtt/#/development/intro?id=testing-custom-devices-config, you can use this file to test:
[hac01.json.txt](https://github.com/zwave-js/node-zwave-js/files/6634375/hac01.json.txt) - make sure to rename it back to `.json`

**Comment by ehindriks** [comment]
Thanks for looking into it. I will try your config file once I found out how to update it on HA,

**Comment by ehindriks** [comment]
@AlCalzone I tried the attached hac01.json file and with this config I now have an entity in HA that I can use. Thanks for the update!

**Comment by AlCalzone** [comment]
Thanks for the feedback --> https://github.com/zwave-js/node-zwave-js/pull/2903

**Comment by Flight777** [comment]
Sorry to jump back in, was trying the new version just now. I indeed see an entity created in HA, however, it does not do anything (change state) when I press the switch on the wall.

This is what I see in the log, its node 019 (I did do some reinterviews in between to see if that helped):

![image](https://user-images.githubusercontent.com/5236143/125158802-b212d780-e173-11eb-8e9e-30459724e257.png)

Don't know if @ehindriks had more luck?

**Comment by AlCalzone** [comment]
@Flight777 doesn't look like it's being mapped to another CC. Can you share a log of a re-interview?

**Comment by Flight777** [comment]
Here you go (see attached).
[zwave_js (1).log](https://github.com/zwave-js/node-zwave-js/files/6795013/zwave_js.1.log)

**Comment by AlCalzone** [comment]
@Flight777 that's truncated. Please try again (wait for the "interview complete" message).
Seeing the cache files (the ones starting with the homeid) wouldn't hurt either.

**Comment by Flight777** [comment]
Sorry about that, somehow the download log function in the HA Integration seems to truncate automatically, even thought I see the full log lines until completion... Manually copied now, see attached.

Let me check where to get the cache files.

[zwave_js.log](https://github.com/zwave-js/node-zwave-js/files/6796849/zwave_js.log)

**Comment by Flight777** [comment]
@AlCalzone

**Comment by AlCalzone** [comment]
Ok the Binary Switch CC is at least being queried during the interview, which is good. The cache files can be downloaded here:
https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report?id=download-zip

**Comment by Flight777** [comment]
@AlCalzone I don't think I can reach those in Home Assistant OS, cannot get to the Addons files :(

**Comment by AlCalzone** [comment]
Any chance you could get zwavejs2mqtt to run outside HA?

**Comment by ehindriks** [comment]
> Sorry to jump back in, was trying the new version just now. I indeed see an entity created in HA, however, it does not do anything (change state) when I press the switch on the wall.
> 
> This is what I see in the log, its node 019 (I did do some reinterviews in between to see if that helped):
> 
> ![image](https://user-images.githubusercontent.com/5236143/125158802-b212d780-e173-11eb-8e9e-30459724e257.png)
> 
> Don't know if @ehindriks had more luck?

Mine is still working with the latest update, but I must admit that I still have the config file from AlCalzone installed as well. Strangly I noticed that I now have two entities in HA. One is updating the other is not. The one that is updating is named: sensor.in_wall_remote_insert_basic
The one that isn't working is: sensor.in_wall_remote_insert_node_status

**Comment by AlCalzone** [comment]
@Flight777 maybe I can work with HA's node dump, but no guarantee.
