### ISSUE TITLE
Log file rotation

### ISSUE THREAD

**Issue by steve28** [zwave-js/zwave-js#2569]
**Is your feature request related to a problem? Please describe.**
Log files grow unbounded.  With long-running instances and/or high levels of logs, the files can consume large amounts of disk space.

**Describe the solution you'd like**
Allow for log file rotation of the zwavejs*.log files.  Either by size or daily or any of the usuall log rotation schemes.  Would be nice to be configurable, but probably not necessary

**Explaining your use-case will go a long way in helping us understand.**
I like to leave logging on so I can go back and look at stuff in the past.  Helps for initial debugging.

**Describe alternatives you've considered**
scripts to do it myself 

**Additional context**
N/A

**Comment by marcus-j-davies** [comment]
Not sure on your setup, but...

This can already be achieved, with a custom file transport, which gives you complete control.
you will need to import the  Winston package.

and `createDefaultTransportFormat` from `@zwave-js/core`

```javascript
let FileTransportOptions = {
    filename: "/logs/zwave-js.log",
    format: createDefaultTransportFormat(false, false),
    level: "debug",
    maxsize: 500,
    maxFiles: 5
}
let FileTransport = new Winston.transports.File(FileTransportOptions)

let DriverOptions = {
    logConfig: {
        enabled: true,
        transports: [FileTransport]
    }
}

let Driver = new ZWaveJS.Driver("/dev/ttyACM0", DriverOptions)
```

See Winston file transport options here.
https://github.com/winstonjs/winston/blob/master/lib/winston/transports/file.js
