### ISSUE TITLE
Philio Technology Corp PST02-C: Config file needs partial parameters

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#2575]
Reported in https://github.com/AlCalzone/ioBroker.zwave2/issues/627
Link to device DB: https://devices.zwave-js.io/?jumpTo=0x013c:0x0002:0x000e:0.0
Link to manual: http://manuals-backend.z-wave.info/make.php?lang=en&type=&sku=PHI_PST02-1C

**Comment by cdnninja** [comment]
I have started this one and should have it done some time in the next week.  I will create the pull from my repo once closer to complete.

**Comment by AlCalzone** [comment]
Thanks!
