### ISSUE TITLE
[bug] Ensure Z-Wave JS external config directory exists

### ISSUE THREAD

**Issue by kpine** [zwave-js/zwave-js#2602]
### Version

**Checklist:**

- [ ] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 4.2.0
zwave-js version: 7.4.0

### Describe the bug

The `.config-db` directory is not populated. This is because nothing creates the directory. ZWave-JS [expects](https://github.com/zwave-js/node-zwave-js/blob/d487f9b2b0521bb3c8d8165f65fa76262f4e81e4/packages/config/src/utils.ts#L14) the directory to be created already. After manually creating the directory in my store volume, it gets populated.
 
### To Reproduce

1. Run the docker image
2. Notice the `.config-db` is not created or populated.

### Expected behavior

The container startup scripts should create the directory automatically, or upstream zwave-js driver should do it.

### Additional context

None.

**Comment by Altycoder** [comment]
For me, rolling back to 4.1.0 does not fix my problem, but 4.0.0 does.
