### ISSUE TITLE
Do not direct to Home Assistant github unless using zwave_js integration

### ISSUE THREAD

**Issue by Altycoder** [zwave-js/zwave-js#2604]
Do not direct home assistant users to the home assistant page unless they are using the zwave_js integration.  Users using an mqtt broker need to file issues here.

Item 1 in the new issues template directs all home assistant users away from here so it needs to be re-worded.

Suggest changing the wording on the new issues template from:

  1. Are you using HomeAssistant?
  If yes, please open your issue at https://github.com/home-assistant/core/issues
  UNLESS a developer told you to come here.

To:

  1. Are you using HomeAssistant **with the zwave_js integration**?
  If yes, please open your issue at https://github.com/home-assistant/core/issues
  UNLESS a developer told you to come here.

**Comment by AlCalzone** [comment]
Accepting PR

**Comment by blhoward2** [comment]
@kreene1987 I see that you pushed a commit to your local repository referencing this issue. Did you mean to push a PR to the project pushing that change over?

**Comment by kreene1987** [comment]
Yep, very new to GH, let me see if I can get it figured out.

**Comment by blhoward2** [comment]
It's not a commit. Go to the GitHub website, compare your branch to the master at the project, and create a pull request. 

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by AlCalzone** [comment]
closed in #2633
