### ISSUE TITLE
[bug] Fibaro - Missing associations

### ISSUE THREAD

**Issue by matthias-matze** [zwave-js/zwave-js#2608]
Hy, all my fibaro devices are missing assocation group lifeline.

The devices are alive ans interview complete.

i cant add association manually the field "Group" is empty.

All other devices (aeotec or qubino) are ok and working

**Comment by AlCalzone** [comment]
If I trust the cache files, both Node 33 and 42 **do not** support `Association CC` or `Multi Channel Association CC`. However, they do support `Association Group Information`, which makes me sceptical there's something fishy.

Can you please set the loglevel to `"debug"`, re-interview both nodes and post a log of that?

**Comment by matthias-matze** [comment]
Hy, 
upgraded to latest zwav-js version. Attached is log files with debug level. Hope it helps, and sorry for the delay to give you the attached files.
[zwavejs2mqtt-store(1).zip](https://github.com/zwave-js/node-zwave-js/files/6602065/zwavejs2mqtt-store.1.zip)

**Comment by AlCalzone** [comment]
There are no logfiles in the attached archive. Please read here: https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report?id=export-logs
