### ISSUE TITLE
ZDI 5200 Param 5 duplicates param 4

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#2623]
https://github.com/zwave-js/node-zwave-js/blob/6f0cb2bbaf734c0bac2edd446853244de2bc89c7/packages/config/config/devices/0x0234/zdi5200.json#L39-L44

@Roagert you made this file - could you provide a fix for param 5? I found a manual, but I don't speak danish:
![grafik](https://user-images.githubusercontent.com/17641229/118379086-71199f00-b5d8-11eb-8427-c214a1a8446e.png)
I _think_ this is about consumption reports.

**Comment by Roagert** [comment]
Yes ill fix tomorrow.
