### ISSUE TITLE
FT111-K needs to be aligned to Aeotec file

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#2624]
https://github.com/zwave-js/node-zwave-js/blob/6f0cb2bbaf734c0bac2edd446853244de2bc89c7/packages/config/config/devices/0x016a/ft111-k.json#L241

These are wrong and should already be fixed in the Aeotec original file.

**Comment by cdnninja** [comment]
I assume this is like FT112 that I recently updated.   I actually removed the -k version.  From what I can tell the -k variants are just different device IDs with the same config.

**Comment by AlCalzone** [comment]
Oh, good. Got some time to check that?

**Comment by cdnninja** [comment]
Yes I could work on it in the next bit.  I chip away at files when holding a sleeping baby.
