### ISSUE TITLE
Multilevel Switch current level value is never refreshed after a Set - Heatit ZDim

### ISSUE THREAD

**Issue by henrikeri** [zwave-js/zwave-js#2655]
**Checklist:**

-   [x] My problem is **not** within Home Assistant or the ZWave JS integration. **Or:** a Home Assistant developer has told me to come here.
-   [x] My problem is **not** within ZWaveJS2MQTT. **Or:** a ZWaveJS2MQTT developer has told me to come here.
-   [x] I have checked the troubleshooting section and my problem is **not** described there.
-   [x] I have read the changelog and my problem was **not** mentioned there.

**Describe the bug**

When toggeling the "Light" swith in Home Assistant, the multilevel switch current level value is never refreshed after a Set

**Device information**

Which device(s) is/are affected (manufacturer/model)?  Thermofloor Heatit Z-Dim https://devices.zwave-js.io/?jumpTo=0x019b:0x0003:0x2200:0.0
What is/are the node IDs? 031

**Did you change anything?**

-   [ ] **Yes**: _(please describe)_
-   [x] **No**

**Did this use to work before?**

-   [x] **Don't know**, this is a new device <--- I have 20 of them, so not a dud
-   [ ] **No**, it never worked anywhere
-   [ ] **Yes**, in: _(specify application with versions)_

**How are you using `node-zwave-js`**

-   [ ] `zwavejs2mqtt` (latest) docker image
-   [ ] `zwavejs2mqtt` (dev) docker image
-   [ ] `zwavejs2mqtt` Manual Docker build
    -   `node-zwave-js` branch: 
    -   `zwavejs2mqtt` branch: 
-   [ ] ioBroker.zwave2 adapter
-   [x] `HomeAssistant` version  0.1.21
-   [ ] Pkg
-   [ ] Manual Docker build
    -   `node-zwave-js` branch: 
    -   `zwavejs2mqtt` branch: 
-   [ ] `node-red-contrib-zwave-js`
    -   Module version (double click node): 
-   [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github))
-   [ ] Other: 

**To Reproduce**

1. Go to 'the dimmer in for instance home assistant'
2. Click on 'toggle the "light" switch
4. It will stay on for a second or so before switching off (the ui switch), the light itself turns on at previous level

**Additional context**

Not operating properly breaks the home assistant lovelace frontend card for the dimmer. If one toggles the binary switch, the "light" switch will turn on, and stay on. However as the frontend operates on the "light" switch, this does not help

**Logfile:**

[zwave_debug_log.zip](https://github.com/zwave-js/node-zwave-js/files/6519068/zwave_debug_log.zip)
[zwave_js_dump.zip](https://github.com/zwave-js/node-zwave-js/files/6519069/zwave_js_dump.zip)

When toggeling the dimmer, the multilevel Switch current level value is never refreshed after a set. This makes the dimmer unusable with the HomeAssistant Lovelace UI.

**Comment by kpine** [comment]
I told @henrikeri to submit this issue, because it looks like the Multilevel Switch Set is supervised, but there is never any Report to update the current level. On the other hand, the Binary Switch Set is not supervised, and the node responds on its own with Binary and Multilevel Switch reports.

**Comment by blhoward2** [comment]
@kpine So you think we need to disable Supervision?

**Comment by blhoward2** [comment]
@zwave-js-bot add compat flag to 0x019b:0x0003:0x2200:0.0

```
"commandClasses": {
			"remove": {
				"0x6c": {
					// The device does not support supervision although it is mandatory for the device type
					"endpoints": "*"
				}
			}
```

**Comment by blhoward2** [comment]
@zwave-js-bot add compat flag to 0x019b:0x0003:0x2200:0.0

```
"commandClasses": {
			"remove": {
				"0x6c": {
					"endpoints": "*"
				}
			}
```

**Comment by blhoward2** [comment]
@zwave-js-bot add compat flag to 0x019b:0x0003:0x2200:0.0

```
"commandClasses": {
	"remove": {
		"0x6c": {
			"endpoints": "*"
		}
	}
}
```

**Comment by blhoward2** [comment]
@AlCalzone See the error message on the bot. It looks like there is a bug in the code.

**Comment by kpine** [comment]
> 
> 
> @kpine So you think we need to disable Supervision?

It came to mind, but I couldn't remember what was supposed to actually happen with Supervision and setting the target value to 0xFF (last level).

**Comment by blhoward2** [comment]
I staged the PR but I'm not actually sure this is right:

```
2021-05-20T21:31:41.487Z DRIVER » [Node 031] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      128
                                  └─[SupervisionCCGet]
                                    │ session id:      56
                                    │ request updates: true
                                    └─[MultilevelSwitchCCSet]
                                        target value: 255
2021-05-20T21:31:41.489Z SERIAL « [ACK]                                                                   (0x06)
2021-05-20T21:31:41.496Z SERIAL « 0x0104011301e8                                                       (6 bytes)
2021-05-20T21:31:41.496Z SERIAL » [ACK]                                                                   (0x06)
2021-05-20T21:31:41.497Z DRIVER « [RES] [SendData]
                                    was sent: true
2021-05-20T21:31:41.513Z SERIAL « 0x010700138000000368                                                 (9 bytes)
2021-05-20T21:31:41.513Z SERIAL » [ACK]                                                                   (0x06)
2021-05-20T21:31:41.514Z DRIVER « [REQ] [SendData]
                                    callback id:     128
                                    transmit status: OK
2021-05-20T21:31:41.528Z SERIAL « 0x010b0004001f056c0238ff0043                                        (13 bytes)
2021-05-20T21:31:41.528Z SERIAL » [ACK]                                                                   (0x06)
2021-05-20T21:31:41.529Z DRIVER « [Node 031] [REQ] [ApplicationCommand]
                                  └─[SupervisionCCReport]
                                      session id:          56
                                      more updates follow: false
                                      status:              Success
                                      duration:            [Duration: 0 seconds]
```

It does see a Supervision report back. @AlCalzone ?

**Comment by AlCalzone** [comment]
Supervision is not the problem - its the fact that we don't refresh the value after setting it to 255.

**Comment by henrikeri** [comment]
I got in contact with Thermofloor today, they were aware of the issue and supplied an OTA firmware update that resolves the issue.

**Comment by AlCalzone** [comment]
> they were aware of the issue and supplied an OTA firmware update that resolves the issue.

So the expected behavior is that the device reports the actual status on its own?
That's good to know but we still need to handle those device that don't.

**Comment by henrikeri** [comment]
> 
> 
> > they were aware of the issue and supplied an OTA firmware update that resolves the issue.
> 
> So the expected behavior is that the device reports the actual status on its own?
> That's good to know but we still need to handle those device that don't.

I would assume that's the expected behaviour given the fact that they did have an OTA update ready. However, they did not specifically elaborate as to wheter this expected or not.
