### ISSUE TITLE
Coolcam Light switch 2 channel (EU-2) "does not support the CC assosiation" error

### ISSUE THREAD

**Issue by davidwaze** [zwave-js/zwave-js#2659]
Build/Run method

[ X ] Manually built (git clone - npm install - npm run build )
zwavejs2mqtt version: 4.2.1
zwave-js version: 7.4.0

Describe the bug
Interview fails, stay in "nodeinfo", log indicate [Node 196] Error during node interview: Node 196 (endpoint 1) does not support
the Command Class Association

Device : 600-4235-3 (0x0258-0x0003-0x108b)

Tried : multiple interviews without any success / remove device / factory reset device

Thanks for your support.
[logs.txt](https://github.com/zwave-js/node-zwave-js/files/6521328/logs.txt)

![coolcam](https://user-images.githubusercontent.com/26407047/119110925-dd563180-ba22-11eb-8411-994d13aa023f.JPG)

**Comment by AlCalzone** [comment]
This should already be fixed on master -> #2646
I'll probably release a patch tonight.

**Comment by davidwaze** [comment]
Thanks my friend and for your faaaaast answer :-)

**Comment by davidwaze** [comment]
Hello,

Just one small question, i tried to find the answer without success (probably wrong search ...)

I'm running with zwavejs2mqtt 4.3.0 (with included zwavejs 7.5.0).

How to upgrade only zwavejs to 7.5.1 without waiting next release of zwavejs2mqtt ?

Thanks for your help.
