### ISSUE TITLE
Create a compat flag to Ring Keypad v1 due to duplicate entry control notification sequences 

### ISSUE THREAD

**Issue by xhemp** [zwave-js/zwave-js#2677]
I’ve never seen this before but my Ring keypad v1 has been seeing duplicate sequences even when connected to mains (before that, it would only happen when on battery):
`
[Node 057] Received duplicate Entry Control Notification (sequence number 1),ignoring...
[Node 057] Received duplicate Entry Control Notification (sequence number 2),ignoring...
[Node 057] Received duplicate Entry Control Notification (sequence number 3),ignoring...

`
Would it be doable to do a compat flag (ie: ignoreEntryControlSequenceNumber) for it to ignore the duplicates instead of patching the drivers on every release (like I’m doing it now, thanks @marcus-j-davies for the help)?

**Comment by blhoward2** [comment]
We have tried to avoid creating device specific compat flags thus far. Most often we can find an underlying bug on our end, work around this in the automation itself, or use a pre-existing compat flag to prevent the issue. Does this notification event change the state of an entity in HA? Or does it come across as a value_notification or something?

Please fill out the bug template or post that info. We need versions. Log files at the Silly level. A node export. Etc. We're not going to hop right to adding a new compat flag without looking into it.

**Comment by xhemp** [comment]
Problem is that it doesn't show what I actually pressed on the keypad so HA doesn't even know what is coming from it.  I didn't send in any logs as I would like to know if you would even consider it as if not, I would be patching the driver file every time.  I am using the latest version of zwavejs (7.5.1) and I am attaching a debug I've done a couple of weeks ago and a dump of that node.
[dump_ringkeypad_v1.json.txt](https://github.com/zwave-js/node-zwave-js/files/6532500/dump_ringkeypad_v1.json.txt)
[keypadv1-debug.txt](https://github.com/zwave-js/node-zwave-js/files/6532473/keypadv1-debug.txt)

**Comment by marcus-j-davies** [comment]
@blhoward2,

I think some context might help here.

**Entry Control** is relatively new in Z-Wave JS, I know of very few devices, that provide this CC, its the ring Keypad, that first made use of it - as far as I am aware.

Now then,
The **Entry Control** specification states, that the `sequenceNumber` part of notifications must be unique, but between the range of 0-255 🤷.

The ring pad keypad, has already shown it is not compliant, as there is compat flag for `disableStrictEntryControlDataValidation` already in the config.

It turns out, the device likes to send duplicated `sequenceNumber`s  also.
Z-Wave JS ignores these duplicates (providing they have been used in the last 5 notifications) - and rightfully so.

However, it means, the notifications are not being forwarded to the front end 

Much like `disableStrictEntryControlDataValidation`, it maybe of discussion, to also create a  `ignoreEntryControlSequenceNumber` to deal with Entry Control devices  that don't follow the proper spec.

As mentioned, the way around it currently, is to comment out the duplication checking altogether (for this CC).
which is not the best approach obviously, but if a new compat flag could be added, it can be applied to other device configs that may come out, with the same disregard to spec on this CC.

**Comment by blhoward2** [comment]
> 
> 
> 
> 
> Problem is that it doesn't show what I actually pressed on the keypad so HA doesn't even know what is coming from it.  I didn't send in any logs as I would like to know if you would even consider it as if not, I would be patching the driver file every time.  I am using the latest version of zwavejs (7.5.1) and I am attaching a debug I've done a couple of weeks ago and a dump of that node.
> 
> [dump_ringkeypad_v1.json.txt](https://github.com/zwave-js/node-zwave-js/files/6532500/dump_ringkeypad_v1.json.txt)
> 
> [keypadv1-debug.txt](https://github.com/zwave-js/node-zwave-js/files/6532473/keypadv1-debug.txt)
> 
> 

Just to confirm, are these logs from the project code or your patched version?

> I didn't send in any logs as I would like to know if you would even consider it as if not, I would be patching the driver file every time.

The call is @AlCalzone but I think we'd always consider a compat flag along the lines of what @marcus-j-davies describes, if really needed. We're not going to make one just to work around one device's quirk though. OZW did and it led to a number of issues eventually. 

Also, you should be able to fork the repo, make a change, and just keep merging in upstream changes for now. Then you only have to do something with your change if it creates a conflict.

**Comment by xhemp** [comment]
> > Problem is that it doesn't show what I actually pressed on the keypad so HA doesn't even know what is coming from it.  I didn't send in any logs as I would like to know if you would even consider it as if not, I would be patching the driver file every time.  I am using the latest version of zwavejs (7.5.1) and I am attaching a debug I've done a couple of weeks ago and a dump of that node.
> > [dump_ringkeypad_v1.json.txt](https://github.com/zwave-js/node-zwave-js/files/6532500/dump_ringkeypad_v1.json.txt)
> > [keypadv1-debug.txt](https://github.com/zwave-js/node-zwave-js/files/6532473/keypadv1-debug.txt)
> 
> Just to confirm, are these logs from the project code or your patched version?

The debug was done before I patched it.

> > Also, you should be able to fork the repo, make a change, and just keep merging in upstream changes for now. Then you only have to do something with your change if it creates a conflict.

👍 , thanks!

**Comment by blhoward2** [comment]
So I guess one question would be, should this be part of the current compat flag versus a separate one? I haven't looked but what data validation are we disabling but this seems like data validation too?

@xhemp Did this ever work under any version? Or is the change you describe from switching to mains power?

**Comment by marcus-j-davies** [comment]
`Entry Control` specs, states that the ASCII/DATA payload of notifications needs to have padding
(as its a security payload, to introduce entropy I suppose).

But this device (and maybe more) don't add the required padding, hence the compat flag.
Having it apart of the current flag - would indeed work, and will remove the need for another flag.

but I'm not sure if it should be 2 separate areas that need some assistance - there maybe devices that  follow the padding requirements , but not the `sequenceNumber `runs

**Comment by xhemp** [comment]
> @xhemp Did this ever work under any version? Or is the change you describe from switching to mains power?

I have never seen this particular  issue with the device on mains, first time I've seen was thia morning (I had updated from 7.5.0 to 7.5.1 but don't think it's related). If the keypad is on batteries, it happens all the time which makes it unusable.

**Comment by marcus-j-davies** [comment]
For what it's worth, I just don't  think the sequenceNumber rules are strictly followed, and end up acting differently, if mains powered.

The device it's self, has issues with the requirements in data validation.

I can't say, if other Entry Control devices have the same problems, but it won't be too much of a surprise if not.

**Comment by AlCalzone** [comment]
@xhemp could you share a bit more logging from **before** the first notification gets ignored? It does seem like the device is counting up correctly. Maybe something caused it to lose power and restart from 1?

**Comment by xhemp** [comment]
> @xhemp could you share a bit more logging from **before** the first notification gets ignored? It does seem like the device is counting up correctly. Maybe something caused it to lose power and restart from 1?

Trying now, patch has been undone and I'm running on debug only on that device, it may take sometime to reappear, though.

**Comment by xhemp** [comment]
Tested for the last 20 minutes and the duplicated showed up again (a few times), in the end of the log file, you can see I try to arm away then arm home and it didn't work then disarmed just worked fine.
[new_log.txt](https://github.com/zwave-js/node-zwave-js/files/6533518/new_log.txt)
Edit: Logs are still running, will leave it running and keep testing and upload the latest file later on.

**Comment by marcus-j-davies** [comment]
@AlCalzone,

Here is another (Mine went from Sequence 1 -> 2 -> 1) towards the end
[zwavelog-2.txt](https://github.com/zwave-js/node-zwave-js/files/6533525/zwavelog-2.txt)

Ignore **REDCTL** entries (thats node red)


The device behaves "Better" when plugged in

**Comment by AlCalzone** [comment]
Yeah, that looks like some kind of reset in the device or something. I'll disable this check as part of `disableStrictEntryControlDataValidation`, as the device is more or less unusable without it.

**Comment by marcus-j-davies** [comment]
Specifications  state a range from 1-255, but I wonder if there is any rule as to when the counter is reset. 🤔.
I'm not hot on terminology with specifications, so could be clutching  at straws
