### ISSUE TITLE
In order to reopen issue 2608

### ISSUE THREAD

**Issue by matthias-matze** [zwave-js/zwave-js#2782]
**Describe the bug**

FGS-213 and fgd-212 missing association groups
**Device information**
node id 42 and 33

**Did this use to work before?**

-   [ ] **Don't know**, this is a new device
-   [X] **No**, it never worked anywhere
-   [ ] **Yes**, in: _(specify application with versions)_

**How are you using `node-zwave-js`**

-   [X] `zwavejs2mqtt` (latest) docker image
-   [ ] `zwavejs2mqtt` (dev) docker image
-   [ ] `zwavejs2mqtt` Manual Docker build
    -   `node-zwave-js` branch: 
    -   `zwavejs2mqtt` branch: 
-   [ ] ioBroker.zwave2 adapter
-   [ ] `HomeAssistant` version XYZ
-   [ ] Pkg
-   [ ] Manual Docker build
    -   `node-zwave-js` branch: 
    -   `zwavejs2mqtt` branch: 
-   [ ] `node-red-contrib-zwave-js`
    -   Module version (double click node): 
-   [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github))
-   [ ] Other: 

**To Reproduce**

dont know
**Additional context**
[zwavejs2mqtt-store(1).zip](https://github.com/zwave-js/node-zwave-js/files/6602079/zwavejs2mqtt-store.1.zip)

**Comment by AlCalzone** [comment]
Let's continue this in #2608 - I've reopened it.
