### ISSUE TITLE
Missing device configuration params for DSC08 AEON Labs / Smart Energy Illuminator.

### ISSUE THREAD

**Issue by raym777** [zwave-js/zwave-js#2796]
**Checklist:**

-   [X] My problem is **not** within Home Assistant or the ZWave JS integration. **Or:** a Home Assistant developer has told me to come here.
-   [X] My problem is **not** within ZWaveJS2MQTT. **Or:** a ZWaveJS2MQTT developer has told me to come here.
-   [X] I have checked the troubleshooting section and my problem is **not** described there.
-   [X] I have read the changelog and my problem was **not** mentioned there.

**Describe the bug**

As [instructed](https://github.com/zwave-js/node-zwave-js/discussions/2781), providing details for the [DSC08 AEON Labs / Smart Energy Illuminator](https://devices.zwave-js.io/?jumpTo=0x0086:0x0003:0x0008:0.0) which provides config params **80, 90, 91 and 92** but these are missing from the associated configuration file and can therefore not be set via Z-Wave JS. 
**Device information**

```
  "manufacturer": "AEON Labs",
  "manufacturerId": 134,
  "productType": 3,
  "productId": 8,
  "firmwareVersion": "1.27",
```

**Did you change anything?**

-   [ ] **Yes**: _(please describe)_
-   [X] **No**

**Did this use to work before?**

-   [X] **Don't know**, this is a new device
-   [ ] **No**, it never worked anywhere
-   [ ] **Yes**, in: _(specify application with versions)_

**How are you using `node-zwave-js`**

-   [ ] `zwavejs2mqtt` (latest) docker image
-   [ ] `zwavejs2mqtt` (dev) docker image
-   [ ] `zwavejs2mqtt` Manual Docker build
    -   `node-zwave-js` branch: 
    -   `zwavejs2mqtt` branch: 
-   [ ] ioBroker.zwave2 adapter
-   [X] `HomeAssistant` version core-2021.6.2
-   [ ] Pkg
-   [ ] Manual Docker build
    -   `node-zwave-js` branch: 
    -   `zwavejs2mqtt` branch: 
-   [ ] `node-red-contrib-zwave-js`
    -   Module version (double click node): 
-   [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github))
-   [ ] Other: 

**To Reproduce**

Attempt to set the above missing params in Home Assistant. Error message:
`websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Configuration parameter with value ID 4-112-0-80 could not be found`

-->

**Comment by AlCalzone** [comment]
@blhoward2 Do you have some insight here?

**Comment by blhoward2** [comment]
Those aren't in the manual provided to me by Aeotec, so they may have been added along the way at some point. @raym777 are you sure this is supported on this device?

 I'll email them to verify. They aren't listed in the lists of changes they provided bu they may have overlooked them since this is an old device.

Update: Aeotec is checking as they think they should exist, but they aren't included on their engineering sheets.

**Comment by blhoward2** [comment]
Aeotec confirmed 80, 90-92 exist on this device. They're revising their spec sheet.

**Comment by raym777** [comment]
Nice! Thanks a lot for the follow up.

**Comment by blhoward2** [comment]
This is incorporated into my Aeotec batch that is in progress.
