### ISSUE TITLE
Heatit Z-TRM2fx not refreshing power (watt)

### ISSUE THREAD

**Issue by quack3d** [zwave-js/zwave-js#2815]
**Checklist:**

-   [x] My problem is **not** within Home Assistant or the ZWave JS integration. **Or:** a Home Assistant developer has told me to come here.
-   [x] My problem is **not** within ZWaveJS2MQTT. **Or:** a ZWaveJS2MQTT developer has told me to come here.
-   [x] I have checked the troubleshooting section and my problem is **not** described there.
-   [x] I have read the changelog and my problem was **not** mentioned there.

**Describe the bug**

Meter report only reports energy (kWh) and not power (watt). Watt is also not reported when watt changes.

**Device information**

Heatit Z-TRM2fx
Node ID 26

**Did you change anything?**

-   [ ] **Yes**: _(please describe)_
-   [x] **No**

**Did this use to work before?**

-   [ ] **Don't know**, this is a new device
-   [x] **No**, it never worked anywhere
-   [ ] **Yes**, in: _(specify application with versions)_

**How are you using `node-zwave-js`**

-   [ ] `zwavejs2mqtt` (latest) docker image
-   [ ] `zwavejs2mqtt` (dev) docker image
-   [ ] `zwavejs2mqtt` Manual Docker build
    -   `node-zwave-js` branch: 
    -   `zwavejs2mqtt` branch: 
-   [ ] ioBroker.zwave2 adapter
-   [ ] `HomeAssistant` version XYZ
-   [ ] Pkg
-   [ ] Manual Docker build
    -   `node-zwave-js` branch: 
    -   `zwavejs2mqtt` branch: 
-   [ ] `node-red-contrib-zwave-js`
    -   Module version (double click node): 
-   [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github))
-   [x] Other: Home Assistant core-2021.6.3 with Z-Wave JS to MQTT addon

**To Reproduce**

1. See debug logs.
2. Watch power (watt) not being updated in the interval specified in configuration parameter 21
3. Do a refresh_value and see power (watt) being updated

**Logfile:**
[zwavejs2mqtt.log](https://github.com/zwave-js/node-zwave-js/files/6619253/zwavejs2mqtt.log)
[meter report_manual refresh.log](https://github.com/zwave-js/node-zwave-js/files/6619254/meter.report_manual.refresh.log)
[meter report.log](https://github.com/zwave-js/node-zwave-js/files/6619255/meter.report.log)

**Comment by quack3d** [comment]
I got watt values automatically when I used Zwave 1.4. Does that mean it should work in ZwaveJS also?

**Comment by AlCalzone** [comment]
Did OZW 1.4 poll them?

**Comment by quack3d** [comment]
I don't think so. But apparently an old integration corrupted settings somehow. For some reason these were my associations on the device:

![image](https://user-images.githubusercontent.com/25592497/121306029-a925b080-c8fe-11eb-8e4c-e489f507bd73.png)

I removed the top line and everything started working! The right temperature started reporting in the interval, the power started reporting in the interval AND power started reporting when there was a change.

**Comment by AlCalzone** [comment]
Gotta love the OZW associations 🙄

**Comment by kpine** [comment]
For reference, it looks like OZW has a `ForceInstances` compatibility flag, which appears to force a multi-channnel association to [endpoint/instance 1](https://github.com/OpenZWave/open-zwave/blob/449f89f063effb048f5dd6348d509a6c54fd942d/cpp/src/command_classes/MultiChannelAssociation.cpp#L398) of the controller node. It has something to do with Qubino devices. 🤷‍♂️ 

Why it was originally [set](https://github.com/OpenZWave/open-zwave/blob/449f89f063effb048f5dd6348d509a6c54fd942d/config/thermofloor/heatit056.xml#L134) on _this_ device, who knows?
