### ISSUE TITLE
Battery devices are put back to sleep before parameter changes are verified

### ISSUE THREAD

**Issue by jtronicus** [zwave-js/zwave-js#2820]
**Checklist:**

-   [X] My problem is **not** within Home Assistant or the ZWave JS integration. **Or:** a Home Assistant developer has told me to come here.
-   [X] My problem is **not** within ZWaveJS2MQTT. **Or:** a ZWaveJS2MQTT developer has told me to come here.
-   [X] I have checked the troubleshooting section and my problem is **not** described there.
-   [X] I have read the changelog and my problem was **not** mentioned there.

**Describe the bug**

When I change a config parameter on a battery-powered (asleep) device, and then manually wake the device, zwavejs appears to send 3 commands, in this order:
* Configuration Set
* Wake Up No More Information
* Configuration Get

The 3rd command (Configuration Get) is not received by the device because it has already gone back to sleep.  I need to manually wake the device a second time in order for the command to complete

**Device information**

Which device(s) is/are affected (manufacturer/model)?  Inovelli LZW60 multisensor
What is/are the node IDs? 20

**Did you change anything?**

-   [ ] **Yes**: _(please describe)_
-   [X] **No**

**Did this use to work before?**

-   [X] **Don't know**, this is a new device
-   [ ] **No**, it never worked anywhere
-   [ ] **Yes**, in: _(specify application with versions)_

**How are you using `node-zwave-js`**

-   [X] `zwavejs2mqtt` (latest) docker image
-   [ ] `zwavejs2mqtt` (dev) docker image
-   [ ] `zwavejs2mqtt` Manual Docker build
    -   `node-zwave-js` branch: 
    -   `zwavejs2mqtt` branch: 
-   [ ] ioBroker.zwave2 adapter
-   [ ] `HomeAssistant` version XYZ
-   [ ] Pkg
-   [ ] Manual Docker build
    -   `node-zwave-js` branch: 
    -   `zwavejs2mqtt` branch: 
-   [ ] `node-red-contrib-zwave-js`
    -   Module version (double click node): 
-   [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github))
-   [ ] Other: 

**To Reproduce**

1. Change a config parameter on device
2. Wake the device (on the LZW60, this is done by pressing the button 3x)
3. Wait for device to go back asleep
4. Wake the device again

**Additional context**

Starting Timestamp in log file: 2021-06-08T22:34:53.881Z CNTRLR « [Node 020] received wakeup notification

**Logfile:**

[zwavejs_2021-06-08.log](https://github.com/zwave-js/node-zwave-js/files/6620032/zwavejs_2021-06-08.log)

**Comment by AlCalzone** [comment]
Looks like we don't consider scheduled messages when determining if we should send a node back to sleep
