### ISSUE TITLE
Enerwave (Wenzhou MTLC Electric Appliances) ZWN-RSM1-PLUS incorrectly detected as ZWN-RSM1 / ZWN-RSM2

### ISSUE THREAD

**Issue by pletch** [zwave-js/zwave-js#2835]
**Checklist:**

-   [x] My problem is **not** within Home Assistant or the ZWave JS integration. **Or:** a Home Assistant developer has told me to come here.
-   [x] My problem is **not** within ZWaveJS2MQTT. **Or:** a ZWaveJS2MQTT developer has told me to come here.
-   [x] I have checked the troubleshooting section and my problem is **not** described there.
-   [x] I have read the changelog and my problem was **not** mentioned there.

**Describe the bug**

Recently migrated from Vera Edge to this library for use with Home Assistant with ZooZ S2 Stick 700 Series .  When moving several (qty 3) ZWN-RSM1-Plus devices, observed that these were incorrectly identified as older generation ZWN-RSM1 / ZWN-RSM2 type.  Tracked this to the productType / productID combination in the config file definitions.

**Device information**

Which device(s) is/are affected (manufacturer/model)? 
   ZWN-RSM1-PLUS
   Wenzhou MTLC Electric Appliances Co., Ltd. / Smart Relay Switch Module 
What is/are the node IDs?
   282-1541-273 (0x011a-0x0111-0x0605)
**Did you change anything?**

-   [x] **Yes**: _(please describe)_
       To fix, migrate the combination of 
		{
			"productType": "0x0111",
			"productId": "0x0605"
		}
      from
          /config/config/devices/0x011a/zwn-rsm2.json
      [https://devices.zwave-js.io/?jumpTo=0x011a:0x0101:0x5606:0.0](https://devices.zwave-js.io/?jumpTo=0x011a:0x0101:0x5606:0.0)
       to
          /config/config/devices/0x011a/zwn-rsm1-plus.json.
       [https://devices.zwave-js.io/?jumpTo=0x011a:0x0101:0x5605:0.0](https://devices.zwave-js.io/?jumpTo=0x011a:0x0101:0x5605:0.0)
      The Z-wave alliance reference in that device entry also appears to be only relevant to the older ZWN-RSM1 / ZWN-RSM2.
-   [ ] **No**

**Did this use to work before?**

-   [x] **Don't know**, this is a new device
-   [ ] **No**, it never worked anywhere
-   [ ] **Yes**, in: _(specify application with versions)_

**How are you using `node-zwave-js`**

-   [ ] `zwavejs2mqtt` (latest) docker image
-   [ ] `zwavejs2mqtt` (dev) docker image
-   [ ] `zwavejs2mqtt` Manual Docker build
    -   `node-zwave-js` branch: 
    -   `zwavejs2mqtt` branch: 
-   [ ] ioBroker.zwave2 adapter
-   [ ] `HomeAssistant` version XYZ
-   [ ] Pkg
-   [ ] Manual Docker build
    -   `node-zwave-js` branch: 
    -   `zwavejs2mqtt` branch: 
-   [ ] `node-red-contrib-zwave-js`
    -   Module version (double click node): 
-   [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github))
-   [x] Other: 
   Using yarn version of zwavejs2mqtt master branch from github.

**To Reproduce**

1. Perform inclusion with ZWN-RSM1-Plus device and observe that the product type and ID are incorrect in the zwavejs2mqtt dashboard.

**Additional context**

![PXL_20210611_131557155-downsized](https://user-images.githubusercontent.com/17855860/121695114-becedd80-ca98-11eb-8dcd-7643b8acb00a.jpg)

**Logfile:**
Let me know if this really needed for this issue and I'll provide.

**Comment by AlCalzone** [comment]
Do you have time to provide a PR for this?
