### ISSUE TITLE
Older Leviton VRCS1 not correctly detected due to missing product type in config.

### ISSUE THREAD

**Issue by pletch** [zwave-js/zwave-js#2836]
**Checklist:**

-   [x] My problem is **not** within Home Assistant or the ZWave JS integration. **Or:** a Home Assistant developer has told me to come here.
-   [x] My problem is **not** within ZWaveJS2MQTT. **Or:** a ZWaveJS2MQTT developer has told me to come here.
-   [x] I have checked the troubleshooting section and my problem is **not** described there.
-   [x] I have read the changelog and my problem was **not** mentioned there.

**Describe the bug**
Recently migrated from Vera Edge to this library for use with Home Assistant with ZooZ S2 Stick 700 Series .   Older generation Leviton VRCS1-1LZ scene controller is not correctly identified and comes up as unknown device.  The config definition needs to be updated to include productType 0x0901 in addition to the currently defined 0x0902.
[https://devices.zwave-js.io/?jumpTo=0x001d:0x0902:0x0215:0.0](https://devices.zwave-js.io/?jumpTo=0x001d:0x0902:0x0215:0.0)

**Device information**

Which device(s) is/are affected (manufacturer/model)?
Leviton VRCS1-1LZ  
What is/are the node IDs?
29-533-2305 (0x001d-0x0901-0x0215)

**Did you change anything?**

-   [ ] **Yes**: _(please describe)_
-   [x] **No**

**Did this use to work before?**

-   [x] **Don't know**, this is a new device
-   [ ] **No**, it never worked anywhere
-   [ ] **Yes**, in: _(specify application with versions)_

**How are you using `node-zwave-js`**

-   [ ] `zwavejs2mqtt` (latest) docker image
-   [ ] `zwavejs2mqtt` (dev) docker image
-   [ ] `zwavejs2mqtt` Manual Docker build
    -   `node-zwave-js` branch: 
    -   `zwavejs2mqtt` branch: 
-   [ ] ioBroker.zwave2 adapter
-   [ ] `HomeAssistant` version XYZ
-   [ ] Pkg
-   [ ] Manual Docker build
    -   `node-zwave-js` branch: 
    -   `zwavejs2mqtt` branch: 
-   [ ] `node-red-contrib-zwave-js`
    -   Module version (double click node): 
-   [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github))
-   [x] Other: Using yarn version of zwavejs2mqtt master branch from github.

**To Reproduce**

1. Include older generation Leviton VRCS1 and observe that it is not recognized as a known device in Zwavejs2mqtt dashboard.

**Additional context**

**Logfile:**
Let me know if this is really needed and i'll provide.

**Comment by AlCalzone** [comment]
Yup, that seems straightforward. Accepting a PR (or I'll do it when I find the time).
