### ISSUE TITLE
Fibaro devices not always correctly shown

### ISSUE THREAD

**Issue by rploeg** [zwave-js/zwave-js#2863]
See threat I created here: https://github.com/home-assistant/core/issues/51844

I use ZwaveJS integration in Homeassistant (core-2021.6.4) on a raspberry PI 4 with an AEONlabs USB zwave stick (gen5). I have the strange behaviour that some Fibaro devices are shown correctly and others not, like in the example below

![image](https://user-images.githubusercontent.com/49752333/122043382-936f2a00-cddb-11eb-8f8a-d77af20adafb.png)
 
All three have the same type of Fibaro plug, but only one is showing correctly Fibaro. I have done reconfigure, remove nodes and adding again, but no luck. 

Here the log files of the integration within Home Assistant:

[zwave_js_dump.log](https://github.com/zwave-js/node-zwave-js/files/6655124/zwave_js_dump.log)

**Comment by AlCalzone** [comment]
Please use the **bug report** template and fill it out completely.
