### ISSUE TITLE
[bug] Detect serial disconnection

### ISSUE THREAD

**Issue by asystentka-jolka** [zwave-js/zwave-js#2873]
### Version

zwavejs2mqtt: 5.0.4.ebfd0b3
zwave-js: 7.7.5
home id: 4266870589
home hex: 0xfe53473d

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ ] Docker
- [ ] PKG
- [ ] Snap package
- [x] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 5.0.4.ebfd0b3
zwave-js version: 7.7.5

### Describe the bug

the health is still OK event when the adapter is disconnected (not in the /dev/ttyACM... )

### To Reproduce

1. Check the health without service

```
curl localhost:8091/health -H "Accept: text/plain" -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* connect to 127.0.0.1 port 8091 failed: Connection refused
* Failed to connect to localhost port 8091: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 8091: Connection refused
```
OK

2. Start service without adapter connected
```
yarn start
``` 

OK 

3. Check the health
```
curl localhost:8091/health -H "Accept: text/plain"
Error
```

OK

4. Connect the adapter wait a minute and check health

```
curl localhost:8091/health -H "Accept: text/plain"
Ok
```

OK

5. Remove the adapter wait x minutes and check health

```
curl localhost:8091/health -H "Accept: text/plain"
Ok
```

NOK

### Expected behavior

After removing adapter the health should be Error 

### Additional context

I'm trying to add to my app some info about problem with zWave adapter connection. 
In zigbee2mqtt it can be easy done via mqtt -> ``state_topic: "zigbee2mqtt/bridge/state"``

![image](https://user-images.githubusercontent.com/43966761/122426863-e2aa8b80-cf90-11eb-9fbc-6361b6093960.png)

Is there any way (via mqtt or http) to have the real status about zwave?

 :pray:  Thanks 

BTW
this is the greatest web app I ever saw :+1:

**Comment by robertsLando** [comment]
I think you could use serialport `close` [event](https://serialport.io/docs/api-stream#close) to handle this and check if `err.disconnect = true` 

Wouyld be also good to catch serialport `error` event and log them

Seems you are already catching `close` event [here](https://github.com/zwave-js/node-zwave-js/blob/master/packages/serial/src/ZWaveSocket.ts#L20) but I think that the check should use `err.disconnected` istead of checking `_isOpen`
