### ISSUE TITLE
Zwaveproducts.com/Zlink WD-100   doesn't ever respond with updated values after turning on or off

### ISSUE THREAD

**Issue by continuousmining** [zwave-js/zwave-js#2908]
I have several Zwaveproducts.com/Zlink WD-100 Dimmers which is the same hardware as the HomeSeer HS-WD100+'s however they don't ever respond with a status after toggling the switch.   It always goes on and the flicks right back to off.  

2021-06-25T01:25:38.613Z SERIAL » 0x010e001308076c0181032601ff2506f9                                  (16 bytes)
2021-06-25T01:25:38.614Z DRIVER » [Node 008] [REQ] [SendData]
                                  │ transmit options: 0x25
                                  │ callback id:      6
                                  └─[SupervisionCCGet]
                                    │ session id:      1
                                    │ request updates: true
                                    └─[MultilevelSwitchCCSet]
                                        target value: 255
2021-06-25T01:25:38.621Z SERIAL « [ACK]                                                                   (0x06)
2021-06-25T01:25:38.628Z SERIAL « 0x0104011301e8                                                       (6 bytes)
2021-06-25T01:25:38.629Z SERIAL » [ACK]                                                                   (0x06)
2021-06-25T01:25:38.629Z DRIVER « [RES] [SendData]
                                    was sent: true
2021-06-25T01:25:38.648Z SERIAL « 0x011800130600000200c47f7f7f7f000003000000000301000035              (26 bytes)
2021-06-25T01:25:38.649Z SERIAL » [ACK]                                                                   (0x06)
2021-06-25T01:25:38.649Z DRIVER « [REQ] [SendData]
                                    callback id:     6
                                    transmit status: OK
2021-06-25T01:25:38.665Z SERIAL « 0x010d00040008056c02010000c40050                                    (15 bytes)
2021-06-25T01:25:38.667Z SERIAL » [ACK]                                                                   (0x06)
2021-06-25T01:25:38.668Z DRIVER « [Node 008] [REQ] [ApplicationCommand]
                                  └─[SupervisionCCReport]
                                      session id:          1
                                      more updates follow: false
                                      status:              NoSupport
                                      duration:            0s

**Comment by AlCalzone** [comment]
Please re-interview the device, create a logfile and **attach** it here as a file.

**Comment by continuousmining** [comment]
Here you go.  It is a zwaveproducts.com / ZLink WD-100 Switch

[ZlinkWD-100.log](https://github.com/zwave-js/node-zwave-js/files/6718789/ZlinkWD-100.log)

**Comment by AlCalzone** [comment]
Guess I should have been more specific - loglevel **debug** please and upload the actual logfile, not some weird console redirection which messes up all special characters:
https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report?id=driver-logs

**Comment by continuousmining** [comment]
[WD-100 Zwave Logs.zip](https://github.com/zwave-js/node-zwave-js/files/6719429/WD-100.Zwave.Logs.zip)

Here you go!  Thank you!

**Comment by AlCalzone** [comment]
@zwave-js-bot add compat flag to `0x0315:0x4447:0x3034:0.0`
```json
"commandClasses": {
	"remove": {
		"0x6c": {
			// The device does not support supervision although it is mandatory for the device type
			"endpoints": "*"
		}
	}
}
```

**Comment by AlCalzone** [comment]
@zwave-js-bot add compat flag to 0x0315:0x4447:0x3034:0.0
```json
"commandClasses": {
	"remove": {
		"0x6c": {
			// The device does not support supervision although it is mandatory for the device type
			"endpoints": "*"
		}
	}
}
```

**Comment by AlCalzone** [comment]
@continuousmining do you have a chance to test this config file?
https://raw.githubusercontent.com/zwave-js/node-zwave-js/add-compat-flag-1624740612/packages/config/config/devices/0x0315/wd-100.json

The process is described here:
https://zwave-js.github.io/zwavejs2mqtt/#/development/intro?id=testing-custom-devices-config

**Comment by continuousmining** [comment]
I tried but how do I do this running Home Assistant ?

**Comment by AlCalzone** [comment]
Apparently that's not possible (yet). You'll have to use the zwavejs2mqtt addon.

**Comment by continuousmining** [comment]
I am.. but I can’t edit the driver file I create.

**Comment by AlCalzone** [comment]
Hmm, can you upload the complete file there?

**Comment by continuousmining** [comment]
No, I can't.

**Comment by AlCalzone** [comment]
Okay then... I'll merge this and you can report back after the next update.

**Comment by continuousmining** [comment]
Awesome, thanks!

**Comment by AlCalzone** [comment]
FYI, zwave-js 7.10.0 is **not** the update that includes this.

**Comment by continuousmining** [comment]
I got it working!  Thx a lot it works great!

**Comment by AlCalzone** [comment]
What did you do? Would be good if I have something to link other HA users to
