### ISSUE TITLE
[bug] Danalock square BTZW125 - wrong device config loaded

### ISSUE THREAD

**Issue by kfazon** [zwave-js/zwave-js#2916]
After adding this danalock lock it loads the wrong device config. The link to zwavejs db on Device ID
270-2-3 (0x010e-0x0003-0x0002) is ok and there is a right config in zwavejs database. But the loaded cofig is from an unknown lock

**Comment by AlCalzone** [comment]
@kfazon we need some more info to diagnose. What config gets loaded?

**Comment by kfazon** [comment]
I do not know from witch lock is it.. Here is the code from debug info.. 
Here is the link from what should have been loaded (https://devices.zwave-js.io/?jumpTo=0x010e:0x0003:0x0002:2.4)

This is loaded:

{
  "id": 9,
  "name": "Vjezbaona Vrata Lock",
  "loc": "Vjezbaona",
  "values": [
    {
      "id": "9-98-0-currentMode",
      "nodeId": 9,
      "commandClass": 98,
      "commandClassName": "Door Lock",
      "endpoint": 0,
      "property": "currentMode",
      "propertyName": "currentMode",
      "type": "number",
      "readable": true,
      "writeable": false,
      "label": "Current lock mode",
      "stateless": false,
      "min": 0,
      "max": 255,
      "list": true,
      "states": [
        {
          "text": "Unsecured",
          "value": 0
        },
        {
          "text": "UnsecuredWithTimeout",
          "value": 1
        },
        {
          "text": "InsideUnsecured",
          "value": 16
        },
        {
          "text": "InsideUnsecuredWithTimeout",
          "value": 17
        },
        {
          "text": "OutsideUnsecured",
          "value": 32
        },
        {
          "text": "OutsideUnsecuredWithTimeout",
          "value": 33
        },
        {
          "text": "Unknown",
          "value": 254
        },
        {
          "text": "Secured",
          "value": 255
        }
      ],
      "isCurrentValue": true,
      "targetValue": "98-0-targetMode"
    },
    {
      "id": "9-98-0-targetMode",
      "nodeId": 9,
      "commandClass": 98,
      "commandClassName": "Door Lock",
      "endpoint": 0,
      "property": "targetMode",
      "propertyName": "targetMode",
      "type": "number",
      "readable": true,
      "writeable": true,
      "label": "Target lock mode",
      "stateless": false,
      "min": 0,
      "max": 255,
      "list": true,
      "states": [
        {
          "text": "Unsecured",
          "value": 0
        },
        {
          "text": "UnsecuredWithTimeout",
          "value": 1
        },
        {
          "text": "InsideUnsecured",
          "value": 16
        },
        {
          "text": "InsideUnsecuredWithTimeout",
          "value": 17
        },
        {
          "text": "OutsideUnsecured",
          "value": 32
        },
        {
          "text": "OutsideUnsecuredWithTimeout",
          "value": 33
        },
        {
          "text": "Unknown",
          "value": 254
        },
        {
          "text": "Secured",
          "value": 255
        }
      ]
    },
    {
      "id": "9-98-0-outsideHandlesCanOpenDoor",
      "nodeId": 9,
      "commandClass": 98,
      "commandClassName": "Door Lock",
      "endpoint": 0,
      "property": "outsideHandlesCanOpenDoor",
      "propertyName": "outsideHandlesCanOpenDoor",
      "type": "any",
      "readable": true,
      "writeable": false,
      "label": "Which outside handles can open the door (actual status)",
      "stateless": false,
      "list": false
    },
    {
      "id": "9-98-0-insideHandlesCanOpenDoor",
      "nodeId": 9,
      "commandClass": 98,
      "commandClassName": "Door Lock",
      "endpoint": 0,
      "property": "insideHandlesCanOpenDoor",
      "propertyName": "insideHandlesCanOpenDoor",
      "type": "any",
      "readable": true,
      "writeable": false,
      "label": "Which inside handles can open the door (actual status)",
      "stateless": false,
      "list": false
    },
    {
      "id": "9-98-0-latchStatus",
      "nodeId": 9,
      "commandClass": 98,
      "commandClassName": "Door Lock",
      "endpoint": 0,
      "property": "latchStatus",
      "propertyName": "latchStatus",
      "type": "any",
      "readable": true,
      "writeable": false,
      "label": "The current status of the latch",
      "stateless": false,
      "list": false
    },
    {
      "id": "9-98-0-boltStatus",
      "nodeId": 9,
      "commandClass": 98,
      "commandClassName": "Door Lock",
      "endpoint": 0,
      "property": "boltStatus",
      "propertyName": "boltStatus",
      "type": "any",
      "readable": true,
      "writeable": false,
      "label": "The current status of the bolt",
      "stateless": false,
      "list": false
    },
    {
      "id": "9-98-0-doorStatus",
      "nodeId": 9,
      "commandClass": 98,
      "commandClassName": "Door Lock",
      "endpoint": 0,
      "property": "doorStatus",
      "propertyName": "doorStatus",
      "type": "any",
      "readable": true,
      "writeable": false,
      "label": "The current status of the door",
      "stateless": false,
      "list": false
    },
    {
      "id": "9-98-0-lockTimeout",
      "nodeId": 9,
      "commandClass": 98,
      "commandClassName": "Door Lock",
      "endpoint": 0,
      "property": "lockTimeout",
      "propertyName": "lockTimeout",
      "type": "number",
      "readable": true,
      "writeable": false,
      "label": "Seconds until lock mode times out",
      "stateless": false,
      "list": false
    },
    {
      "id": "9-98-0-operationType",
      "nodeId": 9,
      "commandClass": 98,
      "commandClassName": "Door Lock",
      "endpoint": 0,
      "property": "operationType",
      "propertyName": "operationType",
      "type": "number",
      "readable": true,
      "writeable": true,
      "label": "Lock operation type",
      "stateless": false,
      "min": 0,
      "max": 255,
      "list": true,
      "states": [
        {
          "text": "Constant",
          "value": 1
        },
        {
          "text": "Timed",
          "value": 2
        }
      ]
    },
    {
      "id": "9-98-0-outsideHandlesCanOpenDoorConfiguration",
      "nodeId": 9,
      "commandClass": 98,
      "commandClassName": "Door Lock",
      "endpoint": 0,
      "property": "outsideHandlesCanOpenDoorConfiguration",
      "propertyName": "outsideHandlesCanOpenDoorConfiguration",
      "type": "any",
      "readable": true,
      "writeable": true,
      "label": "Which outside handles can open the door (configuration)",
      "stateless": false,
      "list": false
    },
    {
      "id": "9-98-0-insideHandlesCanOpenDoorConfiguration",
      "nodeId": 9,
      "commandClass": 98,
      "commandClassName": "Door Lock",
      "endpoint": 0,
      "property": "insideHandlesCanOpenDoorConfiguration",
      "propertyName": "insideHandlesCanOpenDoorConfiguration",
      "type": "any",
      "readable": true,
      "writeable": true,
      "label": "Which inside handles can open the door (configuration)",
      "stateless": false,
      "list": false
    },
    {
      "id": "9-98-0-lockTimeoutConfiguration",
      "nodeId": 9,
      "commandClass": 98,
      "commandClassName": "Door Lock",
      "endpoint": 0,
      "property": "lockTimeoutConfiguration",
      "propertyName": "lockTimeoutConfiguration",
      "type": "number",
      "readable": true,
      "writeable": true,
      "label": "Duration of timed mode in seconds",
      "stateless": false,
      "min": 0,
      "max": 65535,
      "list": false
    },
    {
      "id": "9-114-0-manufacturerId",
      "nodeId": 9,
      "commandClass": 114,
      "commandClassName": "Manufacturer Specific",
      "endpoint": 0,
      "property": "manufacturerId",
      "propertyName": "manufacturerId",
      "type": "number",
      "readable": true,
      "writeable": false,
      "label": "Manufacturer ID",
      "stateless": false,
      "min": 0,
      "max": 65535,
      "list": false,
      "value": 270,
      "newValue": 270
    },
    {
      "id": "9-114-0-productType",
      "nodeId": 9,
      "commandClass": 114,
      "commandClassName": "Manufacturer Specific",
      "endpoint": 0,
      "property": "productType",
      "propertyName": "productType",
      "type": "number",
      "readable": true,
      "writeable": false,
      "label": "Product type",
      "stateless": false,
      "min": 0,
      "max": 65535,
      "list": false,
      "value": 3,
      "newValue": 3
    },
    {
      "id": "9-114-0-productId",
      "nodeId": 9,
      "commandClass": 114,
      "commandClassName": "Manufacturer Specific",
      "endpoint": 0,
      "property": "productId",
      "propertyName": "productId",
      "type": "number",
      "readable": true,
      "writeable": false,
      "label": "Product ID",
      "stateless": false,
      "min": 0,
      "max": 65535,
      "list": false,
      "value": 2,
      "newValue": 2
    },
    {
      "id": "9-134-0-libraryType",
      "nodeId": 9,
      "commandClass": 134,
      "commandClassName": "Version",
      "endpoint": 0,
      "property": "libraryType",
      "propertyName": "libraryType",
      "type": "any",
      "readable": true,
      "writeable": false,
      "label": "Library type",
      "stateless": false,
      "list": false,
      "value": 3,
      "newValue": 3
    },
    {
      "id": "9-134-0-protocolVersion",
      "nodeId": 9,
      "commandClass": 134,
      "commandClassName": "Version",
      "endpoint": 0,
      "property": "protocolVersion",
      "propertyName": "protocolVersion",
      "type": "any",
      "readable": true,
      "writeable": false,
      "label": "Z-Wave protocol version",
      "stateless": false,
      "list": false,
      "value": "2.78",
      "newValue": "2.78"
    },
    {
      "id": "9-134-0-firmwareVersions",
      "nodeId": 9,
      "commandClass": 134,
      "commandClassName": "Version",
      "endpoint": 0,
      "property": "firmwareVersions",
      "propertyName": "firmwareVersions",
      "type": "any",
      "readable": true,
      "writeable": false,
      "label": "Z-Wave chip firmware versions",
      "stateless": false,
      "list": false,
      "value": [
        "2.4"
      ],
      "lastUpdate": 1624864564246,
      "newValue": [
        "2.4"
      ]
    },
    {
      "id": "9-128-0-level",
      "nodeId": 9,
      "commandClass": 128,
      "commandClassName": "Battery",
      "endpoint": 0,
      "property": "level",
      "propertyName": "level",
      "type": "number",
      "readable": true,
      "writeable": false,
      "label": "Battery level",
      "stateless": false,
      "min": 0,
      "max": 100,
      "unit": "%",
      "list": false,
      "value": 0,
      "newValue": 0
    },
    {
      "id": "9-128-0-isLow",
      "nodeId": 9,
      "commandClass": 128,
      "commandClassName": "Battery",
      "endpoint": 0,
      "property": "isLow",
      "propertyName": "isLow",
      "type": "boolean",
      "readable": true,
      "writeable": false,
      "label": "Low battery level",
      "stateless": false,
      "list": false,
      "value": false,
      "newValue": false
    }
  ],
  "groups": [],
  "neighbors": [],
  "ready": true,
  "available": true,
  "hassDevices": {},
  "failed": false,
  "inited": true,
  "hexId": "0x010e-0x0003-0x0002",
  "dbLink": "https://devices.zwave-js.io/?jumpTo=0x010e:0x0003:0x0002:2.4",
  "manufacturerId": 270,
  "productId": 2,
  "productType": 3,
  "productLabel": "BTZW125",
  "productDescription": "Danalock v2 circle",
  "manufacturer": "Poly-control",
  "firmwareVersion": "2.4",
  "protocolVersion": 2,
  "nodeType": 1,
  "endpointsCount": 0,
  "endpointIndizes": [],
  "isSecure": false,
  "supportsSecurity": false,
  "supportsBeaming": true,
  "isControllerNode": false,
  "isListening": false,
  "isFrequentListening": "1000ms",
  "isRouting": true,
  "keepAwake": false,
  "maxDataRate": 40000,
  "deviceClass": {
    "basic": 4,
    "generic": 64,
    "specific": 2
  },
  "deviceId": "270-2-3",
  "status": "Alive",
  "interviewStage": "Complete",
  "lastActive": 1624864564246,
  "healProgress": "done",
  "_name": "Vjezbaona Vrata Lock (Vjezbaona)"
}

**Comment by kfazon** [comment]
And this should be in config lines..
https://github.com/zwave-js/node-zwave-js/blob/master/packages/config/config/devices/0x010e/btzw125.json

**Comment by blhoward2** [comment]
A log of the interview would be much more helpful. Please do so at the debug level and then post.

**Comment by kfazon** [comment]
I started reinterview and this is debug of this node during reinterview

2021-06-28 15:07:28.362 INFO ZWAVE: Calling api refreshInfo with args: [ 9, [length]: 1 ]
2021-06-28 15:07:28.380 INFO ZWAVE: Node 9: interview started
2021-06-28 15:07:28.384 INFO ZWAVE: Success zwave api call refreshInfo undefined
2021-06-28 15:07:28.409 INFO ZWAVE: Node 9: interview stage PROTOCOLINFO completed
2021-06-28 15:07:29.680 INFO ZWAVE: Node 9: interview stage NODEINFO completed
2021-06-28 15:07:39.864 INFO ZWAVE: Node 9: value added: 114-0-manufacturerId => 270
2021-06-28 15:07:39.867 INFO ZWAVE: Node 9: value added: 114-0-productType => 3
2021-06-28 15:07:39.868 INFO ZWAVE: Node 9: value added: 114-0-productId => 2
2021-06-28 15:07:39.961 INFO ZWAVE: Node 9: value added: 134-0-libraryType => 3
2021-06-28 15:07:39.962 INFO ZWAVE: Node 9: value added: 134-0-protocolVersion => 2.78
2021-06-28 15:07:39.963 INFO ZWAVE: Node 9: value added: 134-0-firmwareVersions => 2.4
2021-06-28 15:07:40.440 INFO ZWAVE: Node 9: value added: 128-0-level => 0
2021-06-28 15:07:40.442 INFO ZWAVE: Node 9: value added: 128-0-isLow => false
2021-06-28 15:08:00.543 INFO ZWAVE: Node 9: interview stage COMMANDCLASSES completed
2021-06-28 15:08:00.545 INFO ZWAVE: Node 9: interview stage OVERWRITECONFIG completed
2021-06-28 15:08:00.577 INFO ZWAVE: Node 9: interview stage NEIGHBORS completed
2021-06-28 15:08:00.579 INFO ZWAVE: Node 9: interview stage COMPLETE completed
2021-06-28 15:08:00.585 INFO ZWAVE: Node 9: value added 9-98-0-currentMode => undefined
2021-06-28 15:08:00.585 INFO ZWAVE: Node 9: value added 9-98-0-targetMode => undefined
2021-06-28 15:08:00.587 INFO ZWAVE: Node 9: value added 9-98-0-outsideHandlesCanOpenDoor => undefined
2021-06-28 15:08:00.587 INFO ZWAVE: Node 9: value added 9-98-0-insideHandlesCanOpenDoor => undefined
2021-06-28 15:08:00.588 INFO ZWAVE: Node 9: value added 9-98-0-latchStatus => undefined
2021-06-28 15:08:00.588 INFO ZWAVE: Node 9: value added 9-98-0-boltStatus => undefined
2021-06-28 15:08:00.589 INFO ZWAVE: Node 9: value added 9-98-0-doorStatus => undefined
2021-06-28 15:08:00.589 INFO ZWAVE: Node 9: value added 9-98-0-lockTimeout => undefined
2021-06-28 15:08:00.589 INFO ZWAVE: Node 9: value added 9-98-0-operationType => undefined
2021-06-28 15:08:00.590 INFO ZWAVE: Node 9: value added 9-98-0-outsideHandlesCanOpenDoorConfiguration => undefined
2021-06-28 15:08:00.590 INFO ZWAVE: Node 9: value added 9-98-0-insideHandlesCanOpenDoorConfiguration => undefined
2021-06-28 15:08:00.590 INFO ZWAVE: Node 9: value added 9-98-0-lockTimeoutConfiguration => undefined
2021-06-28 15:08:00.591 INFO ZWAVE: Node 9: value added 9-114-0-manufacturerId => 270
2021-06-28 15:08:00.591 INFO ZWAVE: Node 9: value added 9-114-0-productType => 3
2021-06-28 15:08:00.592 INFO ZWAVE: Node 9: value added 9-114-0-productId => 2
2021-06-28 15:08:00.592 INFO ZWAVE: Node 9: value added 9-134-0-libraryType => 3
2021-06-28 15:08:00.592 INFO ZWAVE: Node 9: value added 9-134-0-protocolVersion => 2.78
2021-06-28 15:08:00.593 INFO ZWAVE: Node 9: value added 9-134-0-firmwareVersions => 2.4
2021-06-28 15:08:00.593 INFO ZWAVE: Node 9: value added 9-128-0-level => 0
2021-06-28 15:08:00.594 INFO ZWAVE: Node 9: value added 9-128-0-isLow => false
2021-06-28 15:08:00.595 INFO ZWAVE: Node 9 ready: Poly-control - BTZW125 (Danalock v2 circle)
2021-06-28 15:08:00.599 INFO ZWAVE: Node 9: interview COMPLETED, all values are updated

**Comment by blhoward2** [comment]
That's not the debug level logging. That's INFO level. And please post it in a file and attach it. No one can read pages long, unformatted posts.

**Comment by AlCalzone** [comment]
I need the [driver logs](https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report?id=driver-logs) to be sure, but this looks terribly like you have no network key configured (or a different one than on the lock), or included the lock insecurely.

**Comment by kfazon** [comment]
I fixed by secure add.. It was not secure added because it did not go. Tried over 10 times and then added insecure. in 1st attempt.. 
I excluded it and now It succeeded to secure add on 6th or 7th attempt.. 

Thank you for your time
