### ISSUE TITLE
Missing config: Heatit ZM Single Relay 16A

### ISSUE THREAD

**Issue by henrikeri** [zwave-js/zwave-js#2924]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Heatit ZM Single Relay 16A

### Manufacturer ID

0x019b

### Product Type

0x0004

### Product ID

0x3500

### Firmware Version

1.0

### Do you have a manual?

[1651.pdf](https://github.com/zwave-js/node-zwave-js/files/6735554/1651.pdf)

**Comment by henrikeri** [comment]
@AlCalzone, could this potentially be auto-generated from the zwave alliance db as it exists there (https://products.z-wavealliance.org/products/4062)?

**Comment by AlCalzone** [comment]
Yeah we can do that. The resulting file needs to be manually cleaned up to match our style guide though. If you want to help out, you can make a PR onto the PR our bot is going to create in a minute.

@zwave-js-bot import config 4062 from zwa

**Comment by henrikeri** [comment]
@AlCalzone, done. Although bear in mind it's my first PR if I messed something up :)

**Comment by AlCalzone** [comment]
I've left you a few comments in the PR
