### ISSUE TITLE
Philio PST02 4 in 1 Sensor 

### ISSUE THREAD

**Issue by alireza44907** [zwave-js/zwave-js#2930]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

YES, BUT a Home Assistant developer has told me to come here

### Is your problem within ZWaveJS2MQTT?

YES, BUT a ZWaveJS2MQTT developer has told me to come here

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug? I included PST02A to home assistant running Z-Wave JS driver

What do you observe?
Motion sensor and Door/Window sensor do not work.
Motion sensor detects the first motion and then it remains detected. Also Door/Window sensor does not work at all. but all other sensors are okay.

What did you expect to happen?

All sensors work fine

  2. Click on '...'
  3. Scroll down to '...'

### Device information

Manufacturer:  Philio Technology Corp
Model name: PST02A
Node ID in your network: 14

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch:0.1.28 
`zwavejs2mqtt` branch:
Z-Wave JS
Current version: 0.1.28 (Changelog)
Control a ZWave network with Home Assistant Z-Wave JS.
Visit the Z-Wave JS page for more details

### Did you change anything?

yes (please describe)

### If yes, what did you change?

I tested the device by setting Parameter 7 to 2,6,16,18,22 but nothing happend

### Did this work before?

Yes (please describe)

### If yes, where did it work?

I read on the net that changing parameter 7 had worked

### Attach Driver Logfile

[param 7 set to 18.txt](https://github.com/zwave-js/node-zwave-js/files/6746007/param.7.set.to.18.txt)
[param 7 set to 16.txt](https://github.com/zwave-js/node-zwave-js/files/6746008/param.7.set.to.16.txt)
[pst02 HA.txt](https://github.com/zwave-js/node-zwave-js/files/6746009/pst02.HA.txt)
[param 7 set to 6.txt](https://github.com/zwave-js/node-zwave-js/files/6746010/param.7.set.to.6.txt)

**Comment by AlCalzone** [comment]
Sorry I missed this somehow. The logfiles you attached are not on loglevel "debug", so they aren't helpful. Please make a new one, ensure it is on the correct loglevel and trigger the sensors so we can see if and what gets sent.

> Motion sensor detects the first motion and then it remains detected.

If the device does not reset the motion status on its own, we need to add a compat flag. I want to verify with the log first though.
