### ISSUE TITLE
Missing Device Configuration: Neo Coolcam NAS-PD07Z Motion Sensor

### ISSUE THREAD

**Issue by madrose** [zwave-js/zwave-js#2969]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Shenzhen Neo Electronics Co., Ltd. PIR Motion Sensor 5in1

### Manufacturer ID

0x0258

### Product Type

0x20

### Product ID

0x0720

### Firmware Version

2.6

### Is the device listed on the Z-Wave Alliance website?

NO

### Do you have a manual?

I got the manual and I am attaching it. 
[motion 5in1 manual（20200602）(1).docx](https://github.com/zwave-js/node-zwave-js/files/6758340/motion.5in1.manual.20200602.1.docx)

**Comment by madrose** [comment]
There is 2 additional products as well that are new from the same company.
I am attaching them here so they can be also included in the approved devices.
[Repeater User Manual(20210407).docx](https://github.com/zwave-js/node-zwave-js/files/6758343/Repeater.User.Manual.20210407.docx)
[SmartPlug User Manual（20200620）.docx](https://github.com/zwave-js/node-zwave-js/files/6758344/SmartPlug.User.Manual.20200620.docx)

**Comment by AlCalzone** [comment]
If anyone wants to try his/her hand at a PR, go ahead. That will speed things up.

**Comment by luzik** [comment]
@madrose - config based on documentation is released. Please confirm that default values match those from documentation. In my case with firmware 2.6 the did not. Please look at
https://github.com/zwave-js/node-zwave-js/pull/3422/commits/6864c0e2e8b828682c203397732dd6ef97143473
and confirm or deny that your hardware is also affecting this mismatch between hardware and documentation.

You can also just paste logs from refresh configuration command.

If you are already upgrading from older release, you have to re-interview node to see new configuration options

**Comment by AlCalzone** [comment]
fixed by https://github.com/zwave-js/node-zwave-js/pull/3343
