### ISSUE TITLE
Missing device configuration: Aibase Water Leak Sensor, ZWA ID 2906

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#3052]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

Aibase Water Leak Sensor, ZWA ID 2906

### Manufacturer ID

0x0384

### Product Type

0x0200

### Product ID

0x000a

### Firmware Version

2.7

### Do you have a manual?

Reported by Telemetry:

capability | value
-- | --
associationGroups | ["Lifeline","Basic set"]
supportsAGI | true
supportsConfigCCV3 | false
supportsZWavePlus | true
zWavePlusVersion | 1

**Comment by AlCalzone** [comment]
If anyone plans on helping out with this file, please read https://zwave-js.github.io/node-zwave-js/#/config-files/using-telemetry-data first.

**Comment by blhoward2** [comment]
@zwave-js-bot import config 2906 from zwa
