### ISSUE TITLE
Aoetec HEM Gen5 configurationn missing

### ISSUE THREAD

**Issue by febalci** [zwave-js/zwave-js#3076]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What do you observe?
Updated zwavejs2mqtt from 4.x to 5.4.1; Aoetec HEM5 doesn't have configuration item neither in Home Assistant nor in Zwave Control Page. I only have meter values of clamps seperately but no Total Readings. I want to change 101-103 values but the configuration item to change these is missing... It was working fine previously on zwavejs2mqtt 4.x. Re-interviewed node several times but still the same.

### Device information

Manufacturer: Aoetec
Model name: Home Energy Meter Gen5 3 clamps
Node ID in your network: Node 29

### How are you using `node-zwave-js`?

- [X] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [ ] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: 8.0.4
`zwavejs2mqtt` branch: 5.4.1

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

Was working fine with zwavejs2mqtt 4.x

### Attach Driver Logfile

[node29.txt](https://github.com/zwave-js/node-zwave-js/files/6862539/node29.txt)

**Comment by AlCalzone** [comment]
Fixed in https://github.com/zwave-js/node-zwave-js/releases/tag/v8.0.5
A new zwavejs2mqtt version will be released soon.
