### ISSUE TITLE
Qubino 3 Phase Smart Meter missing configuration sheet

### ISSUE THREAD

**Issue by Thomasdmm** [zwave-js/zwave-js#3083]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

NO, my problem is NOT within Home Assistant or the ZWave JS integration

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
The device is include not secure include 
What do you observe?
i see manufacteur specific, version,basic, meters but i didn't find the configuration sheet
What did you expect to happen?
show the configuration sheet to set the parameter

### Device information

Manufacturer: Qubino
Model name: ZMNHXD1 3 Phase Smart Meter
Node ID in your network: 

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version:
`node-zwave-js` branch: 0.1.32
`zwavejs2mqtt` branch: 0.23.2

### Did you change anything?

no

### Did this work before?

No, it never worked anywhere

### Attach Driver Logfile

[log.txt](https://github.com/zwave-js/node-zwave-js/files/6868677/log.txt)

**Comment by AlCalzone** [comment]
We do have a config file: https://devices.zwave-js.io/?jumpTo=0x0159:0x0007:0x0054:4.11
So I guess something went wrong during the inclusion or the last re-interview. I can't tell what without a driver log of an interview though.
