### ISSUE TITLE
When endpoints have a Z-Wave+ lifeline with 0 max. nodes, setup a multi channel association on the root

### ISSUE THREAD

**Issue by je-mei** [zwave-js/zwave-js#3099]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

YES, BUT a Home Assistant developer has told me to come here

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

What causes the bug?
./.

What do you observe?
./.

What did you expect to happen?
Power-Entity available for FGR223 Fibaro Roller Shutter

  1. See result from home assistant / core issue: https://github.com/home-assistant/core/issues/53507

### Device information

Add-on with the issue: Z-Wave JS
Add-on release with the issue: 0.1.32
Last working add-on release (if known): included in home assistant the first first
Operating environment (OS/Supervised): Version core-2021.7.4, supervisor-2021.06.8, Home Assistant OS 6.1

-Roller shutter 2 working correctly, power entity existing
-another user uses the legacy zwave implementation, where the power entity also occurs

see https://github.com/home-assistant/core/issues/53507

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

Add-on with the issue: Z-Wave JS
Add-on release with the issue: 0.1.32
Last working add-on release (if known): included in home assistant the first first
Operating environment (OS/Supervised): Version core-2021.7.4, supervisor-2021.06.8, Home Assistant OS 6.1

### Did you change anything?

no

### If yes, what did you change?

- migrating from fhem to home assistant
- including process in fhem (here everythink ran fine)
- behavior from the beginning

### Did this work before?

Yes (please describe)

### If yes, where did it work?

- within fhem, zwave roller shutter completly useable
- legacy version of zwave runs with power entity
[zwave_2021-07-26_interview_fgr223.log](https://github.com/zwave-js/node-zwave-js/files/6887404/zwave_2021-07-26_interview_fgr223.log)
[zwave_config_legacy_integration_by_another_user_where_everything_works_fine_FGRM223_Roller_Shutter_Controller_3.txt](https://github.com/zwave-js/node-zwave-js/files/6887410/zwave_config_legacy_integration_by_another_user_where_everything_works_fine_FGRM223_Roller_Shutter_Controller_3.txt)

- Detailed Information, see: https://github.com/home-assistant/core/issues/53507, the developer from core asked me to get in contact with you, referring to the existing issue opened yesterday.

Kind regards
Jens

### Attach Driver Logfile

[zwave_config_legacy_integration_by_another_user_where_everything_works_fine_FGRM223_Roller_Shutter_Controller_3.txt](https://github.com/zwave-js/node-zwave-js/files/6887414/zwave_config_legacy_integration_by_another_user_where_everything_works_fine_FGRM223_Roller_Shutter_Controller_3.txt)
[zwave_2021-07-26_interview_fgr223.log](https://github.com/zwave-js/node-zwave-js/files/6887415/zwave_2021-07-26_interview_fgr223.log)

**Comment by kpine** [comment]
See my [latest comment](https://github.com/home-assistant/core/issues/53507#issuecomment-887680041) in the HA issue. Given the newly provided zwcfg*.xml file, I don't think there's any issue here.

**Comment by AlCalzone** [comment]
I agree, the device is using the `Meter CC` to report its consumption and I see it being queried successfully in the log.

**Comment by je-mei** [comment]
Hi AlCalzone,
hi kpine,

first of all thanks for your support! By the way I would like to mention, that some additional points are not clear for me:

1. Why is there a possibility for configurating "power reports", when they are not available in shutter 3 at all?

![image](https://user-images.githubusercontent.com/84464997/127349601-d5aed371-2dd5-41b3-b7e8-afb70c77b446.png)

2.
Unfortunately, values for "Roller Shutter 3: Electric Consumed [W]" will not be send, but the kwH do. I opened and closed my shutters, but thats not represented in the graphic/log:

![image](https://user-images.githubusercontent.com/84464997/127350058-27743d3d-1fcf-4aad-8df4-ad16f538532a.png)

![image](https://user-images.githubusercontent.com/84464997/127350099-f9a00d4e-0fa0-4208-b721-9a38ef73f4fd.png)

Kind regards
Jens

**Comment by je-mei** [comment]
update:
exclusion of shutter 3
factory reset of shutter 3
inclusion of shutter 3
same phenomenon: no reporting of electric consumed W

![image](https://user-images.githubusercontent.com/84464997/127376179-43eed729-3626-4814-b30f-38c6179d397e.png)

although mulitple open and close of the shutter, no reporting:
![image](https://user-images.githubusercontent.com/84464997/127376332-c3e5a1bd-b7fa-4ded-b076-d1fe7b6d6b6d.png)

**Comment by je-mei** [comment]
![image](https://user-images.githubusercontent.com/84464997/127376858-6fb5b43a-55b5-4aaf-9361-e4017b687be7.png)

**Comment by kpine** [comment]
3600 seconds is one hour for the periodic report. Have you tried reducing it to something like 1 minute to see if anything is reported?

**Comment by AlCalzone** [comment]
>     1. Why is there a possibility for configurating "power reports", when they are not available in shutter 3 at all?

I can't speak for how devices behave. Looking at the configuration you posted, the changes should come every 5W or 1%, depending on what is higher:
![grafik](https://user-images.githubusercontent.com/17641229/127397430-801ceaf9-8f56-41aa-a2c7-6c350ed50601.png)

If they don't appear in the UI, looking at the driver logs could give you a hint whether the reports are received at all. If they aren't, either the messages don't reach the controller (in which case a heal could help) or they never get sent (which you can only figure out with a Zniffer next to the shutters).

**Comment by je-mei** [comment]
change of energy repots didn't have any effect on reporting
therefore I checked system behavior when changing the values via log
error message based on "silly" log find attached

![image](https://user-images.githubusercontent.com/84464997/127445128-88888beb-15b2-4845-9194-5c184e83968f.png)

**Comment by AlCalzone** [comment]
Hm, looks like that log doesn't actually use the `silly` loglevel - there should be more. @kpine do you know more about that?

The mention of "Application Status" could mean that the device didn't actually accept the command

**Comment by kpine** [comment]
> Hm, looks like that log doesn't actually use the `silly` loglevel - there should be more. @kpine do you know more about that?

No, but it sounds like you got some attention in Discord. The funny thing is, we gathered the interview logs using the same procedure. That seemed to be successful. 🤷🏻‍♂️

**Comment by je-mei** [comment]
its really strange :-( :-(

I was using shutter 2+3 in fhem first. next to the known bug "send no update for position" it worked really fine. I used the power/electric reports to trigger a zwave-update for the whole sensor. similar like the blueprint. and it worked. 

so i directly switched from fhem (excluding) to ha (reset, incluing) within 1 day, so hardware couldn't be the root cause. :-(

just made another update of the configuration for you: 
change report "on change" and "periodic". Here is the result:

![image](https://user-images.githubusercontent.com/84464997/127530922-b0be4a3e-94ac-4fc3-8f0b-13ac0ad19ae9.png)


Network heal already done a few days ago and many times ... . But finally it is sending no update:

![image](https://user-images.githubusercontent.com/84464997/127531119-1f514b4f-482b-4813-8f6e-d4e6e36759b6.png)

Although open and close a minimum of twice a day.

By the way: Shutter 2 is also sending no energy, but power ;-)

![image](https://user-images.githubusercontent.com/84464997/127531334-dbc33004-b115-4a76-a399-d5d82a090e15.png)

shutter 2 sends only power, but no energy watt:
![image](https://user-images.githubusercontent.com/84464997/127531451-00c4404c-cf86-4ff4-a9c4-ca1cde8e00bc.png)
(screenshot during close progress)

![image](https://user-images.githubusercontent.com/84464997/127531727-5d2c63b4-9289-4bdc-aa47-b58a94169443.png)

![image](https://user-images.githubusercontent.com/84464997/127531782-62e34abe-f576-4db7-82f0-454225f33041.png)

If I could do anything to help give me some information what to do. 

Kind regards 
Jens

**Comment by je-mei** [comment]
did a configuration change for shutter 2

![image](https://user-images.githubusercontent.com/84464997/127532176-8fea2748-fe90-4390-9627-3a5df04da0db.png)

[zwave_js-log (2).txt](https://github.com/zwave-js/node-zwave-js/files/6902169/zwave_js-log.2.txt)

**Comment by je-mei** [comment]
thats all shutter 2:
![image](https://user-images.githubusercontent.com/84464997/127532499-694c992a-d9f5-42b2-8feb-aa716473331c.png)

**Comment by je-mei** [comment]
shutter 2:
![image](https://user-images.githubusercontent.com/84464997/127532703-ffcd65e8-36a5-4790-8223-131c4d091f34.png)

**Comment by AlCalzone** [comment]
> change report "on change" and "periodic". Here is the result:

Looks like the device doesn't like you changing the parameters. I think that is because you're setting an unsupported value for the periodic report. Only 0 and 30-32400 are allowed.
![grafik](https://user-images.githubusercontent.com/17641229/127557346-9adddf3c-aabe-4943-8439-3f6742278ac9.png)

I can confirm that my Roller Shutter 2 reports power via a **Multilevel Sensor (Power)** and **Electric Consumed [kWh]** with the configured frequency, but the **Electric Consumed [W]** never changes in the time it is moving. Maybe FHEM was polling? zwave-js doesn't do that automatically.

> next to the known bug "send no update for position" it worked really fine. I used the power/electric reports to trigger a zwave-update for the whole sensor

You do know that this isn't necessary in `zwave-js`, right? It uses the `Supervision CC` to get informed about the position changes of the Roller Shutter 3. Can you make a log where you move the Shutter 3?

**Comment by je-mei** [comment]
1. log during change of config for shutter 3
2. 2. log during many open and closes incusive a screenshot of the graphic / cover

[during_change_parameter_shutter3-log.txt](https://github.com/zwave-js/node-zwave-js/files/6906737/during_change_parameter_shutter3-log.txt)
![cover_after_open_closes_many_times](https://user-images.githubusercontent.com/84464997/127636583-5930e5f2-87dc-4931-9de3-929a96f60f5b.png)
![graphic_after_open_closes_many_times](https://user-images.githubusercontent.com/84464997/127636587-d33a101e-7eb9-4b07-ad35-9925040e0b9a.png)
[after_many_open_and_closes-log.txt](https://github.com/zwave-js/node-zwave-js/files/6906738/after_many_open_and_closes-log.txt)

**Comment by je-mei** [comment]
i will send you another log, where shutter is triggered by local shutter switch to open and close tomorrow if needed

**Comment by je-mei** [comment]
arghh :-/ not many information stored in the log, thats different to the information displayed. 

i will do it again tomorrow and copy data from screen into text file

**Comment by kpine** [comment]
@je-mei Are you using the log download button in HA, or copying and pasting from the window? The download button does not work properly, so you should copy and paste.

**Comment by je-mei** [comment]
@kpine yes, forgotten :-(. used copy and paste from the window instead. 

please find attached "silly" logs and corresponding screenshots (same number link 01_* means same progress)

[00_change-device-configuration.txt](https://github.com/zwave-js/node-zwave-js/files/6908690/00_change-device-configuration.txt)
![00_change_device_configuratoin](https://user-images.githubusercontent.com/84464997/127679064-c4d30c8d-eaa6-48ab-8bf7-ec7fb6730c3b.png)
![01_position_change_via_ha-](https://user-images.githubusercontent.com/84464997/127679084-ab9e29a4-c859-4377-8c46-669360cc0bb8.png)
[01_postition_change.txt](https://github.com/zwave-js/node-zwave-js/files/6908691/01_postition_change.txt)
![02_no_change_in_electric_consumed](https://user-images.githubusercontent.com/84464997/127679117-34881f5f-0cc0-4038-81b6-12c8381304c7.png)
![02_no_change_in_electric_consumed_developertools](https://user-images.githubusercontent.com/84464997/127679129-9215938f-0ae0-4464-9072-ce58f4bda9bf.png)
![02_no_change_in_electric_consumed2](https://user-images.githubusercontent.com/84464997/127679145-f98c8984-4a91-426b-9d78-ea603138924b.png)
![02_no_change_in_electric_consumed3](https://user-images.githubusercontent.com/84464997/127679162-87f67d02-e932-444f-a3b4-d52458c1124b.png)
[03_one_time_down_one_time_up_by_local_swith_shutter3.txt](https://github.com/zwave-js/node-zwave-js/files/6908695/03_one_time_down_one_time_up_by_local_swith_shutter3.txt)
![03_one_time_down_one_time_up_by_local_swith_shutter3](https://user-images.githubusercontent.com/84464997/127679189-4fee1e8a-57da-4b30-8bc2-2c66c3b9d66a.png)
![03_one_time_down_one_time_up_by_local_swith_shutter3_developertools](https://user-images.githubusercontent.com/84464997/127679204-998350d9-da50-4798-a9b2-b9da3c5fd183.png)

**Comment by kpine** [comment]
In your original HA dump file, the meter value is associated with endpoint one. In your zwave-js debug logs, endpoint 0 is reporting the meter values. This would mean HA wouldn't see the updates.
```
              {
                "endpoint": 1,
                "commandClass": 50,
                "commandClassName": "Meter",
                "property": "value",
                "propertyKey": 66049,
                "propertyName": "value",
                "propertyKeyName": "Electric_W_Consumed",
                "ccVersion": 3,
                "metadata": {
                  "type": "number",
                  "readable": true,
                  "writeable": false,
                  "label": "Electric Consumed [W]",
                  "ccSpecific": {
                    "meterType": 1,
                    "rateType": 1,
                    "scale": 2
                  },
                  "unit": "W"
                },
                "value": 0.6
              },
```

```
2021-07-30T15:45:13.338Z SERIAL « 0x0112000400200a32022132058a00000000b600d9                          (20 bytes)
2021-07-30T15:45:13.341Z CNTRLR   [Node 032] [~] [Meter] value[66049]: 0.6 => 141.8                 [Endpoint 0]
2021-07-30T15:45:13.343Z SERIAL » [ACK]                                                                   (0x06)
2021-07-30T15:45:13.345Z DRIVER « [Node 032] [REQ] [ApplicationCommand]
                                  └─[MeterCCReport]
                                      type:       Electric
                                      scale:      W
                                      rate type:  Consumed
                                      value:      141.8
                                      time delta: 0 seconds
```

Also, your original dump had the Shutter 3 as node 31, did you remove and add it? Could you provide a new dump file to confirm it's in the same situation?

**Comment by je-mei** [comment]
did you remove and add it --> yes, I did.  I did everything to get the shutter run ;-). 

here my new reports
1. reinterview 
2. down and up via local switch
3. down and up via HA

![00_reinterview](https://user-images.githubusercontent.com/84464997/127689878-9410d448-9c21-41fb-b65e-867bb97e9545.png)
[00_reinterview.txt](https://github.com/zwave-js/node-zwave-js/files/6909143/00_reinterview.txt)


####

![01_down_and_up_via_local_switch-](https://user-images.githubusercontent.com/84464997/127689903-1629a8a5-5247-4e79-adce-73409514daec.png)
[01_down_and_up_via_local_switch-.txt](https://github.com/zwave-js/node-zwave-js/files/6909146/01_down_and_up_via_local_switch-.txt)


####

![02_down_and_up_via_HA](https://user-images.githubusercontent.com/84464997/127689922-0d904140-bf7c-45a5-bc2b-2345c635dc4d.png)
[02_down_and_up_via_HA.txt](https://github.com/zwave-js/node-zwave-js/files/6909149/02_down_and_up_via_HA.txt)

**Comment by kpine** [comment]
Could you please provide the [network dump](https://www.home-assistant.io/integrations/zwave_js/#get-a-dump-of-the-current-network-state). I just wanted to confirm that HA still sees only values for endpoints 1 and 2.

**Comment by je-mei** [comment]
[zwave_js_dump-json.txt](https://github.com/zwave-js/node-zwave-js/files/6909244/zwave_js_dump-json.txt)

**Comment by kpine** [comment]
@AlCalzone looks like another case of values for endpoints 1, etc, but reports on endpoint 0?

**Comment by AlCalzone** [comment]
Yeah, that looks like another edge case for the association setup. The endpoints 1/2 share their lifeline with the root endpoint (max. no of nodes is 0), so it looks like they have a node association when they actually don't.

**Comment by je-mei** [comment]
hi, fyi - behaviour of my shutter 2 in addition.
I have only two shutters. one shutter 3 and one shutter 2. shutter 2 runs better, but maybe there is the same issue occuring, but the power entity is running great ;-)
[reinterview_shutter2.txt](https://github.com/zwave-js/node-zwave-js/files/6911133/reinterview_shutter2.txt)
[up_down_manually_via_local_shutter.txt](https://github.com/zwave-js/node-zwave-js/files/6911134/up_down_manually_via_local_shutter.txt)
[up_down_manually_via_local_shutter.txt](https://github.com/zwave-js/node-zwave-js/files/6911135/up_down_manually_via_local_shutter.txt)
[reinterview_shutter2.txt](https://github.com/zwave-js/node-zwave-js/files/6911136/reinterview_shutter2.txt)
[Screenshots_before_and_during_progress.pdf](https://github.com/zwave-js/node-zwave-js/files/6911137/Screenshots_before_and_during_progress.pdf)

**Comment by je-mei** [comment]
Roller Shutter 3 runs great now, thanks for your work!

Kind regards 
Jens
