### ISSUE TITLE
Add New Ecolink Siren

### ISSUE THREAD

**Issue by blhoward2** [zwave-js/zwave-js#3114]
ZWA ID: 4000

**Comment by blhoward2** [comment]
@zwave-js-bot import config 4000 from zwa

**Comment by blhoward2** [comment]
@AlCalzone What am I doing wrong here? Am I not authorized for bot commands anymore?

**Comment by blhoward2** [comment]
Nevermind, looks like we already have it.

**Comment by AlCalzone** [comment]
Botty is a bit slow:
![grafik](https://user-images.githubusercontent.com/17641229/127564445-63f47c65-dff5-4a3a-918f-60dbc2b87319.png)
