### ISSUE TITLE
FGS211/FGS221 not return status.

### ISSUE THREAD

**Issue by Ascariota** [zwave-js/zwave-js#3119]
### Is your problem within Home Assistant (Core or Z-Wave JS Integration)?

YES, BUT a Home Assistant developer has told me to come here

### Is your problem within ZWaveJS2MQTT?

NO, my problem is NOT within ZWaveJS2MQTT

### Checklist

- [X] I have checked the [troubleshooting section](https://zwave-js.github.io/node-zwave-js/#/troubleshooting/index) and my problem is **not** described there.

- [X] I have read the [changelog](https://github.com/zwave-js/node-zwave-js/blob/master/CHANGELOG.md) and my problem was **not** mentioned there.

### Describe the bug

Hello,
JS Zwave - FGS211 / FGS221 not return status

since the last update of JS Zwave (Current version: 0.1.32 ) my FGS211 / FGS221 not return the status of one switch.
He works but I don't know if is switch on or off.

Exactly the same issue I have in april : #48744

I open an issue : https://github.com/home-assistant/core/issues/53515
and after analysis "Kpine" told me to open a bug report to have help.

### Device information

Manufacturer:  Fibaro 
Model name: FGS211/FGS221
Node ID in your network: NODE 06

### How are you using `node-zwave-js`?

- [ ] `zwavejs2mqtt` Docker image (latest)
- [ ] `zwavejs2mqtt` Docker image (dev)
- [ ] `zwavejs2mqtt` Docker manually built _(please specify branches)_
- [ ] `ioBroker.zwave2` adapter _(please specify version)_
- [X] `HomeAssistant zwave_js` integration  _(please specify version)_
- [ ] `pkg`
- [ ] `node-red-contrib-zwave-js` _(please specify version, double click node to find out)_
- [ ] Manually built from GitHub _(please specify branch)_
- [ ] Other _(please describe)_

### Which branches or versions?

version: JS ZWAVE
Current version: 0.1.34 

CORE Version
core-2021.7.4

SUPERVISOR Version
supervisor-2021.06.8

### Did you change anything?

no

### Did this work before?

Yes (please describe)

### If yes, where did it work?

It's work before Udpate.

### Attach Driver Logfile

Log after a re-interviewing Node06.

[lognodeZw.txt](https://github.com/zwave-js/node-zwave-js/files/6905296/lognodeZw.txt)

**Comment by AlCalzone** [comment]
Thanks for the report. I think this is an edge case we haven't handled yet.

The node (endpoint 0) supports both Multi Channel and normal associations, but none of the extra endpoints do. By default, we try to setup normal associations on all endpoints and fall back to a multi channel association on endpoint 0 when it didn't work on the other endpoints.

However since setting up the associations on the extra endpoints never happens, this fallback doesn't happen either.

You can work around this for now by changing the association on the node (group 3) from target "Node 1" to "Node 1, Endpoint 0". Not sure if HA lets you do that yet, but zwavejs2mqtt will.

**Comment by Ascariota** [comment]
Hello, 
Thanks for the help, I use JS Zwave integrated and I can't change nothing :(

My work around is an automation every minute with a zwave_js.refresh_value.
It's not the best solution but waiting solution it's do the job.

**Comment by AlCalzone** [comment]
You can install the zwavejs2mqtt addon and use it for the change, then go back to the integration. They can be installed side-by-side, they just can't be running at the same time.

**Comment by Ascariota** [comment]
AlCalzone, ok ZwaveJs2Mqtt run :)

I try but not change
I'm not sure to understand well (my English is not perfect) it's correct like this : 

![noded](https://user-images.githubusercontent.com/25208125/127687573-d8b72d31-a112-4ed0-b32d-5153b3a8dbe2.JPG)


Thx

**Comment by AlCalzone** [comment]
@robertsLando shouldn't there be a target endpoint selection?

**Comment by robertsLando** [comment]
Target endpoint should be displayed under the target node but just if group `multiChannel` is true

**Comment by AlCalzone** [comment]
Based on the log the group is multi channel. Does a node dump include this info?

**Comment by robertsLando** [comment]
It should yeah. They are under `node.groups` array


Check: https://github.com/zwave-js/zwavejs2mqtt/blob/master/lib/ZwaveClient.ts#L721

**Comment by AlCalzone** [comment]
Ok, @Ascariota could you make a JSON dump of the node in question and upload it here?

**Comment by Ascariota** [comment]
@AlCalzone :  yes here a full Json dump
The nodeId of this device is "nodeId": 6 

Thx

[zwave_js_dump (3).txt](https://github.com/zwave-js/node-zwave-js/files/6917886/zwave_js_dump.3.txt)

**Comment by AlCalzone** [comment]
@robertsLando The association groups don't seem to be included there.

**Comment by kpine** [comment]
That's a dump from HA. Doesn't look like the zwave-js-server (and possibly Python module) exposes the groups.

**Comment by robertsLando** [comment]
The dump shouls be done from z2m interface

**Comment by Ascariota** [comment]
From Z2m

[node_6.txt](https://github.com/zwave-js/node-zwave-js/files/6918387/node_6.txt)

**Comment by kpine** [comment]
Unless I'm missing something, the z2m dump does not include the _defined_ associations either, it only shows the available groups.

**Comment by AlCalzone** [comment]
> if group `multiChannel` is true

Ok it looks like that is working correctly. That's not a Z-Wave+ device, and the lifeline is the last non-multichannel group. That means the fix I did doesn't actually affect this device.

**Comment by AlCalzone** [comment]
@Ascariota can you make another log where you just toggle the device so I can see if anything gets received at all?

**Comment by Ascariota** [comment]
Yes here the Silly Log

My action : 
Switch1 No return Status in HA
Switch2 Return Status in HA correctly
On the same device node 006

13:03 Switch Of Manually Switch 1 
13:04 Switch On Manually Switch 1
13:05 Switch Off Manually Switch 2
13:06 Switch On Manually Switch 2

[zwave_js (1).log](https://github.com/zwave-js/node-zwave-js/files/6923580/zwave_js.1.log)

**Comment by AlCalzone** [comment]
Okay, I know what's going on. Endpoint 1 reports via the root endpoint, so we need to map the reports back. This was changed to opt-in in v8.

PR is up in a few seconds.

**Comment by AlCalzone** [comment]
You can work around this until the release:
Take this file [fgs221_2.1-2.3.json.txt](https://github.com/zwave-js/node-zwave-js/files/6923666/fgs221_2.1-2.3.json.txt), rename it back to `.json` and put it in your user config dir in zwavejs2mqtt:
https://zwave-js.github.io/zwavejs2mqtt/#/development/intro?id=testing-custom-devices-config

After a restart, things should work again.

**Comment by Ascariota** [comment]
@AlCalzone : 
I'm not sure of the path : //root/config/custom_components/
I need to create a folder zwavejs2mqtt ?

![image](https://user-images.githubusercontent.com/25208125/128010572-c9d1c7d2-38a9-4e12-bc98-b008757384a0.png)

Big thx for help again :)

**Comment by AlCalzone** [comment]
Zwavejs2mqtt has a web UI that let's you manage files in its store directory.

**Comment by Ascariota** [comment]
I made a mistake ? 
![image](https://user-images.githubusercontent.com/25208125/128027451-1d18bb5b-b6c8-4fd7-9dfd-0a8afd2b6111.png)

After I reboot the complet HOST but nok.

I change the label 
"label": "Relay 1: Response to Water Flood Alarm"  to "label": "Relay 1: Response to Water Flood Alarma"  just to see if the news JSON is ok but I ZW2M I see the old label, so I sure I made a mistake with th json path/name... 

Sorry usually I'm not so noob.

**Comment by AlCalzone** [comment]
The driver log should show you at the start if it picked up the new file or the included one.

**Comment by kpine** [comment]
> 
> 
> You can work around this until the release:
> Take this file [fgs221_2.1-2.3.json.txt](https://github.com/zwave-js/node-zwave-js/files/6923666/fgs221_2.1-2.3.json.txt), rename it back to `.json` and put it in your user config dir in zwavejs2mqtt:
> https://zwave-js.github.io/zwavejs2mqtt/#/development/intro?id=testing-custom-devices-config
> 
> After a restart, things should work again.

@AlCalzone FYI, this attached file doesn't have the compat flag. I think [this](https://raw.githubusercontent.com/zwave-js/node-zwave-js/fd5460644c7a8e5d79959b0b0e06322d4c446b82/packages/config/config/devices/0x010f/fgs221_2.1-2.3.json) is the file?

**Comment by Ascariota** [comment]
@AlCalzone 

I try unistall and install again Zwave addon.
I put the file in the config folder.
Zwave run in HA I can use my devices, but the driver log 
Driver: Error Resource temporarily unavailable Cannot lock port.

And I think the JSON is not load.

The full log here

[zwavejs2mqtt.log](https://github.com/zwave-js/node-zwave-js/files/6929139/zwavejs2mqtt.log)

**Comment by AlCalzone** [comment]
Yeah, you're right. 🙈

**Comment by AlCalzone** [comment]
@Ascariota Cannot lock port means something else is blocking access.  Please make sure to use the file @kpine linked to, I uploaded the old one.

**Comment by Ascariota** [comment]
Ok 👍
