### ISSUE TITLE
Missing device configuration: ConnectHome CH-103

### ISSUE THREAD

**Issue by Seraph1m89** [zwave-js/zwave-js#3143]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

ConnectHome CH-103

### Manufacturer ID

0x0179

### Product Type

0x0041

### Product ID

0x0014

### Firmware Version

1.43

### Do you have a manual?

https://connecthome.com.ua/product/ch103
I can provide my custom config JSON file that is working for me. Unfortunately I can't run simple yarn commands to test out if my config is working as expected (getting various error messages)
[cn-103.pdf](https://github.com/zwave-js/node-zwave-js/files/6913323/cn-103.pdf)

**Comment by AlCalzone** [comment]
> I can provide my custom config JSON file that is working for me

You can make a PR with that, which will run the checks on Github.
