### ISSUE TITLE
Missing device configuration: Zipato PH-PSE02

### ISSUE THREAD

**Issue by docbobo** [zwave-js/zwave-js#3216]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

 Zipato PH-PSE02

### Manufacturer ID

0x0131

### Product Type

0x004

### Product ID

0x000a

### Firmware Version

1.15

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/2419

### Do you have a manual?

https://www.zipato.com/wp-content/uploads/2015/09/ph-pse02-Zipato-Siren-User-Manual-v1.2.pdf

Seems to be the same as the Devolo PH-PSE02

**Comment by AlCalzone** [comment]
This could be done the same way we do with Fantem and Aeotec devices (`$import` of the existing OEM's files).

**Comment by docbobo** [comment]
Does that require refactoring all parameters on the Devolo side into a templates file?

**Comment by docbobo** [comment]
Or would something like this also work?
`		"7[0x08]": {
			"$import": "~/0x0175/ph-pse02.json#paramInformation/7[0x08]"
		},
`

**Comment by AlCalzone** [comment]
Yep, I'd be fine with that as long as the files are almost 1:1 matches (in the case of identical devices under different labels/oems)
