### ISSUE TITLE
Request to invert covers in device settings

### ISSUE THREAD

**Issue by killtux** [zwave-js/zwave-js#3217]
**Is your feature request related to a problem? Please describe.**
I have a bunch of Fibaro Rolling Shutter v2 (FGR-222). I used them before in Homee and there was a setting to invert directions. looks like there isnt something in general for covers in z-wave js. If i press the "OPEN" switch in the control panel of the server it closes. If i press CLOSE it opens. Modules are wired correctly like described in the manual and the wall switches work correct too.

**Describe the solution you'd like**
Just add a "reverse directions" to Covers in z-wave JS control panel. some modules have that option included (like the FGR-223), some not.

there are some threads on the Home Assistant forums about this:
https://community.home-assistant.io/t/zwave-js-request-to-invert-covers/303156
https://community.home-assistant.io/t/zwave-js-invert-cover/296074

since the control is already false in the control panel of z-wave js server i would suggest to let the user make the correction there instead of adding a revert option in Home Assistant software.

![image](https://user-images.githubusercontent.com/36768145/130365200-ead98058-8825-47c9-8823-de43d22bd2dc.png)

**Comment by AlCalzone** [comment]
In the driver, I try to stay close to the Z-Wave specs whenever possible and they are very explicit about what the values 0 and 99 mean:
![grafik](https://user-images.githubusercontent.com/17641229/130404236-6213d106-003f-458f-8923-ffa85c2aa2fa.png)

I have the same shutters and they follow these rules. 99/open is open and 0/close is closed.
Not sure why it is different for you, but I suspect the wiring is not actually correct.

If anything, this is a feature request for applications (zwavejs2mqtt or the HA integration)
