### ISSUE TITLE
Problems adding Kwikset 888

### ISSUE THREAD

**Issue by mmigdol** [zwave-js/zwave-js#3221]
I've tried a couple of different ways, both with zwjs2mttq and HA with the zwjs addon.  The symptoms are similar -- the logs report that the Door Lock capability is not supported and the lock functions do not show up in the UI. 

See attached log and node dump from zwjs2mttq.
[migdol_210818.zip](https://github.com/zwave-js/zwavejs2mqtt/files/7009803/migdol_210818.zip)

**Comment by AlCalzone** [comment]
```
2021-08-18T19:14:33.007Z CNTRLR « [Node 005] received secure commands (S0)
                                  supported CCs:
                                  · Version
                                  · Anti-Theft
                                  controlled CCs:
```
Looks like the Anti-Theft functionality was enabled whereever you used the lock before. You'll have to disable it first before you can use the lock in Z-Wave JS.
