### ISSUE TITLE
Aeotec ZWA012 has incorrect parameters 22-24 and missing parameter 255

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#3271]
Reported in https://github.com/zwave-js/node-zwave-js/commit/ba6dbf63ce0bda1dbddb6bcb675ed0a98da9a587#commitcomment-55857202:

> The AEOTEC Dorr/Window 7 Pro Sensor does not support parameters 22,23,24 and they should be removed from this. Please see the bottom of this page: aeotec.freshdesk.com/support/solutions/articles/6000230465 where you will see parameter 21 and then parameter 255. The sensor will not report status for 22,23, or 24 and will cause timeout issues during the interview process.

> We seem to be missing Parameter 255 too.

**Comment by blhoward2** [comment]
Odd, those are in the engineering sheet. They must have removed them.
