### ISSUE TITLE
Missing device configuration: Fakro AMZ Solar / Device ID 0x0085-0x0005-0x0112

### ISSUE THREAD

**Issue by avrel-kb** [zwave-js/zwave-js#3282]
### Checklist

- [X] It is not in the [configuration DB](https://devices.zwave-js.io/?search=3)

- [X] It was not [merged recently](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Apr+is%3Aclosed) or has a [pending PR](https://github.com/zwave-js/node-zwave-js/pulls?q=is%3Aopen+is%3Apr)

### Which device is missing?

FAKRO AMZ Solar

### Manufacturer ID

0x0085

### Product Type

0x0005

### Product ID

0x0112

### Firmware Version

3.1

### Is the device listed on the Z-Wave Alliance website?

https://products.z-wavealliance.org/products/2627

### Do you have a manual?

Note: the configuration exist already but for Product ID 0x0002
https://devices.zwave-js.io/?jumpTo=0x0085:0x0005:0x0002:0.0
This configuration is working also for Product ID 0x0112

**Comment by AlCalzone** [comment]
@zwave-js-bot add fingerprint 0x0005:0x0112 to 0x0085:0x0005:0x0002:0.0
