### ISSUE TITLE
ZEN24-4.0 ramp rate bounds

### ISSUE THREAD

**Issue by reidprichard** [zwave-js/zwave-js#3317]
For their ZEN24 switch, Zooz specifies that parameter 9 can be set to 0 to disable the ramp behavior:
https://www.support.getzooz.com/kb/article/318-zen24-toggle-dimmer-ver-4-01-advanced-settings/

However, zen24_4.0.json prevents this from being set below 1. This prevents disabling the ramp, which causes a minimum 1s lag between flipping the switch and it triggering automations in Home Assistant.

**Comment by AlCalzone** [comment]
Accepting PRs

**Comment by reidprichard** [comment]
Gave it a shot - my first ever PR, but I think I did it right.
