### ISSUE TITLE
Hide BasicCC if another Actuator CC is supported by an endpoint

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#388]
From SDS14223:
A controlling node MUST NOT use the Basic Command Class for controlling nor showing status
(receiving report) of a node (or endpoint) if the controlling node controls at least one actuator
command class supported by a node (or endpoint). The actuator command classes are defined in the
Application Command Class specification ([2]).

**Comment by blhoward2** [comment]
Is there a way to ignore this mapping? GE switches and dimmers support double-tap up and double-tap down but you have to ignore the mapping and react to the BasicCC. Compliant to the standard or not that's how they work...

https://github.com/zwave-js/zwavejs2mqtt/issues/116
