### ISSUE TITLE
Check if we need to do additional cleanup after removeFailedNode

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#546]
e.g. deleting the node, raising the all nodes ready event, ...

**Comment by AlCalzone** [comment]
Fixed by #549

@CliffS I did some more changes regarding the `all nodes ready` logic (see also changelog). By default, nodes that are known to be dead (did not respond and cannot be asleep) are now ignored in the check. As soon as the status of all nodes is known and all alive nodes have been interviewed at least once, `all nodes ready` is emitted.

I did not include the check for `isFailed` yet because there's still an ordering issue for controller messages when a node is asleep

**Comment by CliffS** [comment]
@AlCalzone This looks perfect.  It means that the `all nodes ready` event will be reliable after the initial creation of the cache.  Thanks again for all the effort you're putting into this.
