### ISSUE TITLE
Rework the definition process for value IDs

### ISSUE THREAD

**Issue by AlCalzone** [zwave-js/zwave-js#552]
Some thoughts:
* There should be a central property of each CC that provides named access to all defined value IDs (or functions that return a value ID) as well as metadata 
* If possible, this property should be used in the decorators (think about this)
* It should be possible to define if this value is always accessible (e.g. writeonly values #532) and/or private
* This should replace or improve `registerValue`.

**Comment by robertsLando** [comment]
What about using [msg-pack-lite](https://www.npmjs.com/package/msgpack-lite) to decode the valueId json and encode it back to valueId? We could use it's encoding as unique Id. Also we could provide  a public `getId(ValueID valueId) : String` method to calcolate a the valueId unique id

**Comment by robertsLando** [comment]
Based on our slack conversation:

> Is  there a file where I can find all properties/ propertiesKeys of all command classes?

We could create a file with all properties/properties keys that actually are hardcoded in `protected [SET_VALUE]: ` 

Like https://github.com/zwave-js/node-zwave-js/blob/master/packages/zwave-js/src/lib/commandclass/MultilevelSwitchCC.ts#L249

**Comment by raman325** [comment]
As discussed in Discord, this could be used to auto generate CC documentation. Once you get there, please include whether the CC has stateless values
