### ISSUE TITLE
ZigBee USB ID 0658:0200 Sigma Designs, Inc. wird niccht vollständig inkludiert

### ISSUE THREAD

**Issue by olli0815** [zwave-js/zwave-js#682]
hi,

mein usb (ID 0658:0200 Sigma Designs, Inc. ) wird nicht sauber inkludiert
[
![zwave2 usb](https://user-images.githubusercontent.com/17963080/75090729-30aeab00-5566-11ea-87c6-33380a6c7f09.jpg)
](url)

die schnittstelle schon
![zwave2 usb2](https://user-images.githubusercontent.com/17963080/75090766-85522600-5566-11ea-9231-c08ac58e07ce.jpg)

**Comment by olli0815** [comment]
Vermissen nicht direkt, da ich den stick ja eh nicht anspreche.
Früher mit dem alten Adapter hingegen sah es so aus:
![Zwave USB 3](https://user-images.githubusercontent.com/17963080/75133825-7a210680-56dc-11ea-9950-75e6cb45415a.jpg)

aber wie gesagt an der Stelle wirklich "nice to have"

**Comment by AlCalzone** [comment]
Naja. Sinn macht das nicht wirklich beim Controller:

- Ready-Status gibt es
- Alive ist er immer
- Schlafen tut er nie
- Den events-Datenpunkt gibt es in meinem Adapter nicht
- Und Kommandoklassen (Basic) kann man ihm auch nicht senden

Die Bezeichnung könnte ich aber zumindest anzeigen lassen.

**Comment by AlCalzone** [comment]
Ich gehe davon aus, dass die nächste Version des Adapters dieses Wochenende kommt. Dann sollte das funktionieren.
