### ISSUE TITLE
Add a way to specify/configure that a ManufacturerProprietary command is supported

### ISSUE THREAD

**Issue by olli0815** [zwave-js/zwave-js#683]
Hi,

trotz libopenzwave habe ich keine erweiterten Datenpunkte zum Steuern des Neigungswinkles der Lamellen im Roller shutter .

**Comment by AlCalzone** [comment]
Der Adapter ist komplett unabhängig von OpenZWave, das ist der Hauptgrund, warum er überhaupt existiert.
Die Fibaro-Klasse ist eigentlich implementiert, aber ungetestet. Ich bräuchte einen Log vom Adapterstart bis zum Abschluss des Interviews des betreffenden Nodes. Am besten vorher Cache löschen.

**Comment by olli0815** [comment]
Kannst du damit etwas anfeangen? sonst muss ich das Log.file nochmal vom server fummeln, da ich es über den ioBroker nicht (mehr) downloaden kann..

und logfile..

edit: deleted wrong logs

**Comment by AlCalzone** [comment]
Ne, ich meinte das Debug-Log des Adapters. Ist im Test-Thread beschrieben wie du da dran kommst.

**Comment by olli0815** [comment]
[zwave-2870.log](https://github.com/AlCalzone/node-zwave-js/files/4243620/zwave-2870.log)

besser?

**Comment by AlCalzone** [comment]
Jup, schaue ich bei Gelegenheit genauer an.

**Comment by AlCalzone** [comment]
Kannst du mir noch verraten, welcher Node das ist?

**Comment by olli0815** [comment]
z.b 4,5,6,7,10 & 11 das sind die roller shutter
da fehlt "Venetian blind tilt position" via MANUFACTURER_PROPRIETARY wie hier früher im alten zwave

![roller shutter](https://user-images.githubusercontent.com/17963080/75158780-2a136580-5717-11ea-80c0-8a0045c033e3.png)

**Comment by AlCalzone** [comment]
Ah, ich sehe was los ist. Die Interview-Prozedur für die Kommandoklasse fehlt noch. Muss mal schauen, wie das funktioniert.

**Comment by AlCalzone** [comment]
Probably depends on https://github.com/AlCalzone/node-zwave-js/issues/552

**Comment by olli0815** [comment]
perferkt.
Tausend Dank schonmal und weiter so!!
Wenn ich was testen kann, gerne

**Comment by AlCalzone** [comment]
Das wird noch etwas dauern. Sage Bescheid.

**Comment by AlCalzone** [comment]
In der nächsten Version sollte es hoffentlich funktionieren. Würde mich dann über Feedback freuen.

**Comment by olli0815** [comment]
In der nächsten, oder ist es schon im git?

**Comment by AlCalzone** [comment]
Nächste Adapter-Version. Selbst wenn es auf github ist, hilft es nicht, da ich diese Library zuerst in einer neuen Version veröffentlichen muss, bevor es mit dem Adapter funktioniert.
