### ISSUE TITLE
Removing a device from the network.

### ISSUE THREAD

**Issue by RoboPhred** [zwave-js/zwave-js#743]
I have a failed switch I need to remove from the network, as well as several I am decommissioning.  I have unpaired the devices, and all now show up as a dead status when listing nodes.

I read through the docs but could not find any mention of removing a device from the network, just exclusion mode which I already ran using the Aeon stick gen5 in independent mode.

Is there an api call to remove a node from the network?

**Comment by AlCalzone** [comment]
Yes! The docs are a bit outdated, but you're looking for this:
https://github.com/AlCalzone/node-zwave-js/blob/0b1338c31305b14199e03fa20a151458dd5dc97a/src/lib/controller/Controller.ts#L1364

so: `driver.controller.removeFailedNode(nodeId)`

**Comment by RoboPhred** [comment]
Thanks, this is what I need.
